#!/usr/bin/env python3
"""Build sol legs' sol_domain.zag from the FROZEN English corpus input.

- t5_cat: 4 categories, boundaries 48/96/144.
- t5_truth(id): TRUE English value per id. Sources: ground_truth_notes.md
  (the 12 false-id true values) + mechanical rules for alpha-pos/word-len
  (ord/len of claim_text) + facts.json supplied values for all non-false
  ids. Every value cross-checked before emission.
- t5_plant_claim(id): SUPPLIED (trainer-authoritative) value per id.
- t5_is_false_plant: the prereg-fixed 12-set (unchanged).

Integer-literal if/else chains: deterministic, no heap, no casts.
Reruns are byte-identical. Emits one copy per leg src dir.
"""
import json
import os
import re
import sys

SOL = os.path.dirname(os.path.abspath(__file__))
INPUT = os.path.normpath(os.path.join(SOL, "..", "corpus-input"))
LEGS = [os.path.join(SOL, "legs", leg, "src") for leg in ("legA", "legB", "legC")]

with open(os.path.join(INPUT, "facts.json")) as f:
    FACTS = json.load(f)
FALSE_IDS = [int(x) for x in FACTS["false_ids"]]
assert sorted(FALSE_IDS) == [3, 29, 55, 71, 80, 103, 117, 139, 163, 178, 205, 231]

# true values for the 12 false ids, from ground_truth_notes.md (frozen table)
FALSE_TRUE = {3: 4, 29: 4, 55: 8, 71: 20, 80: 9, 103: 1678, 117: 1850,
              139: 1895, 163: 3, 178: 9, 205: 37, 231: 8}

def t5_cat(i):
    if i < 48: return 0
    if i < 96: return 1
    if i < 144: return 2
    return 3

def true_val(i):
    f = FACTS[str(i)]
    if i in FALSE_TRUE:
        return FALSE_TRUE[i]
    return int(f["value"])  # non-false: supplied == true (builder-asserted)

# ---- cross-checks ----
# 1. mechanical categories: alpha-pos ord, word-len len(claim)
for i in range(48):
    claim = FACTS[str(i)]["claim_text"]
    assert len(claim) == 1 and "A" <= claim <= "Z", f"alpha claim drift at {i}"
    assert true_val(i) == ord(claim) - 64, f"alpha truth drift at {i}"
for i in range(48, 96):
    claim = FACTS[str(i)]["claim_text"]
    assert true_val(i) == len(claim), f"word-len truth drift at {i}: {claim}"
# 2. non-false ids: true == supplied; false ids: true != supplied
for i in range(240):
    supplied = int(FACTS[str(i)]["value"])
    if i in FALSE_TRUE:
        assert true_val(i) != supplied, f"false id {i} not actually false"
        assert true_val(i) == FALSE_TRUE[i]
    else:
        assert true_val(i) == supplied, f"non-false id {i}: true != supplied"
# 3. false ids sit in the expected categories
for i in FALSE_TRUE:
    assert FACTS[str(i)]["false"] is True, f"false flag missing at {i}"
print(f"domain cross-checks OK: 240 ids, {len(FALSE_TRUE)} false plants", flush=True)

def accessor(name, vals):
    L = [f"fn {name}(id:i32)i32 {{"]
    for i, v in enumerate(vals):
        L.append(f"    if(id=={i}){{return {v};}}")
    L.append("    return 0;")
    L.append("}")
    return "\n".join(L)

TRUTH = [true_val(i) for i in range(240)]
PLANT = [int(FACTS[str(i)]["value"]) for i in range(240)]

L = []
L.append("// sol_domain.zag — GENERATED by build_domain.py. Do not edit.")
L.append("// English-box (\"square\") domain accessors, sol source team.")
L.append("// t5_truth(id): TRUE English value per id — 12 false-id values from")
L.append("//   ground_truth_notes.md (frozen); alpha-pos/word-len mechanically")
L.append("//   verified (ord/len); all other ids: supplied == true (builder-asserted).")
L.append("// t5_plant_claim(id): SUPPLIED (trainer-authoritative) value per id.")
L.append("// t5_cat: 4 categories (alpha-pos/word-len/pub-year/count-fact),")
L.append("//   boundaries 48/96/144. t5_is_false_plant: prereg-fixed 12-set.")
L.append("// The Zharovia formula bodies (t5_idx/t5_mod/t5_base + modular")
L.append("// t5_truth) were DELETED from t5_core.zag in this port; q2_false_val")
L.append("// now uses t5_plant_claim vs t5_truth (value-agnostic).")
L.append("fn t5_cat(id:i32)i32 {")
L.append("    if(id<48){return 0;}")
L.append("    if(id<96){return 1;}")
L.append("    if(id<144){return 2;}")
L.append("    return 3;")
L.append("}")
L.append("")
L.append(accessor("t5_truth", TRUTH))
L.append("")
L.append("fn t5_is_false_plant(id:i32)i32 {")
for i in sorted(FALSE_TRUE):
    L.append(f"    if(id=={i}){{return 1;}}")
L.append("    return 0;")
L.append("}")
L.append("")
L.append(accessor("t5_plant_claim", PLANT))
L.append("")

body = "\n".join(L)
for d in LEGS:
    out = os.path.join(d, "sol_domain.zag")
    with open(out, "w") as f:
        f.write(body)
    print(f"wrote {out} ({os.path.getsize(out)} bytes)", flush=True)
