#!/usr/bin/env python3
# Generates src/syn_table.zag from SYN_TABLE_V1.txt. No hand transcription:
# the embedded bytes are asserted byte-identical to the table file.
# Also replicates the frozen Zag stemmer to assert zero stem-key collisions
# and prints the derived stem->canon map for review.
import sys

def stem(t):
    n = len(t)
    if n > 4 and t.endswith('ing') and n - 3 >= 3: return t[:-3]
    if n > 3 and t.endswith('ed') and n - 2 >= 3: return t[:-2]
    if n > 4 and t.endswith('es') and n - 2 >= 3: return t[:-2]
    if n > 3 and t.endswith('s') and t[-2] != 's' and n - 1 >= 3: return t[:-1]
    return t

pairs = []
for ln in open('SYN_TABLE_V1.txt'):
    ln = ln.rstrip('\n')
    if not ln or ln.startswith('#'):
        continue
    assert ln.count('|') == 1, f'bad line: {ln}'
    a, b = ln.split('|')
    assert a and b and all(c.isalnum() and c.islower() or c.isdigit() for c in a + b), f'bad word: {ln}'
    pairs.append((a, b))

print(f'pairs: {len(pairs)}')
keymap = {}
for a, b in pairs:
    sa, sb = stem(a), stem(b)
    canon = min(sa, sb)
    for k in (sa, sb):
        assert k not in keymap, f'KEY COLLISION on stem {k!r} (from {(a,b)})'
        keymap[k] = canon

lit = ''.join(f'{a}|{b}\\n' for a, b in pairs)
body = '// GENERATED by gen_syn_table.py from SYN_TABLE_V1.txt — do not edit.\n'
body += '// Byte-identical to the frozen table file (asserted by build_ws2b2).\n'
body += 'fn syn_table_raw()[]u8 {\n'
body += f'    return "{lit}";\n'
body += '}\n'
open('src/syn_table.zag', 'w').write(body)

# verify embedded bytes round-trip (decode the Zag \n escapes)
src = open('SYN_TABLE_V1.txt').read()
raw_lines = [l for l in src.split('\n') if l and not l.startswith('#')]
assert lit.replace('\\n', '\n') == ''.join(l + '\n' for l in raw_lines), 'round-trip mismatch'
print(f'wrote src/syn_table.zag ({len(body)} bytes), round-trip OK')
print(f'stem keys: {len(keymap)}, canons: {len(set(keymap.values()))}')
