#!/usr/bin/env python3
"""gen_lut.py -- FS-F2C: emit the sRGB->linear x10000 lookup table as Zag source.

LUT[c] = round(10000 * lin(c/255)), lin = c/255/12.92 for c/255 <= 0.04045
else ((c/255+0.055)/1.055)^2.4. This is the exact inverse of the gamma the
R2-7 generator applies after its linear-space Bradford illuminant rendering,
so the formation rule discounts the illuminant in the space where it is
diagonal. Deterministic: the table is a pure function of the definition.
Output: src/lut_frag.zag containing fn f_linlut(c:i32) i64 (if-chain, the
same proven pattern as f_tbcoeff in FS-E2's fs2_form.zag).
"""
import os

def lin_lut():
    t = []
    for c in range(256):
        x = c / 255.0
        lin = x / 12.92 if x <= 0.04045 else ((x + 0.055) / 1.055) ** 2.4
        t.append(int(round(lin * 10000)))
    return t

def main():
    t = lin_lut()
    assert t[0] == 0 and t[255] == 10000 and all(b >= a for a, b in zip(t, t[1:]))
    out = []
    out.append("// lut_frag.zag — GENERATED by src/gen_lut.py — do not hand-edit.")
    out.append("// sRGB byte -> linear x10000. Exact inverse of the R2-7 generator gamma.")
    out.append("fn f_linlut(c:i32) i64 {")
    for c, v in enumerate(t):
        out.append("    if(c == %d) { return %d; }" % (c, v))
    out.append("    return 10000;")
    out.append("}")
    out.append("")
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "lut_frag.zag")
    with open(path, "w") as fh:
        fh.write("\n".join(out))
    print("wrote %s (256 entries, t[0]=%d t[128]=%d t[255]=%d)" % (path, t[0], t[128], t[255]))

if __name__ == "__main__":
    main()
