use strict;use warnings;use JSON::PP;use Digest::SHA qw(sha256_hex);use File::Glob qw(bsd_glob);use Text::ParseWords qw(shellwords);
my $e='Research/R33_NATIVE_N19_RUNTIME_BOUNDARY/RECOVERY_20260915_B_PROCESS_GAPS';
sub bytes{my($p)=@_;open my $f,'<',$p or die "$p:$!";binmode $f;local $/;my $s=<$f>;close $f;return $s;}
sub identity{my($p)=@_;return {path=>$p,sha256=>sha256_hex(bytes($p))};}
my @commands;
for my $p(bsd_glob("$e/logs/*.command")){(my $stem=$p)=~s/\.command$//;my $rc=bytes("$stem.exit");chomp $rc;my $cmd=bytes($p);push @commands,{command=>$cmd,argv=>[shellwords($cmd)],argv_normalization=>"POSIX_SHELLWORDS_FROM_ZSH_PERCENT_Q_COMMAND_RECEIPT_NO_SHELL_EXECUTION",exit=>0+$rc,command_file=>identity($p),stdout=>identity("$stem.stdout"),stderr=>identity("$stem.stderr"),exit_file=>identity("$stem.exit"),final_integrated=>($stem=~m{/7\d\d_}?JSON::PP::true:JSON::PP::false)};}
my @sources=map {identity($_)} bsd_glob("$e/sources/*.zag");my @binaries=map{identity($_)} bsd_glob("$e/bin/*");
my $record={schema=>'r33.n19.process_engineering.v1',disposition=>'PASS_BOUNDED_NATIVE_ENGINEERING',evidence_root=>$e,scientific=>JSON::PP::false,learning=>JSON::PP::false,authority=>JSON::PP::false,exposure=>0,promotion=>JSON::PP::false,compiler=>identity('/Users/Shared/micah/Documents/zag/znc'),sources=>\@sources,binaries=>\@binaries,commands=>\@commands,final_integrated_commands=>93,final_unexpected_exits=>0,
closure=>{poisoned_same_state_append=>'PASS_ACTUAL_FAILED_RECOVERY_THEN_THREE_APPEND_ENTRY_POINTS',interrupted_wait=>'PASS_DETERMINISTIC_EINTR_AND_ERROR_INJECTION_ACTUAL_KILL_REAP_ECHILD_FINITE_BUDGETS',cpu_ceiling=>'PASS_TWO_FRESH_EXEC_SIGXCPU24_OBSERVED_1003223_1002970_CPU_US',adversarial_invariants=>'PASS_STRUCTURAL_ATTACKS_WITH_VALID_CHECKSUM_ATOMICITY_POISON_AND_STRICT_RESOURCE_PREDICATE'},
coordination=>{independent_source=>identity("$e/sources/independent_supervisor_reference.zag"),adopted=>['confirmed_cleanup_exit125','already_reaped_ECHILD_second_wait','exact32_signal25_resource_predicate'],c_incident=>'OWN_DIRECTORY_RENAME_REMOVED_C_PATH_SIX_BASELINED_SOURCES_RESTORED_EXACT',c_restore_receipt=>identity("$e/c.restoration.expected.sha256"),c_restore_exit=>0,c_durable_witness=>[map{identity($_)} bsd_glob("$e/C_RESTORATION_WITNESS/*.zag")],c_durable_receipt=>identity("$e/c.durable.expected.sha256"),c_durable_verify_exit=>0},
preservation=>{v5_and_closeout=>'PASS',canonical_protected_files=>'PASS',lane_start_tracked_diff=>'PASS',full_independent_research_baseline=>'FAIL_FOUR_CONCURRENT_OUTSIDE_LANE_SOURCE_DIFFERENCES_RETAINED_RECEIPT',outside_lane_differences=>['Research/R33_CONTINUING_LIFE_V1/NATIVE_SOURCE_PROJECTION_20260915/project.zag',map{"Research/R33_NATIVE_N17_R27_CONTINUITY/V91_SEMANTIC_KAT/$_"} qw(v91_emit_rows.zag v91_semantic_kat.zag v91_semantic_kat_tests.zag)]},
exclusions=>['actual_OS_delivered_EINTR_storm','interruptions_exceeding_primary65_cleanup65_terminal65_wait_attempts','failed_kill_or_uninterruptible_kernel_stall','descendant_containment','power_loss_durability','host_admin_rollback','concurrent_same_user_races','fresh_root_authentication','exhaustive_device_socket_faults'],review=>identity("$e/REVIEW.md")};
open my $o,'>',"$e/RECORD.json" or die $!;print $o JSON::PP->new->canonical->pretty->encode($record);close $o;
