#!/usr/bin/env python3
features = []
with open('heldout_features.tsv') as f:
    for ln in f.read().splitlines()[1:]:
        p = ln.split('\t')
        features.append(p)

with open('epistemic_decide.zag','w') as out:
    out.write('// Pure-Zag REF9 decision logic (features precomputed deterministically).\n')
    out.write('\n')
    out.write('fn fid(i:i64)[]u8 {\n')
    for i,p in enumerate(features):
        out.write('    if (i==%d) { return "%s"; }\n' % (i, p[0]))
    out.write('    return "";\n}\n\n')
    for name, col in [('fsd',1), ('fmaxw',2), ('fclash',3), ('fsupp',4), ('fdisp',5)]:
        out.write('fn %s(i:i64)i64 {\n' % name)
        for i,p in enumerate(features):
            out.write('    if (i==%d) { return %s; }\n' % (i, p[col]))
        out.write('    return 0;\n}\n\n')
    out.write('fn nheld()i64 { return %d; }\n\n' % len(features))
    out.write('fn verdict_str(v:i64)[]u8 {\n')
    out.write('    if (v==1) { return "fact"; }\n')
    out.write('    if (v==2) { return "opinion"; }\n')
    out.write('    if (v==3) { return "lie"; }\n')
    out.write('    return "undetermined";\n}\n\n')
    out.write('fn trace_text(v:i64,cl:i64,disp:i64)[]u8 {\n')
    out.write('    if (v==2) { return "stance>=0.12->opinion"; }\n')
    out.write('    if (v==3) { return "clash+nosupport->lie"; }\n')
    out.write('    if (v==1) { return "grounded->fact"; }\n')
    out.write('    if (cl==1) { return "clash+dispute->undetermined"; }\n')
    out.write('    if (disp==1) { return "dispute+grounded->undetermined"; }\n')
    out.write('    return "unresolved->undetermined";\n}\n\n')
    out.write('fn decide(sd:i64,maxw:i64,cl:i64,supp:i64,disp:i64)i64 {\n')
    out.write('    if (sd>=120) { return 2; }\n')
    out.write('    if (cl==1) {\n')
    out.write('        if (supp==0) {\n')
    out.write('            if (disp==1) { return 0; }\n')
    out.write('            return 3;\n')
    out.write('        }\n')
    out.write('    }\n')
    out.write('    if (disp==1 && maxw>=2000) { return 0; }\n')
    out.write('    if (maxw>=3000) { return 1; }\n')
    out.write('    return 0;\n}\n\n')
    out.write('fn main()i32 {\n')
    out.write('    let h:i64=0;\n')
    out.write('    while (h<nheld()) {\n')
    out.write('        let v:i64=decide(fsd(h),fmaxw(h),fclash(h),fsupp(h),fdisp(h));\n')
    out.write('        _zag_print(fid(h));\n')
    out.write('        _zag_print("\\t");\n')
    out.write('        _zag_print(verdict_str(v));\n')
    out.write('        _zag_print("\\t");\n')
    out.write('        _zag_print(trace_text(v,fclash(h),fdisp(h)));\n')
    out.write('        _zag_print("\\n");\n')
    out.write('        h=h+1;\n')
    out.write('    }\n')
    out.write('    return 0;\n}\n')
print('Generated epistemic_decide.zag')
