#!/usr/bin/env python3
"""PAM ROUND 2 — frozen fixture suite R2A generator (R2-7 build crew).

FROZEN SUITE SPEC: ../../preregs/R2_FIXTURE_SET.md
  MASTER seed = 20260923 (new; round 1's was 20260921).
  Stream ids: normal-ext = 400+taskidx, adversarial = 500+taskidx,
              second-presentation (R2-7 prereg s3) = 700+taskidx.
  Per-fixture seed = splitmix64(splitmix64(MASTER ^ stream*0x9E3779B97F4A7C15)
                     ^ index*0xBF58476D1CE4E5B9)  (same construction as harness/gen.py)
  Task index: colordisc=0, colorconst=1, shapetrans=2, pitchdisc=3, timbredisc=4, motiondir=5.

Fixture container R2FX (frozen here, documented in R2_FIXTURE_SPEC_R27.md):
  u32 magic 0x52324658 ("R2FX"), u32 task, u32 index, u32 family_id,
  u32 f_off, u32 f_len, u32 g_off, u32 g_len   (header = 32 bytes)
  F = formation evidence span (what the percept pipeline sees).
  G = challenge evidence span (disjoint bytes; the controlled intervention:
      neutral illuminant / unoccluded quadrant / uncorrupted token /
      clean high-contrast motion). G is NEVER shown to the formation path.

Counts (frozen spec; note: the spec's normal total "4,260" is arithmetically
inconsistent with its own per-task table which sums to 5,100 — the per-task
table is authoritative here and the inconsistency is recorded in BUILD_NOTES):
  normal r2n:    colordisc 1080, colorconst 720, shapetrans 1296,
                 pitchdisc 720, timbredisc 720, motiondir 564  (= 5,100)
  adversarial r2a: colordisc 1150 (COL-1 400 / COL-2 350 / COL-3 400),
                 colorconst 680 (CCN-1 340 / CCN-2 340),
                 shapetrans 1150 (SHP-1 400 / SHP-2 450 / SHP-3 300),
                 pitchdisc 1150 (PTC-1 350 / PTC-2 400 / PTC-3 400),
                 timbredisc 690 (TMB-1 250 / TMB-2 250 / TMB-3 190),
                 motiondir 995 (MOT-1 350 / MOT-2 350 / MOT-3 295)  (= 4,815)
  second-presentation r2a2: 5,000 = 4,815 same-(family,index) on stream 700+t
                 + 185 family-assigned from the frozen harness adversarial set.

Deterministic: every draw from the per-fixture splitmix64 stream. No wall
clock, no os.urandom. Regenerating with the same code + photo pool yields
byte-identical fixtures (verified by MANIFEST.sha256).

Outputs (OUTDIR):
  r2n/<id>.r2fx + .truth, r2a/<id>.r2fx + .truth, r2a2/<id>.r2fx + .truth
  MANIFEST.sha256  (covers every generated byte)
  gen_ledger.jsonl (id, task, family, truth, seed, sha256 per fixture)
"""
import math, os, struct, sys, hashlib, json
import numpy as np
from PIL import Image

MASTER = 20260923
TASKS = ["colordisc", "colorconst", "shapetrans", "pitchdisc", "timbredisc", "motiondir"]
TIDX = {t: i for i, t in enumerate(TASKS)}
STREAM_NORMAL, STREAM_ADV, STREAM_SECOND = 400, 500, 700

HERE = os.path.dirname(os.path.abspath(__file__))
PHOTO_DIR = os.path.normpath(os.path.join(HERE, "..", "..", "..", "..", "..",
                                          "rebuild", "harness", "fixtures", "_photos"))
OUTDIR = os.environ.get("R2A_OUT",
        os.path.normpath(os.path.join(HERE, "..", "fixtures_R2A")))

# ---------------------------------------------------------------- PRNG
MASK64 = (1 << 64) - 1
C1 = 0x9E3779B97F4A7C15
C2 = 0xBF58476D1CE4E5B9

def splitmix64(state):
    state = (state + C1) & MASK64
    z = state
    z = ((z ^ (z >> 30)) * C2) & MASK64
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK64
    return z ^ (z >> 31)

class Rng:
    def __init__(self, seed):
        self.s = seed & MASK64
    def u64(self):
        self.s = (self.s + C1) & MASK64
        z = self.s
        z = ((z ^ (z >> 30)) * C2) & MASK64
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK64
        return z ^ (z >> 31)
    def uniform(self):
        return (self.u64() >> 11) * (1.0 / (1 << 53))
    def frange(self, lo, hi):
        return lo + (hi - lo) * self.uniform()
    def irange(self, lo, hi):  # [lo, hi)
        return lo + self.u64() % (hi - lo)
    def pick(self, seq):
        return seq[self.u64() % len(seq)]
    def coin(self, p=0.5):
        return self.uniform() < p

def stream_seed(master, stream, index):
    h = splitmix64((master ^ (stream * C1)) & MASK64)
    return splitmix64((h ^ (index * C2)) & MASK64)

def _sm_integers(rng, low, high, shape):
    """Deterministic integer noise in [low, high) from pure splitmix64.

    Replaces np.random.default_rng: every draw comes from the fixture's
    splitmix stream, so the suite is bit-reproducible without NumPy's
    version-dependent RNG. Uses np.fromiter to batch the Python-level draws.
    """
    n = 1
    for d in shape:
        n *= d
    span = high - low
    vals = np.fromiter((rng.u64() for _ in range(n)), dtype=np.uint64, count=n)
    return (low + (vals % np.uint64(span))).astype(np.int16).reshape(shape)

# ------------------------------------------------------- color math (from harness/gen.py)
def srgb_to_linear(c):
    c /= 255.0
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

def linear_to_srgb(c):
    c = max(0.0, min(1.0, c))
    v = 12.92 * c if c <= 0.0031308 else 1.055 * (c ** (1.0 / 2.4)) - 0.055
    return int(round(max(0.0, min(1.0, v)) * 255))

XYZ_M = ((0.4124564, 0.3575761, 0.1804375),
         (0.2126729, 0.7151522, 0.0721750),
         (0.0193339, 0.1191920, 0.9503041))
XYZ_MI = (( 3.2404542, -1.5371385, -0.4985314),
          (-0.9692660,  1.8760108,  0.0415560),
          ( 0.0556434, -0.2040259,  1.0572252))
BRAD = ((0.8951, 0.2664, -0.1614),
        (-0.7502, 1.7135, 0.0367),
        (0.0389, -0.0685, 1.0296))
BRAD_I = ((0.9869929, -0.1470543, 0.1599627),
          (0.4323053, 0.5183603, 0.0492912),
          (-0.0085287, 0.0400428, 0.9684867))

def rgb_to_xyz(r, g, b):
    rl, gl, bl = srgb_to_linear(r), srgb_to_linear(g), srgb_to_linear(b)
    return tuple(XYZ_M[i][0]*rl + XYZ_M[i][1]*gl + XYZ_M[i][2]*bl for i in range(3))

def xyz_to_lab(x, y, z):
    xn, yn, zn = 0.95047, 1.0, 1.08883
    def f(t):
        return t ** (1/3) if t > 0.008856 else 7.787 * t + 16/116
    fx, fy, fz = f(x/xn), f(y/yn), f(z/zn)
    return (116*fy - 16, 500*(fx - fy), 200*(fy - fz))

def rgb_to_lab(r, g, b):
    return xyz_to_lab(*rgb_to_xyz(r, g, b))

def delta_e_2000(lab1, lab2):
    L1, a1, b1 = lab1; L2, a2, b2 = lab2
    kL = kC = kH = 1.0
    C1_ = math.hypot(a1, b1); C2_ = math.hypot(a2, b2)
    Cb = (C1_ + C2_) / 2
    G = 0.5 * (1 - math.sqrt(Cb**7 / (Cb**7 + 25**7)))
    ap1 = (1 + G) * a1; ap2 = (1 + G) * a2
    Cp1 = math.hypot(ap1, b1); Cp2 = math.hypot(ap2, b2)
    def hp(ap, b):
        if ap == 0 and b == 0: return 0.0
        h = math.degrees(math.atan2(b, ap))
        return h + 360 if h < 0 else h
    hp1, hp2 = hp(ap1, b1), hp(ap2, b2)
    dL = L2 - L1; dC = Cp2 - Cp1
    if Cp1 * Cp2 == 0:
        dh = 0.0
    else:
        dh = hp2 - hp1
        if dh > 180: dh -= 360
        elif dh < -180: dh += 360
    dH = 2 * math.sqrt(Cp1 * Cp2) * math.sin(math.radians(dh / 2))
    Lbp = (L1 + L2) / 2; Cbp = (Cp1 + Cp2) / 2
    if Cp1 * Cp2 == 0:
        hbp = hp1 + hp2
    else:
        hbp = (hp1 + hp2) / 2 if abs(hp1 - hp2) <= 180 else (hp1 + hp2 + 360) / 2 if hp1 + hp2 < 360 else (hp1 + hp2 - 360) / 2
    T = (1 - 0.17*math.cos(math.radians(hbp-30)) + 0.24*math.cos(math.radians(2*hbp))
         + 0.32*math.cos(math.radians(3*hbp+6)) - 0.20*math.cos(math.radians(4*hbp-63)))
    dRo = 30 * math.exp(-((hbp - 275) / 25) ** 2)
    Rc = 2 * math.sqrt(Cbp**7 / (Cbp**7 + 25**7))
    Sl = 1 + 0.015 * (Lbp - 50) ** 2 / math.sqrt(20 + (Lbp - 50) ** 2)
    Sc = 1 + 0.045 * Cbp
    Sh = 1 + 0.015 * Cbp * T
    Rt = -math.sin(math.radians(2 * dRo)) * Rc
    return math.sqrt((dL/(kL*Sl))**2 + (dC/(kC*Sc))**2 + (dH/(kH*Sh))**2 + Rt*(dC/(kC*Sc))*(dH/(kH*Sh)))

ILLUM = {
    "d65":   (0.95047, 1.00000, 1.08883),
    "warm":  (1.09850, 1.00000, 0.35585),
    "cool":  (0.99180, 1.00000, 0.67390),
    "xblue": (0.62000, 0.85000, 1.75000),
    "xred":  (1.70000, 0.90000, 0.45000),
}

def apply_illuminant(rgb, illum_xyz):
    x, y, z = rgb_to_xyz(*rgb)
    src = (0.95047, 1.0, 1.08883)
    lms_s = [sum(BRAD[i][j]*v for j, v in enumerate((x, y, z))) for i in range(3)]
    lms_wsrc = [sum(BRAD[i][j]*v for j, v in enumerate(src)) for i in range(3)]
    lms_wdst = [sum(BRAD[i][j]*v for j, v in enumerate(illum_xyz)) for i in range(3)]
    lms = [lms_s[i] * lms_wdst[i] / lms_wsrc[i] for i in range(3)]
    xa = sum(BRAD_I[0][j]*lms[j] for j in range(3))
    ya = sum(BRAD_I[1][j]*lms[j] for j in range(3))
    za = sum(BRAD_I[2][j]*lms[j] for j in range(3))
    rl = XYZ_MI[0][0]*xa + XYZ_MI[0][1]*ya + XYZ_MI[0][2]*za
    gl = XYZ_MI[1][0]*xa + XYZ_MI[1][1]*ya + XYZ_MI[1][2]*za
    bl = XYZ_MI[2][0]*xa + XYZ_MI[2][1]*ya + XYZ_MI[2][2]*za
    return (linear_to_srgb(rl), linear_to_srgb(gl), linear_to_srgb(bl))

# --------------------------------- spectral model (colordisc challenge path)
# A surface = 6-band spectrum in [0,1]. Rendered linear RGB = M @ (s .* illum),
# then linear->sRGB. M is a FIXED instrument matrix (documented here).
# NOTE 2026-09-23: M is scaled by 0.45 so typical spectra land in-gamut
# (unscaled, bright spectra saturated to white and hid perturbations).
M_SPEC = 0.45 * np.array([
    [0.05, 0.25, 0.55, 0.75, 0.45, 0.15],   # R sensitivity
    [0.02, 0.15, 0.45, 0.85, 0.70, 0.30],   # G sensitivity
    [0.30, 0.55, 0.45, 0.25, 0.10, 0.05],   # B sensitivity
])
BAND_ILLUM = {
    "d65":  np.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0]),
    "warm": np.array([1.30, 1.15, 1.00, 0.85, 0.70, 0.60]),
    "cool": np.array([0.60, 0.75, 0.95, 1.05, 1.20, 1.35]),
}
# Nullspace of M (3-dim): spectral moves invisible to the RGB camera.
_NN = None
def _nullspace():
    global _NN
    if _NN is None:
        u, s, vh = np.linalg.svd(M_SPEC)
        _NN = vh[3:].T  # 6x3
    return _NN

def spec_to_srgb(spec, illum="d65"):
    lin = M_SPEC @ (np.asarray(spec, dtype=float) * BAND_ILLUM[illum])
    return (linear_to_srgb(float(lin[0])), linear_to_srgb(float(lin[1])),
            linear_to_srgb(float(lin[2])))

def spec_l1_u16(s1, s2):
    return int(round(sum(abs(a - b) for a, b in zip(s1, s2)) * 65535))

def rgb_euclid(c1, c2):
    return math.sqrt(sum((a - b) ** 2 for a, b in zip(c1, c2)))

def _draw_spec(rng, lo=0.15, hi=0.85):
    return [rng.frange(lo, hi) for _ in range(6)]

def _render_patch(rng, srgb, size=32, noise=3):
    px = np.zeros((size, size, 3), dtype=np.int16)
    px[:, :] = srgb
    if noise:
        px += np.array([[rng.irange(-noise, noise + 1) for _ in range(3)]
                        for _ in range(size * size)]).reshape(size, size, 3)
    return np.clip(px, 0, 255).astype(np.uint8).tobytes()

# ------------------------------------------------------- photo pool (frozen bytes)
_PHOTOS = None
def photos():
    global _PHOTOS
    if _PHOTOS is None:
        _PHOTOS = []
        for i in range(170):
            p = os.path.join(PHOTO_DIR, "ph%03d.jpg" % i)
            im = Image.open(p).convert("RGB")
            _PHOTOS.append(np.asarray(im, dtype=np.uint8))
    return _PHOTOS

def photo_crop(rng, w, h):
    ph = rng.pick(photos())
    ph_h, ph_w = ph.shape[:2]
    x = rng.irange(0, ph_w - w + 1)
    y = rng.irange(0, ph_h - h + 1)
    return ph[y:y + h, x:x + w].copy(), (rng.u64() % 170, x, y)

def apply_illum_np(px, illum_xyz, exposure=1.0):
    """px: uint8 HxWx3 -> illuminant-rendered uint8 (vectorized Bradford approx
    via per-pixel apply_illuminant would be slow; use diagonal in linear RGB
    fitted per illuminant). For honesty we keep the exact Bradford on a
    32-entry LUT per channel triple? Simpler: exact per-pixel via numpy
    tensordot implementation of the Bradford chain."""
    lin = np.zeros_like(px, dtype=np.float64)
    c = px.astype(np.float64) / 255.0
    mask = c <= 0.04045
    lin[mask] = c[mask] / 12.92
    lin[~mask] = ((c[~mask] + 0.055) / 1.055) ** 2.4
    XYZ = np.tensordot(lin, np.array(XYZ_M).T, axes=1)  # HxWx3
    BR = np.array(BRAD); BRI = np.array(BRAD_I)
    src = np.array([0.95047, 1.0, 1.08883]); dst = np.array(illum_xyz)
    lms_s = np.tensordot(XYZ, BR.T, axes=1)
    wsrc = BR @ src; wdst = BR @ dst
    lms = lms_s * (wdst / wsrc)
    XYZ2 = np.tensordot(lms, BRI.T, axes=1)
    lin2 = np.tensordot(XYZ2, np.array(XYZ_MI).T, axes=1) * exposure
    lin2 = np.clip(lin2, 0, 1)
    m2 = lin2 <= 0.0031308
    out = np.zeros_like(lin2)
    out[m2] = 12.92 * lin2[m2]
    out[~m2] = 1.055 * (lin2[~m2] ** (1.0 / 2.4)) - 0.055
    return (np.clip(out, 0, 1) * 255 + 0.5).astype(np.uint8)

# ------------------------------------------------------- R2FX container
R2FX_MAGIC = 0x52324658
def write_r2fx(path, task, index, family, f_bytes, g_bytes):
    hdr = struct.pack("<8I", R2FX_MAGIC, task, index, family,
                      32, len(f_bytes), 32 + len(f_bytes), len(g_bytes))
    with open(path, "wb") as f:
        f.write(hdr); f.write(f_bytes); f.write(g_bytes)

def write_truth(path, value):
    with open(path, "w") as f:
        f.write("truth=%s\n" % value)

# ============================================================ t0 colordisc
# F = patchA(32x32 RGB) + patchB(32x32 RGB) = 6144 B
# G = patchA RGB + patchB RGB (neutral re-render, fresh noise) + 2x6 u16 spectra
CD_F = 32 * 32 * 3 * 2
CD_G = CD_F + 24

def _cd_pair(rng, s1, s2, illum_a="d65", illum_b="d65", noise=3):
    a = _render_patch(rng, spec_to_srgb(s1, illum_a), noise=noise)
    b = _render_patch(rng, spec_to_srgb(s2, illum_b), noise=noise)
    return a + b

def _cd_spectra_bytes(s1, s2):
    out = bytearray()
    for s in (s1, s2):
        for v in s:
            out += struct.pack("<H", int(round(max(0.0, min(1.0, v)) * 65535)))
    return bytes(out)

def gen_colordisc(rng, family, idx):
    """family 0=normal, 1=COL-1 metamer, 2=COL-2 illuminant-drift, 3=COL-3 gray-trap.
    Returns (f, g, truth)."""
    N = _nullspace()
    if family == 0:
        sub = idx % 3
        if sub == 0:  # SAME
            s1 = _draw_spec(rng)
            if rng.coin(0.5):
                s2 = list(s1)
            else:  # deltaE in [0.4, 1.6]
                for _ in range(200):
                    s2 = [min(0.95, max(0.05, v + rng.frange(-0.03, 0.03))) for v in s1]
                    de = delta_e_2000(rgb_to_lab(*spec_to_srgb(s1)),
                                      rgb_to_lab(*spec_to_srgb(s2)))
                    if 0.4 <= de <= 1.6:
                        break
                else:
                    raise RuntimeError("CD normal-SAME search failed idx=%d" % idx)
            truth = "SAME"
        else:  # DIFFERENT graded
            band = [(10, 28), (4, 10), (2.4, 4)][sub - 1]
            for _ in range(500):
                s1 = _draw_spec(rng); s2 = _draw_spec(rng)
                de = delta_e_2000(rgb_to_lab(*spec_to_srgb(s1)),
                                  rgb_to_lab(*spec_to_srgb(s2)))
                if band[0] <= de < band[1] and spec_l1_u16(s1, s2) >= 40000:
                    break
            else:
                raise RuntimeError("CD normal-DIFF search failed idx=%d" % idx)
            truth = "DIFFERENT"
        f = _cd_pair(rng, s1, s2)
        g = _cd_pair(rng, s1, s2) + _cd_spectra_bytes(s1, s2)
        return f, g, truth
    if family == 1:  # COL-1 metamer: truth DIFFERENT, RGB Euclid < 15
        for _ in range(2000):
            s1 = _draw_spec(rng)
            z = np.array([rng.frange(-0.35, 0.35) for _ in range(3)])
            s2 = np.clip(np.array(s1) + _NN @ z, 0.05, 0.95)
            # small RGB-visible nudge to land deltaE in [2.6, 8]
            s2 = np.clip(s2 + np.array([rng.frange(-0.02, 0.02) for _ in range(6)]),
                         0.05, 0.95)
            s2 = list(s2)
            de = delta_e_2000(rgb_to_lab(*spec_to_srgb(s1)),
                              rgb_to_lab(*spec_to_srgb(s2)))
            re_ = rgb_euclid(spec_to_srgb(s1), spec_to_srgb(s2))
            if 2.6 <= de <= 8.0 and re_ < 15 and spec_l1_u16(s1, s2) >= 40000:
                break
        else:
            raise RuntimeError("COL-1 search failed idx=%d" % idx)
        f = _cd_pair(rng, s1, s2)
        g = _cd_pair(rng, s1, s2) + _cd_spectra_bytes(s1, s2)
        return f, g, "DIFFERENT"
    if family == 2:  # COL-2 illuminant-drift: truth SAME, B under warm
        s1 = _draw_spec(rng); s2 = list(s1)
        f = _cd_pair(rng, s1, s2, illum_a="d65", illum_b="warm")
        g = _cd_pair(rng, s1, s2) + _cd_spectra_bytes(s1, s2)
        return f, g, "SAME"
    # COL-3 gray-trap: truth DIFFERENT (dE 2.6..5), RGB Euclid < 25, near-gray.
    # Nullspace move gives the spectral separation (challenge path); a +-0.12
    # RGB-visible nudge lands deltaE in the band (pilot: 15% hit rate).
    for _ in range(3000):
        g0 = rng.frange(0.35, 0.65)
        s1 = [min(0.95, max(0.05, g0 + rng.frange(-0.04, 0.04))) for _ in range(6)]
        z = np.array([rng.frange(-0.3, 0.3) for _ in range(3)])
        s2 = np.clip(np.array(s1) + _NN @ z, 0.05, 0.95)
        s2 = np.clip(s2 + np.array([rng.frange(-0.12, 0.12) for _ in range(6)]),
                     0.05, 0.95)
        s2 = list(s2)
        c1, c2 = spec_to_srgb(s1), spec_to_srgb(s2)
        de = delta_e_2000(rgb_to_lab(*c1), rgb_to_lab(*c2))
        re_ = rgb_euclid(c1, c2)
        sat = max(max(c1) - min(c1), max(c2) - min(c2))
        if 2.6 <= de <= 5.0 and re_ < 25 and sat < 40 and spec_l1_u16(s1, s2) >= 40000:
            break
    else:
        raise RuntimeError("COL-3 search failed idx=%d" % idx)
    f = _cd_pair(rng, s1, s2)
    g = _cd_pair(rng, s1, s2) + _cd_spectra_bytes(s1, s2)
    return f, g, "DIFFERENT"

# ============================================================ t1 colorconst
# F = viewA(48x48 RGB) + viewB(48x48 RGB) = 13824 B ; G = same under d65
CC_F = 48 * 48 * 3 * 2
CC_G = CC_F

def _cc_view(rng, crop, illum, exposure=1.0, noise=2):
    v = apply_illum_np(crop, ILLUM[illum], exposure)
    if noise:
        n = _sm_integers(rng, -noise, noise + 1, v.shape)
        v = np.clip(v.astype(np.int16) + n, 0, 255).astype(np.uint8)
    return v.tobytes()

def gen_colorconst(rng, family, idx):
    """family 0=normal, 1=CCN-1 extreme, 2=CCN-2 mixed-illuminant."""
    if family == 0:
        same = rng.coin(0.5)
        c1, _ = photo_crop(rng, 48, 48)
        if same:
            c2 = c1.copy()
            i1, i2 = rng.pick(["d65", "warm", "cool"]), rng.pick(["d65", "warm", "cool"])
            truth = "SAME_SURFACE"
        else:
            c2, _ = photo_crop(rng, 48, 48)
            i1, i2 = rng.pick(["d65", "warm", "cool"]), rng.pick(["d65", "warm", "cool"])
            truth = "DIFFERENT"
        f = _cc_view(rng, c1, i1) + _cc_view(rng, c2, i2)
        g = _cc_view(rng, c1, "d65") + _cc_view(rng, c2, "d65")
        return f, g, truth
    if family == 1:  # extreme illuminants + 0.55 exposure
        same = rng.coin(0.5)
        c1, _ = photo_crop(rng, 48, 48)
        c2 = c1.copy() if same else photo_crop(rng, 48, 48)[0]
        i1 = rng.pick(["xblue", "xred"]); i2 = rng.pick(["xblue", "xred"])
        truth = "SAME_SURFACE" if same else "DIFFERENT"
        f = _cc_view(rng, c1, i1, 0.55) + _cc_view(rng, c2, i2, 0.55)
        g = _cc_view(rng, c1, "d65") + _cc_view(rng, c2, "d65")
        return f, g, truth
    # CCN-2 mixed-illuminant: same crop, viewB = left warm / right cool
    c1, _ = photo_crop(rng, 48, 48)
    vw = apply_illum_np(c1, ILLUM["warm"]); vc = apply_illum_np(c1, ILLUM["cool"])
    mixed = np.concatenate([vw[:, :24], vc[:, 24:]], axis=1)
    n = _sm_integers(rng, -2, 3, mixed.shape)
    mixed = np.clip(mixed.astype(np.int16) + n, 0, 255).astype(np.uint8)
    f = _cc_view(rng, c1, "d65") + mixed.tobytes()
    g = _cc_view(rng, c1, "d65") + _cc_view(rng, c1, "d65")
    return f, g, "SAME_SURFACE"

# ============================================================ t2 shapetrans
# F = 96x96 u8 grayscale = 9216 B ; G = 48x48 u8 quadrant crop = 2304 B
SH_F = 96 * 96
SH_G = 48 * 48
SH_CLASSES = ["CIRCLE", "TRIANGLE", "SQUARE"]

def _raster(cls, cx, cy, scale, rot, size, fg):
    n = size * 3
    ys, xs = np.mgrid[0:n, 0:n].astype(np.float64) / 3.0
    dx = xs - cx; dy = ys - cy
    ca, sa = math.cos(rot), math.sin(rot)
    lx = dx * ca + dy * sa; ly = -dx * sa + dy * ca
    if cls == 0:  # circle
        inside = lx * lx + ly * ly <= (scale / 2) ** 2
    elif cls == 2:  # square
        inside = (np.abs(lx) <= scale / 2) & (np.abs(ly) <= scale / 2)
    else:  # triangle: equilateral, pointing up, centroid at origin
        R = scale / 2
        v = [(R * math.cos(a), R * math.sin(a))
             for a in (-math.pi / 2, math.pi / 6, 5 * math.pi / 6)]
        (x0, y0), (x1, y1), (x2, y2) = v
        d = (y1 - y2) * (x0 - x2) + (x2 - x1) * (y0 - y2)
        l0 = ((y1 - y2) * (lx - x2) + (x2 - x1) * (ly - y2)) / d
        l1 = ((y2 - y0) * (lx - x2) + (x0 - x2) * (ly - y2)) / d
        l2 = 1 - l0 - l1
        inside = (l0 >= 0) & (l1 >= 0) & (l2 >= 0)
    cov = inside.reshape(size, 3, size, 3).mean(axis=(1, 3))
    return cov

def _shape_frame(rng, cls, cx, cy, scale, rot, size, bg, fg, noise=4):
    cov = _raster(cls, cx, cy, scale, rot, size, fg)
    img = bg * (1 - cov) + fg * cov
    if noise:
        img += _sm_integers(rng, -noise, noise + 1, img.shape)
    return np.clip(img, 0, 255).astype(np.uint8)

def gen_shapetrans(rng, family, idx):
    """family 0=normal, 1=SHP-1 occlusion-bar, 2=SHP-2 distractor-blob,
    3=SHP-3 low-contrast+clutter."""
    if family == 0:
        cls = idx % 3
    else:
        cls = rng.irange(0, 3)
    scale = rng.frange(30, 44)
    rot = rng.frange(0, 2 * math.pi)
    cx = 48 + rng.frange(-14, 14); cy = 48 + rng.frange(-14, 14)
    truth = SH_CLASSES[cls]
    ph, _ = photo_crop(rng, 96, 96)
    bg = (np.asarray(Image.fromarray(ph).convert("L"), dtype=np.float64)) * 0.45
    fg = 235
    if family == 3:
        bg = np.asarray(Image.fromarray(ph).convert("L"), dtype=np.float64)  # full clutter
        fg = 150
    img = _shape_frame(rng, cls, cx, cy, scale, rot, 96, bg, fg)
    if family == 1:  # occlusion bar: solid dark bar across the shape
        by = int(cy + rng.frange(-8, 8))
        img[max(0, by - 7):min(96, by + 7), :] = 20
    if family == 2:  # distractor blob: second same-color filled circle
        for _ in range(20):
            bx = rng.frange(16, 80); by = rng.frange(16, 80)
            if math.hypot(bx - cx, by - cy) > scale:
                break
        cov = _raster(0, bx, by, scale * rng.frange(0.7, 1.0), 0.0, 96, fg)
        img = np.clip(bg * (1 - cov) + fg * cov, 0, 255)
        # redraw target shape on top (target drawn over distractor where overlapping)
        img = _shape_frame(rng, cls, cx, cy, scale, rot, 96, img.astype(np.float64), fg, noise=0)
        img = np.clip(img.astype(np.int16) + _sm_integers(rng, -4, 5, img.shape),
                      0, 255).astype(np.uint8)
    f = img.tobytes()
    # G: clean controlled re-render of the target class, centered to fit fully
    # in the 48x48 span (the F's quadrant position could clip a radius-44
    # shape at the span edge, breaking the ray-profile challenge).
    gbg = np.full((48, 48), 100.0)
    gimg = _shape_frame(rng, cls, 24, 24, 16, rot, 48, gbg, 235, noise=2)
    g = gimg.tobytes()
    assert len(f) == SH_F and len(g) == SH_G
    return f, g, truth

# ============================================================ audio helpers
RATE = 16000
AU_N = 32000  # 2.0 s
AU_F = AU_N   # F bytes = 64000 (int16)
AU_G = AU_N

def _ramps(n, ms=20):
    r = int(RATE * ms / 1000)
    w = np.ones(n)
    t = np.arange(r) / r
    w[:r] = 0.5 - 0.5 * np.cos(math.pi * t)
    w[-r:] = 0.5 - 0.5 * np.cos(math.pi * t[::-1])
    return w

def synth_tone(freq, dur, harms, rng, glide_to=None):
    """harms: list of (k, amp, phase). glide_to: end freq for linear glide."""
    n = int(RATE * dur)
    t = np.arange(n) / RATE
    if glide_to is None:
        ph = 2 * math.pi * freq * t
    else:
        fi = freq + (glide_to - freq) * t / dur
        ph = 2 * math.pi * np.cumsum(fi) / RATE
    sig = np.zeros(n)
    for k, a, pha in harms:
        sig += a * np.sin(k * ph + pha)
    sig *= _ramps(n)
    return sig

def _norm_harms(harms, peak=12000):
    sig = None
    return harms

def tone_bytes(sig):
    sig = sig / max(1e-9, np.abs(sig).max()) * 12000
    return np.clip(sig, -32768, 32767).astype("<i2").tobytes()

# ============================================================ t3 pitchdisc
# F = toneA(0-0.9s) + gap + toneB(1.0-1.9s) [+ pad] = 32000 int16
# G = clean re-render of the same two tones at TRUE endpoint freqs
PTC_GAP0, PTC_GAP1 = 14400, 16000
PTC_B0, PTC_B1 = 16000, 30400

def _ptc_render(fa, fb, harms_a, harms_b, rng, glide_a=None, glide_b=None):
    buf = np.zeros(AU_N)
    buf[0:PTC_GAP0] = synth_tone(fa, 0.9, harms_a, rng,
                                 glide_to=glide_a[1] if glide_a else None)
    bdur = (PTC_B1 - PTC_B0) / RATE
    buf[PTC_B0:PTC_B1] = synth_tone(fb, bdur, harms_b, rng,
                                    glide_to=glide_b[1] if glide_b else None)
    return buf

def _ptc_harms(rng, distractor=False):
    if distractor:
        # 0.6x 2nd + 0.3x 3rd, adversarial phase pi/2 on the 2nd (extra
        # zero-crossings verified in pilot; phase is not frozen by the spec)
        return [(1, 1.0, rng.uniform() * 6.283),
                (2, 0.6, math.pi / 2), (3, 0.3, rng.uniform() * 6.283)]
    return [(1, 1.0, rng.uniform() * 6.283),
            (2, 0.3, rng.uniform() * 6.283),
            (3, 0.15, rng.uniform() * 6.283)]

def _ptc_truth(fa, fb):
    r = (fb - fa) / fa
    if abs(r) < 0.005: return "SAME"
    return "HIGHER" if r > 0 else "LOWER"

def gen_pitchdisc(rng, family, idx):
    """family 0=normal, 1=PTC-1 near-threshold, 2=PTC-2 glide, 3=PTC-3 harmonic."""
    fa = rng.frange(220, 660)
    if family == 0:
        sub = idx % 3
        if sub == 0:
            fb = fa * (1 + rng.frange(-0.0045, 0.0045))
        elif sub == 1:
            fb = fa * (1 + rng.frange(0.0055, 0.25))
        else:
            fb = fa * (1 - rng.frange(0.0055, 0.25))
        fbuf = _ptc_render(fa, fb, _ptc_harms(rng), _ptc_harms(rng), rng)
        gbuf = _ptc_render(fa, fb, _ptc_harms(rng), _ptc_harms(rng), rng)
        return tone_bytes(fbuf), tone_bytes(gbuf), _ptc_truth(fa, fb)
    if family == 1:  # near-threshold straddle
        sub = rng.irange(0, 3)
        if sub == 0:
            fb = fa * (1 + rng.pick([-1, 1]) * rng.frange(0.0015, 0.0045))
        elif sub == 1:
            fb = fa * (1 + rng.frange(0.0055, 0.0085))
        else:
            fb = fa * (1 - rng.frange(0.0055, 0.0085))
        fbuf = _ptc_render(fa, fb, _ptc_harms(rng), _ptc_harms(rng), rng)
        gbuf = _ptc_render(fa, fb, _ptc_harms(rng), _ptc_harms(rng), rng)
        return tone_bytes(fbuf), tone_bytes(gbuf), _ptc_truth(fa, fb)
    if family == 2:  # glide-through-threshold; truth from endpoint ratio
        which = rng.irange(0, 2)  # which tone glides
        delta = rng.frange(0.015, 0.03) * rng.pick([-1, 1])
        if which == 0:
            fbuf = _ptc_render(fa, fa, _ptc_harms(rng), _ptc_harms(rng), rng,
                               glide_a=(fa, fa * (1 + delta)))
            gbuf = _ptc_render(fa * (1 + delta), fa, _ptc_harms(rng),
                               _ptc_harms(rng), rng)
            truth = _ptc_truth(fa * (1 + delta), fa)
        else:
            fbuf = _ptc_render(fa, fa, _ptc_harms(rng), _ptc_harms(rng), rng,
                               glide_b=(fa, fa * (1 + delta)))
            gbuf = _ptc_render(fa, fa * (1 + delta), _ptc_harms(rng),
                               _ptc_harms(rng), rng)
            truth = _ptc_truth(fa, fa * (1 + delta))
        return tone_bytes(fbuf), tone_bytes(gbuf), truth
    # PTC-3 harmonic distractor on tone B
    sub = rng.irange(0, 3)
    if sub == 0:
        fb = fa * (1 + rng.frange(-0.004, 0.004))
    elif sub == 1:
        fb = fa * (1 + rng.frange(0.01, 0.2))
    else:
        fb = fa * (1 - rng.frange(0.01, 0.2))
    fbuf = _ptc_render(fa, fb, _ptc_harms(rng), _ptc_harms(rng, distractor=True), rng)
    gbuf = _ptc_render(fa, fb, _ptc_harms(rng), _ptc_harms(rng), rng)
    return tone_bytes(fbuf), tone_bytes(gbuf), _ptc_truth(fa, fb)

# ============================================================ t4 timbredisc
# F = 2.0 s tone at 440 Hz with harmonic profile ; G = clean re-render
TMB_CLASSES = ["PURE", "BRIGHT", "DARK", "RICH"]
# formation bins on spectral centroid (Hz); calibrated to the profiles below
TMB_BINS = [520, 950, 1550]  # <520 PURE, <950 DARK, <1550 RICH, else BRIGHT
# challenge/truth templates in POWER ratios (p2, p3) = ((a2/a1)^2, (a3/a1)^2),
# x1000. Power ratios match what the Zag Goertzel challenge measures
# (Goertzel power is proportional to amplitude squared), so truth is defined
# in the challenge's own units: DARK (0.28^2, 0.08^2), RICH (0.8^2, 0.62^2),
# BRIGHT ((0.7/0.5)^2, (0.8/0.5)^2).
TMB_TMPL = {
    "PURE": (0, 0),
    "DARK": (78, 6),
    "RICH": (640, 384),
    "BRIGHT": (1960, 2560),
}
TMB_PROFILES = {
    "PURE": {1: 1.0},
    "DARK": {1: 1.0, 2: 0.28, 3: 0.08},
    "RICH": {1: 1.0, 2: 0.80, 3: 0.62, 4: 0.48, 5: 0.36, 6: 0.27},
    "BRIGHT": {1: 0.5, 2: 0.7, 3: 0.8, 4: 0.9, 5: 1.0, 6: 0.9, 7: 0.8, 8: 0.7},
}

def _tmb_centroid(profile):
    num = sum(k * a for k, a in profile.items())
    den = sum(profile.values())
    return 440.0 * num / den

def _tmb_template_class(profile):
    a1 = profile.get(1, 1e-9)
    p2 = int(round((profile.get(2, 0.0) / a1) ** 2 * 1000))
    p3 = int(round((profile.get(3, 0.0) / a1) ** 2 * 1000))
    best, bd = None, 1e18
    for c, (t2, t3) in TMB_TMPL.items():
        d = (p2 - t2) ** 2 + (p3 - t3) ** 2
        if d < bd: bd, best = d, c
    return best

def _tmb_bin(cent):
    if cent < TMB_BINS[0]: return "PURE"
    if cent < TMB_BINS[1]: return "DARK"
    if cent < TMB_BINS[2]: return "RICH"
    return "BRIGHT"

def _tmb_harms(profile, rng):
    return [(k, a, rng.uniform() * 6.283) for k, a in sorted(profile.items())]

def _tmb_render(profile, rng):
    return synth_tone(440.0, 2.0, _tmb_harms(profile, rng), rng)

def _interp_profile(pa, pb, lam):
    ks = set(pa) | set(pb)
    return {k: (1 - lam) * pa.get(k, 0.0) + lam * pb.get(k, 0.0) for k in ks}

def gen_timbredisc(rng, family, idx):
    """family 0=normal, 1=TMB-1 boundary-straddle, 2=TMB-2 harmonic-boost,
    3=TMB-3 distractor."""
    if family == 0:
        cls = TMB_CLASSES[idx % 4]
        profile = dict(TMB_PROFILES[cls])
        truth = cls
    elif family == 1:  # boundary straddle: centroid within +-8% of a bin boundary,
        # truth = template class on the far side of the boundary
        b = rng.pick(TMB_BINS)
        pairs = {520: ("PURE", "DARK"), 950: ("DARK", "RICH"), 1550: ("RICH", "BRIGHT")}
        ca, cb = pairs[b]
        for _ in range(300):
            lam = rng.frange(0.05, 0.95)
            profile = _interp_profile(TMB_PROFILES[ca], TMB_PROFILES[cb], lam)
            cent = _tmb_centroid(profile)
            tcls = _tmb_template_class(profile)
            bcls = _tmb_bin(cent)
            if abs(cent - b) / b <= 0.08 and tcls != bcls:
                break
        else:
            raise RuntimeError("TMB-1 search failed")
        truth = tcls
    elif family == 2:  # harmonic-boost x1.15 on 2nd: template flips, bin stays
        # (power-ratio template space; base just DARK of the DARK/RICH boundary)
        for _ in range(300):
            a2 = rng.frange(0.58, 0.66); a3 = rng.frange(0.32, 0.38)
            profile = {1: 1.0, 2: a2, 3: a3}
            boosted = {1: 1.0, 2: a2 * 1.15, 3: a3}
            if (_tmb_template_class(profile) == "DARK"
                    and _tmb_template_class(boosted) == "RICH"
                    and _tmb_bin(_tmb_centroid(profile)) == "DARK"
                    and _tmb_bin(_tmb_centroid(boosted)) == "DARK"):
                break
        else:
            raise RuntimeError("TMB-2 search failed")
        profile = boosted
        truth = "RICH"
    else:  # TMB-3 distractors
        sub = rng.irange(0, 4)
        if sub == 0:  # BRIGHT weak-fundamental
            profile = {1: 0.2, 2: 0.7, 3: 0.8, 4: 0.9, 5: 1.0, 6: 0.9, 7: 0.8, 8: 0.7}
        elif sub == 1:  # DARK extra-3rd (+0.85 -> template flips to RICH)
            profile = {1: 1.0, 2: 0.28, 3: 0.85}
        elif sub == 2:  # RICH pushed-bright (k>=4 x3.0 -> centroid crosses 1550)
            profile = {1: 1.0, 2: 0.8, 3: 0.62, 4: 1.44, 5: 1.08, 6: 0.81}
        else:  # near-PURE faint-2nd (0.2)
            profile = {1: 1.0, 2: 0.2}
        truth = _tmb_template_class(profile)
    fbuf = _tmb_render(profile, rng)
    gbuf = _tmb_render(profile, rng)
    return tone_bytes(fbuf), tone_bytes(gbuf), truth

# ============================================================ t5 motiondir
# F = 50 frames 32x32 u8 = 51200 B ; G = 50 frames clean high-contrast
MOT_F = 50 * 32 * 32
MOT_G = MOT_F
MOT_DIRS = ["N", "NE", "E", "SE", "S", "SW", "W", "NW"]
MOT_VEC = {"N": (0, -2), "NE": (2, -2), "E": (2, 0), "SE": (2, 2),
           "S": (0, 2), "SW": (-2, 2), "W": (-2, 0), "NW": (-2, -2),
           "STILL": (0, 0)}

def _mot_region(rng):
    ph = rng.pick(photos())
    ph_h, ph_w = ph.shape[:2]
    x = rng.irange(0, ph_w - 48 + 1); y = rng.irange(0, ph_h - 48 + 1)
    gray = np.asarray(Image.fromarray(ph[y:y + 48, x:x + 48]).convert("L"),
                      dtype=np.float64)
    return gray

def _mot_frames(region, direction, nframes, step_scale=1.0, contrast=1.0,
                rng=None, flicker=None, blob=None):
    """Render nframes of 32x32 from a 48x48 region; window moves per direction
    with wraparound in the 16px slack. flicker=(frac, mdir): frac of frames
    show the misleading-direction offset. blob=(mdir): bright blob moving mdir."""
    dx, dy = MOT_VEC[direction]
    dx, dy = dx * step_scale, dy * step_scale
    mdx, mdy = (MOT_VEC[flicker[1]][0] * step_scale,
                MOT_VEC[flicker[1]][1] * step_scale) if flicker else (0, 0)
    sx = rng.frange(0, 16) if rng else 4.0
    sy = rng.frange(0, 16) if rng else 4.0
    mean = region.mean()
    reg = mean + (region - mean) * contrast
    reg = np.clip(reg, 0, 255)
    frames = []
    bx, by = (rng.frange(0, 32) if rng else 8.0), (rng.frange(0, 32) if rng else 8.0)
    for t in range(nframes):
        if flicker and rng.uniform() < flicker[0]:
            wx = (sx + mdx * t) % 16; wy = (sy + mdy * t) % 16
        else:
            wx = (sx + dx * t) % 16; wy = (sy + dy * t) % 16
        ix, iy = int(wx), int(wy)
        fr = reg[iy:iy + 32, ix:ix + 32].copy()
        if blob is not None:
            bdx, bdy = MOT_VEC[blob]
            px = int((bx + bdx * t) % 32); py = int((by + bdy * t) % 32)
            fr[max(0, py - 4):py + 4, max(0, px - 4):px + 4] = 250
        if rng:
            fr += _sm_integers(rng, -3, 4, fr.shape)
        frames.append(np.clip(fr, 0, 255).astype(np.uint8))
    return frames

def _mot_high_contrast(frames):
    out = []
    for fr in frames:
        f = fr.astype(np.float64)
        lo, hi = f.min(), f.max()
        if hi - lo < 1: out.append(fr); continue
        out.append((((f - lo) / (hi - lo)) * 255).astype(np.uint8))
    return out

def gen_motiondir(rng, family, idx):
    """family 0=normal, 1=MOT-1 reversed, 2=MOT-2 flicker, 3=MOT-3 camouflaged."""
    region = _mot_region(rng)
    if family == 0:
        sub = idx % 9
        direction = "STILL" if sub == 8 else MOT_DIRS[sub]
        F = _mot_frames(region, direction, 50, rng=rng)
        G = _mot_high_contrast(_mot_frames(region, direction, 50, rng=rng))
        truth = direction
    elif family == 1:  # reversed video; truth = true direction
        direction = rng.pick(MOT_DIRS)
        fwd = _mot_frames(region, direction, 100, rng=rng)
        F = fwd[49::-1]  # frames 49..0 : shown motion is reverse(direction)
        G = _mot_high_contrast(_mot_frames(region, direction, 50, rng=rng))
        truth = direction
    elif family == 2:  # flicker + second motion; truth = dominant
        direction = rng.pick(MOT_DIRS)
        mdir = rng.pick([d for d in MOT_DIRS if d != direction])
        F = _mot_frames(region, direction, 50, rng=rng,
                        flicker=(0.30, mdir), blob=mdir)
        G = _mot_high_contrast(_mot_frames(region, direction, 50, rng=rng))
        truth = direction
    else:  # camouflaged: 25% contrast, 1px/frame
        direction = rng.pick(MOT_DIRS)
        F = _mot_frames(region, direction, 50, step_scale=0.5, contrast=0.25, rng=rng)
        G = _mot_high_contrast(_mot_frames(region, direction, 50, rng=rng))
        truth = direction
    f = b"".join(fr.tobytes() for fr in F)
    g = b"".join(fr.tobytes() for fr in G)
    assert len(f) == MOT_F and len(g) == MOT_G
    return f, g, truth

# ============================================================ driver
GEN = {
    0: (gen_colordisc, 1080, [(400, 1), (350, 2), (400, 3)]),
    1: (gen_colorconst, 720, [(340, 1), (340, 2)]),
    2: (gen_shapetrans, 1296, [(400, 1), (450, 2), (300, 3)]),
    3: (gen_pitchdisc, 720, [(350, 1), (400, 2), (400, 3)]),
    4: (gen_timbredisc, 720, [(250, 1), (250, 2), (190, 3)]),
    5: (gen_motiondir, 564, [(350, 1), (350, 2), (295, 3)]),
}
# FROZEN harness adversarial family assignment for the 185 frozen fixtures'
# second presentations: family = FAMS[t][k mod len] (documented approximation;
# the frozen fixtures predate the R2A family taxonomy).
FROZEN_ADV_COUNTS = {0: 30, 1: 20, 2: 45, 3: 30, 4: 30, 5: 30}

def emit(task, split, index, family, f, g, truth, ledger_f, manifest):
    tidx = TIDX[task]
    fid = "r2n_%s_%d" % (task, index) if split == "r2n" else \
          "r2a_%s_%d" % (task, index) if split == "r2a" else \
          "r2a2_%s_%d" % (task, index)
    sub = {"r2n": "r2n", "r2a": "r2a", "r2a2": "r2a2"}[split]
    path = os.path.join(OUTDIR, sub, fid + ".r2fx")
    write_r2fx(path, tidx, index, family, f, g)
    write_truth(path + ".truth", truth)
    h = hashlib.sha256(open(path, "rb").read()).hexdigest()
    rel = "./%s/%s.r2fx" % (sub, fid)
    manifest.append("%s  %s\n" % (h, rel))
    ledger_f.write(json.dumps({"id": fid, "task": task, "split": split,
                               "family": family, "truth": truth,
                               "sha256": h}) + "\n")
    return h

def main():
    only = sys.argv[1:]  # optional: task names to generate
    os.makedirs(OUTDIR, exist_ok=True)
    for s in ("r2n", "r2a", "r2a2"):
        os.makedirs(os.path.join(OUTDIR, s), exist_ok=True)
    manifest_path = os.path.join(OUTDIR, "MANIFEST.sha256")
    manifest = []
    if os.path.exists(manifest_path):
        manifest = open(manifest_path).readlines()
    ledger = open(os.path.join(OUTDIR, "gen_ledger.jsonl"),
                   "a" if manifest else "w")
    have = set(l.split("  ")[1].strip() for l in manifest if "  " in l)
    # also pick up fixture files written by an interrupted run whose manifest
    # was never flushed
    for sub in ("r2n", "r2a", "r2a2"):
        d = os.path.join(OUTDIR, sub)
        if os.path.isdir(d):
            for fn in os.listdir(d):
                if fn.endswith(".r2fx"):
                    rel = "./%s/%s" % (sub, fn)
                    if rel not in have:
                        h = hashlib.sha256(open(os.path.join(d, fn), "rb").read()).hexdigest()
                        manifest.append("%s  %s\n" % (h, rel))
                        have.add(rel)
    def flush_manifest():
        with open(manifest_path, "w") as mf:
            mf.writelines(sorted(manifest))
        ledger.flush()
    total = 0
    for tidx, task in enumerate(TASKS):
        if only and task not in only:
            continue
        gen, n_norm, adv_fams = GEN[tidx]
        # normal
        for i in range(n_norm):
            rel = "./r2n/r2n_%s_%d.r2fx" % (task, i)
            if rel in have:
                continue
            rng = Rng(stream_seed(MASTER, STREAM_NORMAL + tidx, i))
            f, g, truth = gen(rng, 0, i)
            emit(task, "r2n", i, 0, f, g, truth, ledger, manifest)
            total += 1
        # adversarial
        i = 0
        for count, fam in adv_fams:
            for j in range(count):
                rel = "./r2a/r2a_%s_%d.r2fx" % (task, i)
                if rel in have:
                    i += 1
                    continue
                rng = Rng(stream_seed(MASTER, STREAM_ADV + tidx, i))
                f, g, truth = gen(rng, fam, i)
                emit(task, "r2a", i, fam, f, g, truth, ledger, manifest)
                total += 1
                i += 1
        # second presentations: same (family, index), disjoint stream
        i = 0
        for count, fam in adv_fams:
            for j in range(count):
                rel = "./r2a2/r2a2_%s_%d.r2fx" % (task, i)
                if rel in have:
                    i += 1
                    continue
                rng = Rng(stream_seed(MASTER, STREAM_SECOND + tidx, i))
                f, g, truth = gen(rng, fam, i)
                emit(task, "r2a2", i, fam, f, g, truth, ledger, manifest)
                total += 1
                i += 1
        # second presentations for the frozen harness adversarial fixtures
        fams = [f for _, f in adv_fams]
        for k in range(FROZEN_ADV_COUNTS[tidx]):
            fam = fams[k % len(fams)]
            idx2 = 100000 + k
            rel = "./r2a2/r2a2_%s_%d.r2fx" % (task, idx2)
            if rel in have:
                continue
            rng = Rng(stream_seed(MASTER, STREAM_SECOND + tidx, idx2))
            f, g, truth = gen(rng, fam, idx2)
            emit(task, "r2a2", idx2, fam, f, g, truth, ledger, manifest)
            total += 1
        print("task %s done (+%d new)" % (task, total), flush=True)
        flush_manifest()
    ledger.close()
    flush_manifest()
    print("TOTAL new fixtures: %d" % total)
    print("MANIFEST lines: %d" % len(manifest))

if __name__ == "__main__":
    main()
