#!/usr/bin/env python3
"""R2A frozen fixture suite generator — PAM ROUND 2 (prereg instrument).

Implements R2_FIXTURE_SET.md (frozen 2026-09-22) exactly:
  MASTER seed = 20260923 (new; round-1 harness used 20260921).
  Streams: normal-ext = 400+taskidx, adversarial = 500+taskidx, taskidx:
    colordisc=0, colorconst=1, shapetrans=2, pitchdisc=3, timbredisc=4, motiondir=5.
  Per-fixture seed = splitmix64(splitmix64(MASTER ^ stream*0x9E3779B97F4A7C15)
                                ^ index*0xBF58476D1CE4E5B9)
    — identical construction to harness/gen.py stream_seed().
  Truth files <id>.truth alongside each fixture ("truth=<VALUE>").
  MANIFEST.sha256 covers every generated byte.

Suite composition (per-task generated counts are authoritative; they sum to
5100 normal + 5630 adversarial, NOT to the doc's 4260/4815 — the doc's
aggregate arithmetic is inconsistent with its own per-task Distribution and
family-table rows, which cross-check exactly: adversarial family counts sum
to the per-task distribution numbers. Documented in GENERATOR_NOTES.md):

  Normal (generated, "same distributions as the frozen primary set"):
    colordisc 1080, colorconst 720, shapetrans 1296,
    pitchdisc 720, timbredisc 720, motiondir 564            (= 5100)
    + 740 frozen harness fixtures (370 primary + 370 noise) = 5840 normal.
  Adversarial (generated, family table):
    colordisc 1150 (COL-1 400, COL-2 350, COL-3 400),
    colorconst 680 (CCN-1 340, CCN-2 340),
    shapetrans 1150 (SHP-1 400, SHP-2 450, SHP-3 300),
    pitchdisc 1150 (PTC-1 350, PTC-2 400, PTC-3 400),
    timbredisc 690 (TMB-1 250, TMB-2 250, TMB-3 190),
    motiondir 995 (MOT-1 350, MOT-2 350, MOT-3 295)          (= 5630)
    + 185 frozen harness adversarial = 5815 adversarial.
  TOTAL POOL = 11655 trials.

Determinism: every random draw from the per-fixture splitmix64 Rng. numpy is
used ONLY for mechanical pixel/sample loops (no randomness inside numpy);
all decisions come from Rng. Regeneration with the same code + photo pool
yields byte-identical fixtures.

Resolution notes (frozen-doc ambiguities, all documented):
  R-MOT-1: "reversed-video — constant-velocity motion played backward; truth =
    true direction". Operationalized: truth = direction of motion in the
    PRESENTED (reversed) clip, i.e. opposite of the pre-reversal direction
    (STILL stays STILL). Rationale: "truth from the true stimulus, not the
    corrupted appearance" — the fixture IS the stimulus; with wrap-around
    translation the reversed clip is otherwise indistinguishable from a
    forward clip of the opposite direction, so the pre-reversal reading would
    make the family unwinnable-by-construction rather than a predictor test.
  R-TMB-2: truth = the pre-boost class (the x1.15 2nd-harmonic boost is the
    corruption; truth from the true underlying stimulus class).
  R-TMB-1: truth = nearest canonical class centroid (post-synthesis class).
  R-COL-1: "distinct chromaticity" enforced as dE2000 >= 2.5 AND RGB
    Euclidean < 15; truth = DIFFERENT.
  R-COL-3 (CARRYOVER): per the R2A table, all 400 truth=DIFFERENT with
    dE2000 in [2.6,5.0] and mean-RGB Euclidean < 25.
  R-CCN-2: both panels same photo, each panel half warm / half cool;
    truth = SAME_SURFACE (340 trials).
  R-PTC-2: tone1 static f0; tone2 linear glide crossing the 0.5% JND
    mid-tone; truth from endpoint ratio vs the 0.5% boundary.
"""
import math, os, struct, sys, hashlib

import numpy as np

MASTER_SEED = 20260923
TASKIDX = {"colordisc": 0, "colorconst": 1, "shapetrans": 2,
           "pitchdisc": 3, "timbredisc": 4, "motiondir": 5}
TASKS = ["colordisc", "colorconst", "shapetrans",
         "pitchdisc", "timbredisc", "motiondir"]
EXTS = {"colordisc": ".img", "colorconst": ".img", "shapetrans": ".img",
        "pitchdisc": ".pcm", "timbredisc": ".pcm", "motiondir": ".vid"}

# ---------------------------------------------------------------- PRNG
MASK64 = (1 << 64) - 1

def splitmix64(state):
    state = (state + 0x9E3779B97F4A7C15) & MASK64
    z = state
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK64
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK64
    z = z ^ (z >> 31)
    return z

class Rng:
    def __init__(self, seed):
        self.s = seed & MASK64
    def u64(self):
        self.s = (self.s + 0x9E3779B97F4A7C15) & MASK64
        z = self.s
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK64
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK64
        return z ^ (z >> 31)
    def uniform(self):
        return (self.u64() >> 11) * (1.0 / (1 << 53))
    def range(self, lo, hi):
        return lo + (hi - lo) * self.uniform()
    def int(self, n):
        return self.u64() % n
    def pick(self, seq):
        return seq[self.u64() % len(seq)]

def stream_seed(master, stream, index):
    h = splitmix64((master ^ (stream * 0x9E3779B97F4A7C15)) & MASK64)
    return splitmix64((h ^ (index * 0xBF58476D1CE4E5B9)) & MASK64)

# ------------------------------------------------------- color math
def srgb_to_linear(c):
    c = np.asarray(c, dtype=np.float64) / 255.0
    return np.where(c <= 0.04045, c / 12.92, ((c + 0.055) / 1.055) ** 2.4)

def linear_to_srgb(c):
    c = np.clip(np.asarray(c, dtype=np.float64), 0.0, 1.0)
    v = np.where(c <= 0.0031308, 12.92 * c, 1.055 * (c ** (1.0 / 2.4)) - 0.055)
    return np.clip(np.round(v * 255), 0, 255).astype(np.uint8)

XYZ_M = np.array(((0.4124564, 0.3575761, 0.1804375),
                  (0.2126729, 0.7151522, 0.0721750),
                  (0.0193339, 0.1191920, 0.9503041)))
XYZ_MI = np.array((( 3.2404542, -1.5371385, -0.4985314),
                   (-0.9692660,  1.8760108,  0.0415560),
                   ( 0.0556434, -0.2040259,  1.0572252)))
BRAD = np.array(((0.8951, 0.2664, -0.1614),
                 (-0.7502, 1.7135, 0.0367),
                 (0.0389, -0.0685, 1.0296)))
BRAD_I = np.array(((0.9869929, -0.1470543, 0.1599627),
                   (0.4323053, 0.5183603, 0.0492912),
                   (-0.0085287, 0.0400428, 0.9684867)))

def rgb_to_xyz_np(rgb):
    lin = srgb_to_linear(rgb)
    return lin @ XYZ_M.T

def apply_illuminant_np(rgb, illum_xyz):
    """Vectorized von-Kries (Bradford CAT). rgb: (N,3) uint8 -> (N,3) uint8."""
    xyz = rgb_to_xyz_np(rgb.astype(np.float64))
    src = np.array((0.95047, 1.0, 1.08883))
    dst = np.array(illum_xyz)
    lms_s = xyz @ BRAD.T
    lms_wsrc = src @ BRAD.T
    lms_wdst = dst @ BRAD.T
    lms = lms_s * (lms_wdst / lms_wsrc)
    xa = lms @ BRAD_I.T
    lin = xa @ XYZ_MI.T
    return linear_to_srgb(lin)

# scalar versions for the dE search (single colors)
def _srgb_lin_1(c):
    c /= 255.0
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

def _lin_srgb_1(c):
    c = max(0.0, min(1.0, c))
    v = 12.92 * c if c <= 0.0031308 else 1.055 * (c ** (1.0 / 2.4)) - 0.055
    return int(round(max(0.0, min(1.0, v)) * 255))

def rgb_to_lab_1(r, g, b):
    rl, gl, bl = _srgb_lin_1(r), _srgb_lin_1(g), _srgb_lin_1(b)
    x = 0.4124564*rl + 0.3575761*gl + 0.1804375*bl
    y = 0.2126729*rl + 0.7151522*gl + 0.0721750*bl
    z = 0.0193339*rl + 0.1191920*gl + 0.9503041*bl
    xn, yn, zn = 0.95047, 1.0, 1.08883
    def f(t):
        return t ** (1/3) if t > 0.008856 else 7.787 * t + 16/116
    fx, fy, fz = f(x/xn), f(y/yn), f(z/zn)
    return (116*fy - 16, 500*(fx - fy), 200*(fy - fz))

def delta_e_2000(lab1, lab2):
    L1, a1, b1 = lab1; L2, a2, b2 = lab2
    kL = kC = kH = 1.0
    C1 = math.hypot(a1, b1); C2 = math.hypot(a2, b2)
    Cb = (C1 + C2) / 2
    G = 0.5 * (1 - math.sqrt(Cb**7 / (Cb**7 + 25**7)))
    ap1 = (1 + G) * a1; ap2 = (1 + G) * a2
    Cp1 = math.hypot(ap1, b1); Cp2 = math.hypot(ap2, b2)
    def hp(ap, b):
        if ap == 0 and b == 0: return 0.0
        h = math.degrees(math.atan2(b, ap))
        return h + 360 if h < 0 else h
    hp1, hp2 = hp(ap1, b1), hp(ap2, b2)
    dL = L2 - L1; dC = Cp2 - Cp1
    if Cp1 * Cp2 == 0:
        dh = 0.0
    else:
        dh = hp2 - hp1
        if dh > 180: dh -= 360
        elif dh < -180: dh += 360
    dH = 2 * math.sqrt(Cp1 * Cp2) * math.sin(math.radians(dh / 2))
    Lbp = (L1 + L2) / 2; Cbp = (Cp1 + Cp2) / 2
    if Cp1 * Cp2 == 0:
        hbp = hp1 + hp2
    else:
        hbp = (hp1 + hp2) / 2 if abs(hp1 - hp2) <= 180 else (hp1 + hp2 + 360) / 2 if hp1 + hp2 < 360 else (hp1 + hp2 - 360) / 2
    T = (1 - 0.17*math.cos(math.radians(hbp-30)) + 0.24*math.cos(math.radians(2*hbp))
         + 0.32*math.cos(math.radians(3*hbp+6)) - 0.20*math.cos(math.radians(4*hbp-63)))
    dRo = 30 * math.exp(-((hbp - 275) / 25) ** 2)
    Rc = 2 * math.sqrt(Cbp**7 / (Cbp**7 + 25**7))
    Sl = 1 + 0.015 * (Lbp - 50) ** 2 / math.sqrt(20 + (Lbp - 50) ** 2)
    Sc = 1 + 0.045 * Cbp
    Sh = 1 + 0.015 * Cbp * T
    Rt = -math.sin(math.radians(2 * dRo)) * Rc
    return math.sqrt((dL/(kL*Sl))**2 + (dC/(kC*Sc))**2 + (dH/(kH*Sh))**2 + Rt*(dC/(kC*Sc))*(dH/(kH*Sh)))

def _lab_to_srgb_1(L, a, b):
    xn, yn, zn = 0.95047, 1.0, 1.08883
    fy = (L + 16) / 116.0
    fx = fy + a / 500.0
    fz = fy - b / 200.0
    def fi(t):
        return t**3 if t**3 > 0.008856 else (t - 16/116) / 7.787
    x, y, z = xn*fi(fx), yn*fi(fy), zn*fi(fz)
    rl = 3.2404542*x - 1.5371385*y - 0.4985314*z
    gl = -0.9692660*x + 1.8760108*y + 0.0415560*z
    bl = 0.0556434*x - 0.2040259*y + 1.0572252*z
    return (_lin_srgb_1(rl), _lin_srgb_1(gl), _lin_srgb_1(bl))

def _rand_color(rng):
    return (rng.int(256), rng.int(256), rng.int(256))

def _color_at_distance(rng, base, target_de, tol=0.15, tries=400):
    L0, a0, b0 = rgb_to_lab_1(*base)
    best = None
    for _ in range(tries):
        ang = rng.uniform() * 2 * math.pi
        step = target_de * rng.range(0.35, 0.7)
        L1 = max(0.0, min(100.0, L0 + step * math.cos(ang) * rng.range(0.4, 1.0)))
        C = step * math.sin(ang)
        a1 = a0 + C * math.cos(rng.uniform() * 2 * math.pi)
        b1 = b0 + C * math.sin(rng.uniform() * 2 * math.pi)
        rgb = _lab_to_srgb_1(L1, a1, b1)
        de = delta_e_2000((L0, a0, b0), rgb_to_lab_1(*rgb))
        if abs(de - target_de) / max(target_de, 1e-9) < tol:
            return rgb
        if best is None or abs(de - target_de) < abs(best[0] - target_de):
            best = (de, rgb)
    return best[1]

def _rgb_euclid(c1, c2):
    return math.sqrt(sum((a-b)**2 for a, b in zip(c1, c2)))

ILLUM = {
    "d65":   (0.95047, 1.00000, 1.08883),
    "warm":  (1.09850, 1.00000, 0.35585),
    "cool":  (0.99180, 1.00000, 0.67390),
    "xblue": (0.62000, 0.85000, 1.75000),
    "xred":  (1.70000, 0.90000, 0.45000),
    "drift": (1.15000, 1.00000, 0.75000),   # R2A COL-2 mid-item drift point
}

# ------------------------------------------------------- binary writers
def write_img(path, w, h, px):
    """px: (h*w,3) uint8 array."""
    with open(path, "wb") as f:
        f.write(struct.pack("<II", w, h))
        f.write(np.ascontiguousarray(px, dtype=np.uint8).tobytes())

def write_pcm(path, rate, samples):
    """samples: int16 array."""
    s = np.ascontiguousarray(samples, dtype=np.int16)
    with open(path, "wb") as f:
        f.write(struct.pack("<II", rate, len(s)))
        f.write(s.tobytes())

def write_vid(path, w, h, frames):
    """frames: list of (h*w,3) uint8 arrays."""
    with open(path, "wb") as f:
        f.write(struct.pack("<III", len(frames), w, h))
        for fr in frames:
            f.write(np.ascontiguousarray(fr, dtype=np.uint8).tobytes())

def write_truth(path, value):
    with open(path + ".truth", "w") as f:
        f.write("truth=%s\n" % value)

# ------------------------------------------------------- photo pool
PHOTOS_DIR = os.environ.get("R2A_PHOTOS",
    os.path.expanduser("~/workspace/tnn-lab/senses/rebuild/harness/fixtures/_photos"))
_photo_cache = {}

def load_photo(i):
    from PIL import Image
    if i in _photo_cache:
        return _photo_cache[i]
    p = os.path.join(PHOTOS_DIR, "ph%03d.jpg" % i)
    im = Image.open(p).convert("RGB")
    if im.size != (160, 120):
        im = im.resize((160, 120))
    px = np.asarray(im, dtype=np.uint8).reshape(-1, 3)
    _photo_cache[i] = px
    return px

def crop_photo_np(photo, ox, oy, w, h):
    im = photo.reshape(120, 160, 3)
    return im[oy:oy+h, ox:ox+w, :].reshape(-1, 3).copy()

# ------------------------------------------------------- audio synthesis
SR = 16000

def _tone_np(freq, dur, harmonics, amp=0.75):
    """harmonics: list of (multiple, amplitude). 20ms raised-cosine ramps."""
    n = int(SR * dur)
    t = np.arange(n, dtype=np.float64) / SR
    out = np.zeros(n)
    for k, a in harmonics:
        out += a * np.sin(2 * np.pi * freq * k * t)
    ramp = int(SR * 0.02)
    env = np.ones(n)
    r = 0.5 - 0.5 * np.cos(np.pi * np.arange(ramp) / ramp)
    env[:ramp] = r
    env[n-ramp:] = r[::-1]
    out *= env
    peak = np.max(np.abs(out))
    g = (amp / peak) * 32767 if peak > 1e-9 else 0.0
    return np.clip(np.round(out * g), -32768, 32767).astype(np.int16)

def _glide_tone_np(f_start, f_end, dur, harmonics, amp=0.75):
    """Linear frequency glide via phase accumulation."""
    n = int(SR * dur)
    t = np.arange(n, dtype=np.float64) / SR
    f = f_start + (f_end - f_start) * (t / dur)
    phase = 2 * np.pi * np.cumsum(f) / SR
    out = np.zeros(n)
    for k, a in harmonics:
        out += a * np.sin(k * phase)
    ramp = int(SR * 0.02)
    env = np.ones(n)
    r = 0.5 - 0.5 * np.cos(np.pi * np.arange(ramp) / ramp)
    env[:ramp] = r
    env[n-ramp:] = r[::-1]
    out *= env
    peak = np.max(np.abs(out))
    g = (amp / peak) * 32767 if peak > 1e-9 else 0.0
    return np.clip(np.round(out * g), -32768, 32767).astype(np.int16)

RICH_H = [(1, 1.0), (2, 0.30), (3, 0.15)]
# canonical timbre profiles + centroids (Hz @440) for TMB truth
TIMBRES = {
    "PURE":   [(1, 1.0)],
    "BRIGHT": [(1, 1.0), (2, 0.80), (3, 0.65), (4, 0.55), (5, 0.45), (6, 0.38), (7, 0.32), (8, 0.28)],
    "DARK":   [(1, 1.0), (2, 0.40), (3, 0.10), (4, 0.03)],
    "RICH":   [(1, 1.0), (2, 0.55), (3, 0.40), (4, 0.28), (5, 0.20), (6, 0.14)],
}
def _centroid(harm, f0=440.0):
    num = sum(k * f0 * a for k, a in harm)
    den = sum(a for _, a in harm)
    return num / den if den > 0 else 0.0

CENTROIDS = {c: _centroid(h) for c, h in TIMBRES.items()}

def _nearest_class(cent):
    return min(CENTROIDS, key=lambda c: abs(CENTROIDS[c] - cent))

def _exp_profile_for_centroid(target, f0=440.0):
    """Harmonic profile (exponential rolloff 1..8) with spectral centroid
    == target Hz. Solved by bisection on the rolloff rate (deterministic)."""
    def cent_of(s):
        harm = [(k, math.exp(-(k-1)*s)) for k in range(1, 9)]
        return _centroid(harm, f0)
    lo, hi = -0.5, 4.0   # s=-0.5 -> rising harmonics (bright); s=4 -> ~pure
    for _ in range(60):
        mid = (lo + hi) / 2
        if cent_of(mid) < target:
            hi = mid
        else:
            lo = mid
    s = (lo + hi) / 2
    return [(k, math.exp(-(k-1)*s)) for k in range(1, 9)]

# ------------------------------------------------------- shape raster
def _raster_shape(kind, W, cx, cy, scale, rot, fg, bg_px, occl_bar):
    """Vectorized 3x3-supersampled rasterization. bg_px: (W*W,3) uint8."""
    SS = 3
    ys, xs = np.mgrid[0:W, 0:W]
    sub = (np.arange(SS) + 0.5) / SS - 0.5   # subpixel offsets
    # coverage accumulator
    cov = np.zeros((W, W))
    cosr, sinr = math.cos(rot), math.sin(rot)
    for sy in sub:
        for sx in sub:
            fx = xs + sx - cx
            fy = ys + sy - cy
            ux = (fx * cosr + fy * sinr) / scale
            uy = (-fx * sinr + fy * cosr) / scale
            if kind == "circle":
                hit = (ux*ux + uy*uy) <= 0.25
            elif kind == "square":
                hit = (np.abs(ux) <= 0.5) & (np.abs(uy) <= 0.5)
            else:  # triangle
                R = 0.62
                angs = np.array([math.pi/2 + k*2*math.pi/3 for k in range(3)])
                vx = R * np.cos(angs); vy = -R * np.sin(angs)
                def sgn(px, py, ax, ay, bx, by):
                    return (px-bx)*(ay-by) - (ax-bx)*(py-by)
                d1 = sgn(ux, uy, vx[0], vy[0], vx[1], vy[1])
                d2 = sgn(ux, uy, vx[1], vy[1], vx[2], vy[2])
                d3 = sgn(ux, uy, vx[2], vy[2], vx[0], vy[0])
                neg = (d1 < 0) | (d2 < 0) | (d3 < 0)
                pos = (d1 > 0) | (d2 > 0) | (d3 > 0)
                hit = ~(neg & pos)
            cov += hit.astype(np.float64)
    a = (cov / (SS*SS))[..., None]
    fg_a = np.asarray(fg, dtype=np.float64)
    bg_a = bg_px.reshape(W, W, 3).astype(np.float64)
    px = fg_a * a + bg_a * (1 - a)
    if occl_bar:
        bar = np.zeros((W, W, 3))
        bar[30:45, :, :] = bg_a[30:45, :, :] * 0.9 + 40
        m = np.zeros((W, W, 1)); m[30:45, :, :] = 1.0
        px = px * (1 - m) + bar * m
    return np.clip(np.round(px), 0, 255).astype(np.uint8).reshape(-1, 3)

# ------------------------------------------------------- NORMAL generators
# index i: 0-based per task; seed stream = 400+taskidx.
def _patch_pair_img(c1, c2):
    px = np.zeros((64, 128, 3), dtype=np.uint8)
    px[:, :64, :] = c1
    px[:, 64:, :] = c2
    return px.reshape(-1, 3)

def r2n_t1(i, outdir):
    rng = Rng(stream_seed(MASTER_SEED, 400 + 0, i))
    base = _rand_color(rng)
    if i < 360:  # SAME: 180 identical, 180 near (dE 0.4-1.6)
        c2 = base if i < 180 else _color_at_distance(rng, base, rng.range(0.4, 1.6))
        truth = "SAME"
    else:  # DIFFERENT graded: 252 easy [10,28], 234 med [4,10), 234 hard [2.4,4)
        k = i - 360
        if k < 252: de = rng.range(10, 28)
        elif k < 486: de = rng.range(4, 10)
        else: de = rng.range(2.4, 4.0)
        c2 = _color_at_distance(rng, base, de)
        truth = "DIFFERENT"
    p = os.path.join(outdir, "r2n_colordisc_%04d.img" % i)
    write_img(p, 128, 64, _patch_pair_img(base, c2))
    write_truth(p, truth)
    return truth

def _two_panel(p1, p2):
    px = np.zeros((64, 128, 3), dtype=np.uint8)
    px[:, :64, :] = p1.reshape(64, 64, 3)
    px[:, 64:, :] = p2.reshape(64, 64, 3)
    return px.reshape(-1, 3)

def r2n_t2(i, outdir):
    rng = Rng(stream_seed(MASTER_SEED, 400 + 1, i))
    illums = ["d65", "warm", "cool"]
    if i < 360:  # SAME_SURFACE
        ph = rng.int(170)
        crop = crop_photo_np(load_photo(ph), rng.int(160-64), rng.int(120-64), 64, 64)
        i1, i2 = rng.int(3), rng.int(3)
        while i2 == i1: i2 = rng.int(3)
        p1 = apply_illuminant_np(crop, ILLUM[illums[i1]])
        p2 = apply_illuminant_np(crop, ILLUM[illums[i2]])
        truth = "SAME_SURFACE"
    else:
        ph1, ph2 = rng.int(170), rng.int(170)
        while ph2 == ph1: ph2 = rng.int(170)
        c1 = crop_photo_np(load_photo(ph1), rng.int(160-64), rng.int(120-64), 64, 64)
        c2 = crop_photo_np(load_photo(ph2), rng.int(160-64), rng.int(120-64), 64, 64)
        p1 = apply_illuminant_np(c1, ILLUM[rng.pick(illums)])
        p2 = apply_illuminant_np(c2, ILLUM[rng.pick(illums)])
        truth = "DIFFERENT"
    p = os.path.join(outdir, "r2n_colorconst_%04d.img" % i)
    write_img(p, 128, 64, _two_panel(p1, p2))
    write_truth(p, truth)
    return truth

KINDS = ["circle", "triangle", "square"]
KIND_TRUTH = {"circle": "CIRCLE", "triangle": "TRIANGLE", "square": "SQUARE"}

def r2n_t3(i, outdir):
    rng = Rng(stream_seed(MASTER_SEED, 400 + 2, i))
    kind = KINDS[i % 3]
    W = 96
    crop = crop_photo_np(load_photo(rng.int(170)), rng.int(160-W), rng.int(120-W), W, W)
    bg = np.clip(np.round(crop.astype(np.float64) * 0.45), 0, 255).astype(np.uint8)
    rot = rng.uniform() * 2 * math.pi
    scale = rng.range(30, 44)
    cx = W/2 + rng.range(-14, 14); cy = W/2 + rng.range(-14, 14)
    fg = (235, 235, 235)
    px = _raster_shape(kind, W, cx, cy, scale, rot, fg, bg, False)
    p = os.path.join(outdir, "r2n_shapetrans_%04d.img" % i)
    write_img(p, W, W, px)
    truth = KIND_TRUTH[kind]
    write_truth(p, truth)
    return truth

def r2n_t4(i, outdir):
    rng = Rng(stream_seed(MASTER_SEED, 400 + 3, i))
    f0 = rng.range(220, 660)
    cls = (i // 1) % 3          # 240 SAME / 240 HIGHER / 240 LOWER
    band = (i // 3) % 4
    if cls == 0:
        f1 = f0; truth = "SAME"
    else:
        rel = [rng.range(0.10, 0.25), rng.range(0.02, 0.05),
               rng.range(0.005, 0.008), rng.range(0.10, 0.25)][band]
        f1 = f0 * (1 + rel) if cls == 1 else f0 * (1 - rel)
        truth = "HIGHER" if cls == 1 else "LOWER"
    gap = np.zeros(int(SR * 0.08), dtype=np.int16)
    samples = np.concatenate([_tone_np(f0, 0.4, RICH_H), gap, _tone_np(f1, 0.4, RICH_H)])
    p = os.path.join(outdir, "r2n_pitchdisc_%04d.pcm" % i)
    write_pcm(p, SR, samples)
    write_truth(p, truth)
    return truth

def r2n_t5(i, outdir):
    rng = Rng(stream_seed(MASTER_SEED, 400 + 4, i))
    cls = ["PURE", "BRIGHT", "DARK", "RICH"][i % 4]
    samples = _tone_np(440.0, 0.8, TIMBRES[cls])
    p = os.path.join(outdir, "r2n_timbredisc_%04d.pcm" % i)
    write_pcm(p, SR, samples)
    write_truth(p, cls)
    return cls

DIRS = {"N": (0,-1), "NE": (1,-1), "E": (1,0), "SE": (1,1),
        "S": (0,1), "SW": (-1,1), "W": (-1,0), "NW": (-1,-1)}
DIR_ORDER = sorted(DIRS)

def _motion_frames(rng, photo, vec, step, contrast, ox, oy, W=64, nframes=8):
    im = photo.reshape(120, 160, 3).astype(np.float64)
    mean = im.reshape(-1, 3).mean(axis=0)
    imc = mean + (im - mean) * contrast
    imc = np.clip(np.round(imc), 0, 255).astype(np.uint8)
    frames = []
    yy, xx = np.mgrid[0:W, 0:W]
    for f in range(nframes):
        dx = int(round(-vec[0] * step * f)); dy = int(round(-vec[1] * step * f))
        sx = (ox + xx + dx) % 160
        sy = (oy + yy + dy) % 120
        frames.append(imc[sy, sx].reshape(-1, 3).copy())
    return frames

def r2n_t6(i, outdir):
    rng = Rng(stream_seed(MASTER_SEED, 400 + 5, i))
    if i < 36:
        truth, vec = "STILL", (0, 0)
    else:
        truth = DIR_ORDER[(i - 36) % 8]; vec = DIRS[truth]
    photo = load_photo(rng.int(170))
    frames = _motion_frames(rng, photo, vec, 2, 1.0, rng.int(40), rng.int(24))
    p = os.path.join(outdir, "r2n_motiondir_%04d.vid" % i)
    write_vid(p, 64, 64, frames)
    write_truth(p, truth)
    return truth

# ------------------------------------------------------- ADVERSARIAL generators
# index i: 0-based per task across families in table order; stream 500+taskidx.

# ---- T1 colordisc (1150): COL-1 metamer 400 / COL-2 drift 350 / COL-3 gray 400
def r2a_t1_col1(rng, i, outdir):
    # metamer-pairs: truth=DIFFERENT, distinct chromaticity (dE>=2.5),
    # rendered to RGB Euclidean < 15.
    base = _rand_color(rng)
    lab0 = rgb_to_lab_1(*base)
    c2 = None
    for _ in range(600):
        cand = _rand_color(rng)
        d_rgb = _rgb_euclid(base, cand)
        if 3.0 <= d_rgb < 15.0 and delta_e_2000(lab0, rgb_to_lab_1(*cand)) >= 2.5:
            c2 = cand
            break
    if c2 is None:
        c2 = _color_at_distance(rng, base, 3.0)  # fallback (still DIFFERENT)
    p = os.path.join(outdir, "r2a_colordisc_%04d.img" % i)
    write_img(p, 128, 64, _patch_pair_img(base, c2))
    write_truth(p, "DIFFERENT")
    return "DIFFERENT"

def r2a_t1_col2(rng, i, outdir):
    # illuminant-drift: SAME surface, illuminant shifts mid-item
    # (panel1 d65, panel2 drifted). Fools static color-balance.
    ph = rng.int(170)
    crop = crop_photo_np(load_photo(ph), rng.int(160-64), rng.int(120-64), 64, 64)
    p1 = apply_illuminant_np(crop, ILLUM["d65"])
    p2 = apply_illuminant_np(crop, ILLUM["drift"])
    p = os.path.join(outdir, "r2a_colordisc_%04d.img" % i)
    write_img(p, 128, 64, _two_panel(p1, p2))
    write_truth(p, "SAME")
    return "SAME"

def r2a_t1_col3(rng, i, outdir):
    # gray-trap CARRYOVER: truth=DIFFERENT, dE2000 in [2.6,5.0],
    # mean-RGB Euclidean < 25. Grayish bases so RGB stays small.
    base = (rng.int(60)+90, rng.int(60)+90, rng.int(60)+90)
    c2 = _color_at_distance(rng, base, 3.5)
    for _ in range(8):
        cand = _color_at_distance(rng, base, rng.range(2.6, 5.0), tol=0.10)
        if _rgb_euclid(base, cand) < 25.0:
            c2 = cand
            break
    p = os.path.join(outdir, "r2a_colordisc_%04d.img" % i)
    write_img(p, 128, 64, _patch_pair_img(base, c2))
    write_truth(p, "DIFFERENT")
    return "DIFFERENT"

def r2a_t1(i, outdir):
    if i < 400:
        rng = Rng(stream_seed(MASTER_SEED, 500 + 0, i)); return r2a_t1_col1(rng, i, outdir)
    if i < 750:
        rng = Rng(stream_seed(MASTER_SEED, 500 + 0, i)); return r2a_t1_col2(rng, i, outdir)
    rng = Rng(stream_seed(MASTER_SEED, 500 + 0, i)); return r2a_t1_col3(rng, i, outdir)

# ---- T2 colorconst (680): CCN-1 extreme 340 / CCN-2 mixed 340
def r2a_t2_ccn1(rng, i, outdir):
    illums = ["xblue", "xred", "warm"]
    if i < 170:
        ph = rng.int(170)
        crop = crop_photo_np(load_photo(ph), rng.int(160-64), rng.int(120-64), 64, 64)
        i1, i2 = rng.int(3), rng.int(3)
        while i2 == i1: i2 = rng.int(3)
        p1 = apply_illuminant_np((crop.astype(np.float64)*0.55).astype(np.uint8), ILLUM[illums[i1]])
        p2 = apply_illuminant_np((crop.astype(np.float64)*0.55).astype(np.uint8), ILLUM[illums[i2]])
        truth = "SAME_SURFACE"
    else:
        ph1, ph2 = rng.int(170), rng.int(170)
        while ph2 == ph1: ph2 = rng.int(170)
        c1 = crop_photo_np(load_photo(ph1), rng.int(160-64), rng.int(120-64), 64, 64)
        c2 = crop_photo_np(load_photo(ph2), rng.int(160-64), rng.int(120-64), 64, 64)
        p1 = apply_illuminant_np((c1.astype(np.float64)*0.55).astype(np.uint8), ILLUM[rng.pick(illums)])
        p2 = apply_illuminant_np((c2.astype(np.float64)*0.55).astype(np.uint8), ILLUM[rng.pick(illums)])
        truth = "DIFFERENT"
    p = os.path.join(outdir, "r2a_colorconst_%04d.img" % i)
    write_img(p, 128, 64, _two_panel(p1, p2))
    write_truth(p, truth)
    return truth

def r2a_t2_ccn2(rng, i, outdir):
    # mixed-illuminant: same photo; each panel half warm / half cool.
    ph = rng.int(170)
    crop = crop_photo_np(load_photo(ph), rng.int(160-64), rng.int(120-64), 64, 64).reshape(64, 64, 3)
    warm = apply_illuminant_np(crop.reshape(-1,3), ILLUM["warm"]).reshape(64, 64, 3)
    cool = apply_illuminant_np(crop.reshape(-1,3), ILLUM["cool"]).reshape(64, 64, 3)
    panel = np.zeros((64, 64, 3), dtype=np.uint8)
    panel[:, :32, :] = warm[:, :32, :]
    panel[:, 32:, :] = cool[:, 32:, :]
    p = os.path.join(outdir, "r2a_colorconst_%04d.img" % i)
    write_img(p, 128, 64, _two_panel(panel.reshape(-1,3), panel.reshape(-1,3)))
    write_truth(p, "SAME_SURFACE")
    return "SAME_SURFACE"

def r2a_t2(i, outdir):
    rng = Rng(stream_seed(MASTER_SEED, 500 + 1, i))
    if i < 340: return r2a_t2_ccn1(rng, i, outdir)
    return r2a_t2_ccn2(rng, i, outdir)

# ---- T3 shapetrans (1150): SHP-1 occl 400 / SHP-2 distractor 450 / SHP-3 lowcontrast 300
def _t3_base(rng, kind, low_contrast, clutter):
    W = 96
    crop = crop_photo_np(load_photo(rng.int(170)), rng.int(160-W), rng.int(120-W), W, W)
    dim = 1.0 if clutter else 0.45
    bg = np.clip(np.round(crop.astype(np.float64) * dim), 0, 255).astype(np.uint8)
    rot = rng.uniform() * 2 * math.pi
    scale = rng.range(16, 26) if (low_contrast or clutter) else rng.range(30, 44)
    if not (low_contrast or clutter):
        scale = rng.range(30, 44)
    cx = W/2 + rng.range(-14, 14); cy = W/2 + rng.range(-14, 14)
    if low_contrast:
        fg = (int(rng.range(120,175)), int(rng.range(120,175)), int(rng.range(120,175)))
    else:
        fg = (235, 235, 235)
    return W, cx, cy, scale, rot, fg, bg

def r2a_t3(i, outdir):
    rng = Rng(stream_seed(MASTER_SEED, 500 + 2, i))
    W = 96
    if i < 400:  # SHP-1 occlusion-bar CARRYOVER
        kind = KINDS[rng.int(3)]
        W, cx, cy, scale, rot, fg, bg = _t3_base(rng, kind, False, False)
        px = _raster_shape(kind, W, cx, cy, scale, rot, fg, bg, True)
        truth = KIND_TRUTH[kind]
    elif i < 850:  # SHP-2 distractor-blob
        kind = KINDS[rng.int(3)]
        W, cx, cy, scale, rot, fg, bg = _t3_base(rng, kind, False, False)
        px = _raster_shape(kind, W, cx, cy, scale, rot, fg, bg, False).reshape(W, W, 3)
        # distractor: same-color filled circle, ~55% target scale, non-overlapping
        br = scale * 0.55 * 0.5
        ang = rng.uniform() * 2 * math.pi
        dist = scale * 0.5 + br + rng.range(6, 18)
        bx = cx + dist * math.cos(ang); by = cy + dist * math.sin(ang)
        bx = min(max(bx, br+2), W-br-2); by = min(max(by, br+2), W-br-2)
        yy, xx = np.mgrid[0:W, 0:W]
        m = ((xx-bx)**2 + (yy-by)**2) <= br*br
        px[m] = fg
        px = px.reshape(-1, 3)
        truth = KIND_TRUTH[kind]
    else:  # SHP-3 low-contrast gray + full clutter
        kind = KINDS[rng.int(3)]
        W, cx, cy, scale, rot, fg, bg = _t3_base(rng, kind, True, True)
        px = _raster_shape(kind, W, cx, cy, scale, rot, fg, bg, False)
        truth = KIND_TRUTH[kind]
    p = os.path.join(outdir, "r2a_shapetrans_%04d.img" % i)
    write_img(p, W, W, px)
    write_truth(p, truth)
    return truth

# ---- T4 pitchdisc (1150): PTC-1 near 350 / PTC-2 glide 400 / PTC-3 harmdist 400
def r2a_t4(i, outdir):
    rng = Rng(stream_seed(MASTER_SEED, 500 + 3, i))
    f0 = rng.range(220, 660)
    gap = np.zeros(int(SR * 0.08), dtype=np.int16)
    if i < 350:  # PTC-1 near-threshold CARRYOVER
        r = rng.uniform()
        if r < 0.4:
            f1 = f0 * (1 + rng.range(0.001, 0.0045)); truth = "SAME"
        elif r < 0.7:
            f1 = f0 * (1 + rng.range(0.0055, 0.009)); truth = "HIGHER"
        else:
            f1 = f0 * (1 - rng.range(0.0055, 0.009)); truth = "LOWER"
        t2 = _tone_np(f1, 0.4, RICH_H)
    elif i < 750:  # PTC-2 glide-through-threshold; truth from endpoint ratio
        sub = (i - 350) % 3
        if sub == 0: g0, g1 = 0.997, 1.003
        elif sub == 1: g0, g1 = 1.003, 0.997
        else: g0, g1 = 0.9985, 1.0015
        ratio = g1 / g0
        if abs(ratio - 1) < 0.005: truth = "SAME"
        else: truth = "HIGHER" if ratio > 1 else "LOWER"
        t2 = _glide_tone_np(f0*g0, f0*g1, 0.4, RICH_H)
    else:  # PTC-3 harmonic-distractor CARRYOVER: tone B 0.6x 2nd + 0.3x 3rd
        cls = (i - 750) % 3
        if cls == 0: f1 = f0; truth = "SAME"
        elif cls == 1: f1 = f0 * 1.02; truth = "HIGHER"
        else: f1 = f0 * 0.98; truth = "LOWER"
        t2 = _tone_np(f1, 0.4, [(1, 1.0), (2, 0.6), (3, 0.3)])
    samples = np.concatenate([_tone_np(f0, 0.4, RICH_H), gap, t2])
    p = os.path.join(outdir, "r2a_pitchdisc_%04d.pcm" % i)
    write_pcm(p, SR, samples)
    write_truth(p, truth)
    return truth

# ---- T5 timbredisc (690): TMB-1 boundary 250 / TMB-2 boost 250 / TMB-3 distract 190
def r2a_t5(i, outdir):
    rng = Rng(stream_seed(MASTER_SEED, 500 + 4, i))
    if i < 250:  # TMB-1 boundary-straddling: centroid within +-10% of 1075/1400/3000
        b = [1075, 1400, 3000][i % 3]
        target = b * rng.range(0.90, 1.10)
        harm = _exp_profile_for_centroid(target)
        truth = _nearest_class(_centroid(harm))
    elif i < 500:  # TMB-2 harmonic-boost x1.15 on 2nd; truth = pre-boost class
        cls = ["DARK", "RICH", "PURE"][(i - 250) % 3]
        harm = [(k, (a*1.15 if k == 2 else a)) for k, a in TIMBRES[cls]]
        truth = cls
    else:  # TMB-3 distractor CARRYOVER
        r = rng.uniform()
        if r < 0.25:
            harm = [(1, 0.5), (2, 0.9), (3, 0.8), (4, 0.7), (5, 0.6), (6, 0.5)]; truth = "BRIGHT"
        elif r < 0.5:
            harm = [(1, 1.0), (2, 0.45), (3, 0.35), (4, 0.08)]; truth = "DARK"
        elif r < 0.75:
            harm = [(1, 1.0), (2, 0.7), (3, 0.6), (4, 0.5), (5, 0.4), (6, 0.3)]; truth = "RICH"
        else:
            harm = [(1, 1.0), (2, 0.06)]; truth = "PURE"
    samples = _tone_np(440.0, 0.8, harm)
    p = os.path.join(outdir, "r2a_timbredisc_%04d.pcm" % i)
    write_pcm(p, SR, samples)
    write_truth(p, truth)
    return truth

# ---- T6 motiondir (995): MOT-1 reversed 350 / MOT-2 flicker 350 / MOT-3 camo 295
def r2a_t6(i, outdir):
    rng = Rng(stream_seed(MASTER_SEED, 500 + 5, i))
    if i < 350:  # MOT-1 reversed-video; truth = presented direction
        gen_dir = rng.pick(DIR_ORDER + ["STILL"])
        photo = load_photo(rng.int(170))
        frames = _motion_frames(rng, photo, DIRS.get(gen_dir, (0,0)), 2, 1.0,
                                rng.int(40), rng.int(24))
        frames = frames[::-1]
        if gen_dir == "STILL":
            truth = "STILL"
        else:
            # presented motion is opposite of generated
            gx, gy = DIRS[gen_dir]
            truth = next(d for d, v in DIRS.items() if v == (-gx, -gy))
    elif i < 700:  # MOT-2 flicker/two-motion; truth = dominant direction
        truth = rng.pick(DIR_ORDER); vec = DIRS[truth]
        d2 = rng.pick([d for d in DIR_ORDER if d != truth]); vec2 = DIRS[d2]
        photo = load_photo(rng.int(170)); photo2 = load_photo(rng.int(170))
        f1 = _motion_frames(rng, photo, vec, 2, 1.0, rng.int(40), rng.int(24))
        f2 = _motion_frames(rng, photo2, vec2, 2, 1.0, rng.int(40), rng.int(24))
        frames = []
        for f in range(8):
            w2 = 0.60 if (f + i) % 3 == 0 else 0.30  # 30%-misleading flicker
            a = f1[f].reshape(64,64,3).astype(np.float64)
            b = f2[f].reshape(64,64,3).astype(np.float64)
            frames.append(np.clip(np.round(a*(1-w2) + b*w2), 0, 255).astype(np.uint8).reshape(-1,3))
    else:  # MOT-3 camouflaged CARRYOVER
        truth = rng.pick(DIR_ORDER + ["STILL"]); vec = DIRS.get(truth, (0,0))
        photo = load_photo(rng.int(170))
        frames = _motion_frames(rng, photo, vec, 1, 0.25, rng.int(40), rng.int(24))
    p = os.path.join(outdir, "r2a_motiondir_%04d.vid" % i)
    write_vid(p, 64, 64, frames)
    write_truth(p, truth)
    return truth

# ------------------------------------------------------- main
NORMAL_COUNTS = {"colordisc": 1080, "colorconst": 720, "shapetrans": 1296,
                 "pitchdisc": 720, "timbredisc": 720, "motiondir": 564}
ADV_COUNTS = {"colordisc": 1150, "colorconst": 680, "shapetrans": 1150,
              "pitchdisc": 1150, "timbredisc": 690, "motiondir": 995}
NORMAL_FN = {"colordisc": r2n_t1, "colorconst": r2n_t2, "shapetrans": r2n_t3,
             "pitchdisc": r2n_t4, "timbredisc": r2n_t5, "motiondir": r2n_t6}
ADV_FN = {"colordisc": r2a_t1, "colorconst": r2a_t2, "shapetrans": r2a_t3,
          "pitchdisc": r2a_t4, "timbredisc": r2a_t5, "motiondir": r2a_t6}

def sha_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for ch in iter(lambda: f.read(1 << 20), b""):
            h.update(ch)
    return h.hexdigest()

def main():
    root = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "fixtures")
    only = sys.argv[2] if len(sys.argv) > 2 else None
    manifest = []
    dist = {}
    for task in TASKS:
        if only and task != only:
            continue
        for variant, counts, fns in (("normal", NORMAL_COUNTS, NORMAL_FN),
                                     ("adversarial", ADV_COUNTS, ADV_FN)):
            d = os.path.join(root, variant, task)
            os.makedirs(d, exist_ok=True)
            n = counts[task]
            truths = {}
            for i in range(n):
                t = fns[task](i, d)
                truths[t] = truths.get(t, 0) + 1
            dist[(task, variant)] = (n, truths)
            print("%s/%s: %d %s" % (task, variant, n, truths), flush=True)
    # manifest over every generated byte (+ truth files)
    for task in TASKS:
        if only and task != only:
            continue
        for variant in ("normal", "adversarial"):
            d = os.path.join(root, variant, task)
            for fn in sorted(os.listdir(d)):
                fp = os.path.join(d, fn)
                rel = os.path.relpath(fp, root)
                manifest.append((sha_file(fp), rel))
    man_path = os.path.join(root, "MANIFEST.sha256")
    with open(man_path, "w") as f:
        for sha, rel in manifest:
            f.write("%s  %s\n" % (sha, rel))
    total = sum(n for (n, _) in dist.values())
    print("TOTAL generated: %d  (+740 frozen normal +185 frozen adversarial = %d pool)"
          % (total, total + 925), flush=True)
    print("MANIFEST: %s (%d entries)" % (man_path, len(manifest)), flush=True)

if __name__ == "__main__":
    main()
