#!/usr/bin/env python3
"""Generate zag/tables.zag: integer LUTs for the Fork B renderer.

Deterministic (no RNG). Byte-identical output required:
  python3 gen_tables.py > ../zag/tables.zag && cmp with committed file.
"""
import math

print("// tables.zag — generated by gen_tables.py. Do not hand-edit.")
print("// Integer LUTs for the Fork B generative renderer (all LE).")
print()

def emit(name, vals):
    print("fn %s(lut:[]u8) void {" % name)
    for i, v in enumerate(vals):
        print("    t_put16(lut, %d, %d);" % (2 * i, v))
    print("}\n")

# sine: 256 i16, sin(2*pi*i/256) * 32767
emit("sin_init", [int(round(32767 * math.sin(2 * math.pi * i / 256))) for i in range(256)])

# ramp: 320 i16, 20ms raised-cosine 0..1000
emit("ramp_init", [int(round(1000 * (1 - math.cos(math.pi * i / 320)) / 2)) for i in range(320)])

# octant cos/sin x1000 (octant o -> o*45 deg)
C = [1000, 707, 0, -707, -1000, -707, 0, 707]
S = [0, 707, 1000, 707, 0, -707, -1000, -707]
emit("octc_init", C)
emit("octs_init", S)

# triangle vertices: apex-up equilateral, rotated by octant*45deg.
# base verts (x right, y down): (0,-1000), (866,500), (-866,500)
BASE = [(0, -1000), (866, 500), (-866, 500)]
tric, tris = [], []
for o in range(8):
    c, s = C[o], S[o]
    for (x, y) in BASE:
        tric.append(int(round((x * c - y * s) / 1000)))
        tris.append(int(round((x * s + y * c) / 1000)))
emit("tric_init", tric)
emit("tris_init", tris)

# canonical timbre harmonic amplitudes x1000: PURE, BRIGHT, DARK, RICH
TMB = [
    [1000, 0, 0, 0, 0, 0, 0, 0],
    [1000, 800, 650, 550, 450, 380, 320, 280],
    [1000, 400, 100, 30, 0, 0, 0, 0],
    [1000, 550, 400, 280, 200, 140, 0, 0],
]
emit("tmb_init", [a for cls in TMB for a in cls])
