require 'json';require 'digest';require 'open3'
d=File.expand_path(__dir__);parent=File.dirname(d);metadata=JSON.parse(File.read(d+'/NATIVE_SOURCE_CONVERSION.json'));commands=File.readlines(d+'/commands.jsonl').map{|l|JSON.parse(l)}
raise 'qualification incomplete' unless commands.length==25 && commands.all?{|r|r['exit']==r['expected']}
originals=parent+'/sources'
File.open(d+'/diff_commands.jsonl','wx') do |log|
 diffs=metadata['files'].map do |entry|
  name=entry['file'];relative=name.start_with?('R33_NATIVE_') ? name : 'N17/'+name
  argv=['diff','-u',originals+'/'+relative,d+'/sources/'+relative];out,err,st=Open3.capture3(*argv)
  log.puts(JSON.generate({argv:argv,exit:st.exitstatus,expected:'0 identical, 1 source difference',stdout_sha256:Digest::SHA256.hexdigest(out),stderr_sha256:Digest::SHA256.hexdigest(err)}));raise err unless [0,1].include?(st.exitstatus)
  "SOURCE #{relative}\n#{out}"
 end
 File.write(d+'/SOURCE_DIFFS.txt',diffs.join("\n"))
end
prior=JSON.parse(File.read(parent+'/TERMINAL_REVIEW.json'));final=Marshal.load(Marshal.dump(prior));final['supersedes_engineering_constant_gap']=parent+'/TERMINAL_REVIEW.json';final['compatibility_engineering_status']='PASS_REVIEWED_CORRECTION_QUALIFIED';final['r25_execution_gap_closed']='Imported numeric const discrepancy closed for isolated compatibility entrypoint; typed declaration-to-value projection preserves exact constraints. Original diagnostic sources/logs retained unchanged.'
final['presently_closable_overlooked_items']['engineering_subitems']<<'Imported const/native size-binding engineering gap now CLOSED by exact typed numeric compatibility source projection, qualified bounded allocation and missing/malformed/wrong-hash admission. This supersedes diagnostic-only freeze.'
final['presently_closable_overlooked_items']['new_or_refined_gaps'].map!{|s|s.start_with?('Native same-import-graph probe') ? 'RESOLVED for isolated correction: prior probe mismatch/exit1 retained; exact typed numeric projection and corrected size/bounded allocator/admission tests PASS. Original compiler/shim are not mutated and root compiler cause is not asserted.' : s}
final['reviewed_rows'].each do |r|
 next unless ['R26-07','R26-46'].include?(r['id'])
 r['reason']=r['id']=='R26-07' ? 'MISSING_EXACT_INPUTS_AND_RETAINED_GRAPH_SOURCE_BINDING' : 'MISSING_EXACT_LINEAGE_INPUTS_AND_NATIVE_LINEAGE_IMPLEMENTATION'
 r['blocker']=r['id']=='R26-07' ? 'Compatibility imported-constant/allocator gap is closed by reviewed correction. Actual exact R25/R23/speech/noise/canonical inputs remain absent. Complete source-defined digest/extraction and retained embedded-graph projection parity are not yet qualified.' : 'Compatibility constant/allocator gap is closed. Historical 68/68 remains witness-only, exact receipt bytes are absent, complete native lineage suite is absent and actual exact inputs remain absent. A corrected digest runner cannot replace 68 lineage checks.'
 r['native_review_completed']='Import-only shim/source/hash-helper review retained; exact typed numeric compatibility correction passes sizes, bounds, preimage/layout/SHA and missing/malformed/wrong-hash negatives. See corrected qualification commands. No ready1 digest or lineage acceptance claimed.'
 r['closure_requires']=r['id']=='R26-07' ? 'Admit actual exact inputs and normative digest/extraction/retained-object source bindings; independently qualify digest parity. Symbolic constant init is no longer the isolated engineering blocker.' : 'Admit exact selected release inputs/receipt, bind and implement/test complete native lineage suite. Do not convert corrected allocator/digest mechanics or historical receipt into native lineage credit.'
end
final['diagnostic_limits']='Prior failing original-symbolic probe and literal diagnostic remain frozen. Their constant engineering issue is resolved for reviewed isolated compatibility sources by exact typed substitution; constraints preserved and qualified. Exact input/source/spec/lineage blockers remain; no full parity or foreign-runtime claim.'
final['compatibility_correction']={entrypoint_source:d+'/sources/N17/r25_full_digest_exact_parent_v1_runner.zag',entrypoint_binary:d+'/bin/r25_full_digest_exact_parent_v1_runner',conversion_metadata:d+'/NATIVE_SOURCE_CONVERSION.json',source_differences:d+'/SOURCE_DIFFS.txt',declarations:metadata['constants'].length,conversion_rule:'Only numeric declarations/reference tokens mapped to exact typed declared values; inverse source edits reconstruct all input bytes. All other source bytes and import paths are unchanged.',qualification:{commands:commands.length,all_match_expected:true,constant_size_probe_exit:0,bounded_allocator_exit:0,allocator_min:1,allocator_max:33554432,negative_zero_overbound_refuse:true,native_admission_preimage_exit:0,missing_input_exit:66,correct_length_wrong_hash_exit:1,wrong_hash_codes:{numpy:-25301,torch:-25401,digest:-25601,ready:0},source_admission:{missing:66,malformed_wrong_sha:71,empty:68,oversize:68,nonregular:67,symlink:66,invalid_leaf:66,excerpt:71}},boundary:'Engineering compatibility PASS. Lineage/digest acceptance FAIL_CLOSED on actual exact inputs and remaining source/graph/lineage bindings. Token gate keeps original isolated body unchanged: known omission and exact token-loop binding remain reviewed source/spec gaps, not silently guessed or certified.',compiler_pin_unchanged:true,original_diagnostics_retained:true}
token_commands=File.readlines(d+'/token_repair_commands.jsonl').map{|l|JSON.parse(l)};raise unless token_commands.length==21 && token_commands.all?{|r|r['exit']==r['expected']}
final['conservative_gate_correction']=JSON.parse(File.read(d+'/CONSERVATIVE_GATE_CORRECTION.json'))
final['conservative_gate_correction']['qualification_commands']=token_commands
final['conservative_gate_correction']['entrypoint_source']=d+'/sources/N17/repaired_exact_source_gate.zag'
final['conservative_gate_correction']['entrypoint_binary']=d+'/bin/repaired_exact_source_gate'
final['reviewed_rows'].each do |r|
 next unless r['id']>='R26-17'&&r['id']<='R26-22'
 r['reason']='MISSING_WHOLE_SOURCE_AND_EXACT_ORIGINAL_TOKEN_LOOP_BINDING'
 r['code_gap']='Explicit speech_recognition omission CLOSED in additive repaired conservative equivalent; all seven known conservative selectors tested. Exact row20 and original loop/preprocessing selector bindings still unqualified.'
 r['implemented_scan_tokens']=['ultralytics','transformers','torchvision.models','openai','whisper','speech_recognition','librosa.feature.mfcc']
 r['mechanics_review']='Additive repaired conservative gate and shared actual scanner tested: all known selectors detected; original whole-source SHA admission/path/size guards unchanged; missing/malformed and unadmitted token fixtures refuse as expected. No whole original source row credit.'
 r['closure_requires']='Admit complete exact R26 source and exact original verifier token literal/preprocessing/list bindings, then run native full-source per-row checks. Explicit omitted-token engineering defect is closed.'
end
final['presently_closable_overlooked_items']['engineering_subitems'] << 'Known conservative speech_recognition omission CLOSED with strengthened shared scanner and additive repaired exact-SHA gate; all known conservative selectors tested individually.'
final['presently_closable_overlooked_items']['new_or_refined_gaps'].map!{|s|s.start_with?('speech_recognition omitted') ? 'RESOLVED known conservative omission; remaining exact original token-list/literals and preprocessing binding, especially row20, are actual source/spec gaps.' : s}
final['compatibility_correction']['boundary']='Reviewed numeric and conservative admission engineering corrections PASS. Exact inputs/source/spec/lineage acceptance FAIL_CLOSED; no inferred historical preprocessing or row20 credit.'
final['commands']+=token_commands.map{|r|r.merge('log'=>d+'/token_repair_commands.jsonl')}
final['commands']+=commands.map{|r|r.merge('log'=>d+'/commands.jsonl')}
final['custody_hashes'].merge!(Dir.glob(d+'/**/*').select{|p|File.file?(p)&&!File.symlink?(p)&&!p.end_with?('/SHA256SUMS')&&!p.end_with?('/FINAL_TERMINAL_REVIEW.json')&&!p.end_with?('/FINAL_TERMINAL_REVIEW.txt')}.sort.to_h{|p|[p.sub(parent+'/',''),Digest::SHA256.file(p).hexdigest]})
File.write(d+'/FINAL_TERMINAL_REVIEW.json',JSON.pretty_generate(final)+"\n")
text="N17 final independent terminal engineering review COMPLETED — full acceptance receipt FAIL_CLOSED.\nFour integrator-accepted identity/type equivalents preserved; all26 remaining blockers reviewed (5 R27,21 R26), zero additional full-row acceptance.\n\nPRESENT ENGINEERING CORRECTION CLOSED: imported numeric const initialization for isolated R25 compatibility entrypoint.68 exact numeric declarations projected to their declared i32/i64 value; no hash/length/offset/schema/error-code/limit/branch/check weakened. Strings/comments and all other source bytes preserved; reversible per-edit metadata reconstructs every input source byte-for-byte. Relative child imports preserved. Original failing probe and all diagnostic/source snapshots retained. Native conversion metadata NATIVE_SOURCE_CONVERSION.json and exact unified SOURCE_DIFFS.txt include pre/post source SHA. Compiler and original shim unchanged.\n\nCorrected runner and four focused probes freshly built with pinned native znc --target macos-arm64 --no-zagd --no-analyze --no-foreground-cache: builds exit0. Correct required sizes13609471/7028883/482409/499889, constant probe0. Allocator bounds1..33554432 validated (zero/negative/overbound rejected, maximum zeroed endpoint read/write/free), exit0. Preimage order/SHA/overflow/layout and exact-length wrong-hash rejection exit0. Corrected full runner on correct-length wrong-hash fixtures emits NumPy-25301,Torch-25401,digest-25601,READY0 and exit1; missing and wrong-size inputs66; usage64.\n\nWhole-source admission negatives: selftest0, missing66, malformed/wrong SHA71, empty68, oversized68, nonregular67, symlink66, invalid leaf66, excerpt71. All25 focused compatibility commands match expected exits. Fixtures are synthetic negative bytes, never historical execution. Actual exact inputs are absent; no positive digest/lineage READY1 or full parity claimed.\n\nRemaining R25 rows R26-07/-46 are FAIL_CLOSED for actual exact bundle, normative digest/extraction/retained-object bindings and complete native lineage implementation. Prior imported-const/allocator engineering gap is CLOSED for compatibility sources. Explicit R25/R27 manifest/verifier/receipt identity conflicts remain. Original source token gate retained unchanged; additive repaired conservative gate closes speech_recognition omission. Exact original token-loop/literals/preprocessing binding remains unqualified; no specification guesses made. Whole R26 source still absent.\n\nAll other rows retain precise source/input/spec/native implementation/dependency reasons in FINAL_TERMINAL_REVIEW.json. Independent review is COMPLETED, not absent. Prior search/archives evidence frozen and not rerun:166994 paths,283 candidate hashes/0 target admissions,36 inventories (35 nonempty+zero-byte placeholder),16 extracted manifest hashes/0 target matches, two denied RustDesk dirs, no exhaustive absence claim. V91 parity working per integrator/user, no ownership or credit here.\n\n"
final['reviewed_rows'].each{|r|text+="#{r['id']} #{r['name']}: REVIEW_COMPLETED / FAIL_CLOSED / #{r['reason']}\n#{r['blocker']}\nClose with: #{r['closure_requires']}\n\n"}
text+="ADDITIONAL PRESENT ENGINEERING DEFECT CLOSED: conservative speech_recognition omission. Additive repaired_exact_source_gate/shared scanner keeps all seven known conservative selectors and strengthens previous predicate; original contains bytes and whole-file SHA/path/size/read admission guards preserved. All21 repair commands match expected exits: scanner selects each forbidden token; prefix/suffix, truncated/case, clean cases tested; actual outer gate refuses unadmitted token fixtures71 and missing/malformed inputs as before. Conservative raw-byte substring preprocessing is explicit; exact original token-list/literals, row20 grouping/preprocessing still source-unbound. No row20 or exact whole-source absence credit. Metadata CONSERVATIVE_GATE_CORRECTION.json, commands token_repair_commands.jsonl.\n\n"
text+="Final source/binary/conversion/command/output/fixture custody hashes: #{d}/FINAL_TERMINAL_REVIEW.json and SHA256SUMS. Exact command/exits: commands.jsonl; differences: SOURCE_DIFFS.txt and diff_commands.jsonl. Prior diagnostic-only terminal receipt superseded for constant engineering gap; all original diagnostics and four-row review preserved additively.\n\nCanonical/protected before-after checks PASS; no canonical mutation, authority, learning, exposure, promotion, forbidden git or Python/PyTorch/external ML/historical runtime execution. Repository additions only within owned independent root. Carson/integrator: use this final corrected engineering receipt; acceptance remains FAIL_CLOSED on actual missing inputs/spec/lineage dependencies.\n"
File.write(d+'/FINAL_TERMINAL_REVIEW.txt',text)
File.write('/tmp/r33_finish_recovery_20260915_b/n17_terminal_final.txt',text)
File.write(d+'/SHA256SUMS',Dir.glob(d+'/**/*').select{|p|File.file?(p)&&!File.symlink?(p)&&!p.end_with?('/SHA256SUMS')}.sort.map{|p|Digest::SHA256.file(p).hexdigest+'  '+p}.join("\n")+"\n")
puts 'FINAL: engineering compatibility gap CLOSED; review COMPLETED; full acceptance FAIL_CLOSED'
