#!/usr/bin/env python3
"""R2-3 Python mirror of the naive front-ends + reference-gate logic.

INTEGER-ONLY arithmetic throughout. The Zag port (src/gates/ref_gate.zag)
must reproduce these bit-exactly on every fixture. This file is the executable
reference used to (a) tune R2P corruptions in the generator pilot, and
(b) cross-validate the compiled Zag binary on all 1,200 pairs.

Judgment codes (shared with gate_iface.zag):
  colordisc:  0=SAME 1=DIFFERENT
  colorconst: 0=SAME_SURFACE 1=DIFFERENT
  shapetrans: 0=CIRCLE 1=TRIANGLE 2=SQUARE
  pitchdisc:  0=SAME 1=HIGHER 2=LOWER
  timbredisc: 0=PURE 1=BRIGHT 2=DARK 3=RICH
  motiondir:  0=N 1=NE 2=E 3=SE 4=S 5=SW 6=W 7=NW 8=STILL
Decision: 0=ADMIT 1=WITHHOLD
"""
import struct

TASKS = ["colordisc", "colorconst", "shapetrans", "pitchdisc", "timbredisc", "motiondir"]

# ---------------------------------------------------------------- parsers
def parse_frames(buf):
    """u32 nframes, u16 w, u16 h, then nframes*w*h*3 RGB bytes."""
    nframes, w, h = struct.unpack("<IHH", buf[:8])
    fsize = w * h * 3
    frames = [buf[8 + k * fsize: 8 + (k + 1) * fsize] for k in range(nframes)]
    assert len(frames[-1]) == fsize, (len(buf), nframes, w, h)
    return nframes, w, h, frames

def parse_img(buf):
    w, h = struct.unpack("<HH", buf[:4])
    return w, h, buf[4:4 + w * h * 3]

def parse_pcm(buf):
    rate, ns = struct.unpack("<II", buf[:8])
    samps = struct.unpack("<%dh" % ns, buf[8:8 + 2 * ns])
    return rate, ns, samps

# ---------------------------------------------------------------- T1/T2 color
def _mean_rgb(frames, w, h, left):
    s = [0, 0, 0]
    n = 0
    xlo, xhi = (0, w // 2) if left else (w // 2, w)
    for fr in frames:
        for y in range(h):
            base = y * w * 3
            for x in range(xlo, xhi):
                o = base + x * 3
                s[0] += fr[o]; s[1] += fr[o + 1]; s[2] += fr[o + 2]
                n += 1
    return [v // n for v in s]

def nf_colordisc(f):
    nframes, w, h, frames = parse_frames(f)
    ml = _mean_rgb(frames, w, h, True)
    mr = _mean_rgb(frames, w, h, False)
    d2 = (ml[0] - mr[0]) ** 2 + (ml[1] - mr[1]) ** 2 + (ml[2] - mr[2]) ** 2
    return 1 if d2 >= 400 else 0   # DIFFERENT iff squared-Euclidean >= 20^2

def nf_colorconst(f):
    nframes, w, h, frames = parse_frames(f)
    ml = _mean_rgb(frames, w, h, True)
    mr = _mean_rgb(frames, w, h, False)
    d2 = (ml[0] - mr[0]) ** 2 + (ml[1] - mr[1]) ** 2 + (ml[2] - mr[2]) ** 2
    return 1 if d2 >= 900 else 0   # DIFFERENT iff squared-Euclidean >= 30^2

# ---------------------------------------------------------------- T3 shapes
# 12x12 rendered prototypes (canonical pose). P96 for 96x96 inputs (F),
# P48 for 48x48 inputs (G). Generated by cal2.py from the same renderer the
# fixtures use; the Zag gate hardcodes identical bytes.
from t3_protos import (P96_CIRCLE, P96_TRIANGLE, P96_SQUARE,
                       P48_CIRCLE, P48_TRIANGLE, P48_SQUARE)

def _downsample12(px, w, h):
    """Block-average to 12x12, threshold at 128 -> bytes of 0/255."""
    b = w // 12
    out = bytearray(144)
    for gy in range(12):
        for gx in range(12):
            s = 0
            for y in range(gy * b, (gy + 1) * b):
                base = (y * w + gx * b) * 3
                for x in range(b):
                    o = base + x * 3
                    s += px[o] + px[o + 1] + px[o + 2]
            mean = s // (3 * b * b)
            out[gy * 12 + gx] = 255 if mean >= 128 else 0
    return bytes(out)

def _sad12(a, b):
    return sum(abs(x - y) for x, y in zip(a, b))

def nf_shapetrans(f):
    w, h, px = parse_img(f)
    if w == 96:
        protos = (P96_CIRCLE, P96_TRIANGLE, P96_SQUARE)
    else:
        protos = (P48_CIRCLE, P48_TRIANGLE, P48_SQUARE)
    g = _downsample12(px, w, h)
    sads = [_sad12(g, p) for p in protos]
    best, bv = 0, sads[0]
    for i in (1, 2):
        if sads[i] < bv:
            best, bv = i, sads[i]
    return best  # ties -> lowest index

# ---------------------------------------------------------------- T4 pitch
def _zc_freq(samps, rate):
    zc = 0
    n = len(samps)
    for i in range(n - 1):
        a, b = samps[i], samps[i + 1]
        if (a >= 0) != (b >= 0) and (abs(a) > 800 or abs(b) > 800):
            zc += 1
    return (zc * rate) // (2 * n) if n > 1 else 0

def nf_pitchdisc(f):
    rate, ns, samps = parse_pcm(f)
    # F layout: toneA 0-0.9s, gap, toneB 0.98-2.0s (glide).
    # G layout: toneA 0-0.9s, gap, toneB' 0.98-2.0s (steady).
    a0, a1 = int(0.10 * rate), int(0.80 * rate)
    b0, b1 = int(1.10 * rate), int(1.90 * rate)
    fA = _zc_freq(samps[a0:a1], rate)
    fB = _zc_freq(samps[b0:b1], rate)
    if fA <= 0:
        return 0
    rel = abs(fB - fA) * 1000 // fA   # per-mille
    if rel < 5:
        return 0
    return 1 if fB > fA else 2

# ---------------------------------------------------------------- T5 timbre
# brightness = 1000 * sum|x[i+1]-x[i]| / sum|x[i]| over the middle 80% of the tone.
# Thresholds calibrated on canonical 2.0s profiles (cal1.py):
#   PURE=172 DARK=200 RICH=254 BRIGHT=439 -> thresh [186,227,346], order PURE<DARK<RICH<BRIGHT.
T5_THRESH = [186, 227, 346]
T5_ORDER = [0, 2, 3, 1]   # class per ascending-brightness slot: PURE,DARK,RICH,BRIGHT

def nf_timbredisc(f):
    rate, ns, samps = parse_pcm(f)
    lo, hi = ns // 10, ns - ns // 10
    seg = samps[lo:hi]
    num = 0
    den = 0
    for i in range(len(seg) - 1):
        d = seg[i + 1] - seg[i]
        num += d if d >= 0 else -d
    for v in seg:
        den += v if v >= 0 else -v
    br = (num * 1000) // (den + 1)
    slot = 0
    if br >= T5_THRESH[0]:
        slot = 1
    if br >= T5_THRESH[1]:
        slot = 2
    if br >= T5_THRESH[2]:
        slot = 3
    return T5_ORDER[slot]

# ---------------------------------------------------------------- T6 motion
DIRS8 = [(0, -1), (1, -1), (1, 0), (1, 1), (0, 1), (-1, 1), (-1, 0), (-1, -1)]
DIR_NAMES = ["N", "NE", "E", "SE", "S", "SW", "W", "NW"]

def _gray_frame(fr, w, h):
    g = bytearray(w * h)
    for i in range(w * h):
        o = i * 3
        g[i] = (fr[o] * 77 + fr[o + 1] * 150 + fr[o + 2] * 29) >> 8
    return g

def nf_motiondir(f):
    nframes, w, h, frames = parse_frames(f)
    grays = [_gray_frame(fr, w, h) for fr in frames]
    # central region with 2px margin for +-2 shifts
    xs = range(2, w - 2)
    ys = range(2, h - 2)
    votes = [0] * 8
    for k in range(nframes - 1):
        g0, g1 = grays[k], grays[k + 1]
        best, bv = 0, None
        for d, (dx, dy) in enumerate(DIRS8):
            sx, sy = 2 * dx, 2 * dy
            sad = 0
            for y in ys:
                r0, r1 = y * w, (y + sy) * w
                for x in xs:
                    sad += abs(g0[r0 + x] - g1[r1 + x + sx])
            if bv is None or sad < bv:
                best, bv = d, sad
        votes[best] += 1
    best, bv = 0, votes[0]
    for i in range(1, 8):
        if votes[i] > bv:
            best, bv = i, votes[i]
    return best  # ties -> lowest index

# ---------------------------------------------------------------- reference gate
NAIVE = [nf_colordisc, nf_colorconst, nf_shapetrans, nf_pitchdisc, nf_timbredisc, nf_motiondir]

def ref_gate(task, f, g):
    """Reference admission gate: same naive judgment on F and on G;
    WITHHOLD iff they disagree. Returns (decision, formation_j, gate_j)."""
    fj = NAIVE[task](f)
    gj = NAIVE[task](g)
    return (1 if fj != gj else 0), fj, gj

def broken_gate(task, f, g):
    """Positive control: gate evidence = formation span (F again). Always agrees."""
    fj = NAIVE[task](f)
    return 0, fj, fj
