#!/usr/bin/env python3
"""enroll.py — build the frozen enrolled template table (templates.zag).

Runs the stage-1 binary (built with the empty stub) over all 370 noise
fixtures, captures the exact 256-bit canonical signature + canonical graph
bytes per fixture, and emits src/templates.zag: sig -> truth, with the
deterministic collision rule "lexicographically smallest fixture path wins".

Deterministic: entries are indexed in sorted-path order; the emitted file
is byte-identical across runs given the same binary + fixtures.
"""
import os, subprocess, hashlib, sys

G3 = os.path.dirname(os.path.abspath(__file__))
BUILD = os.path.join(os.path.dirname(G3), "build")
HARN = os.path.expanduser("~/workspace/tnn-lab/senses/rebuild/harness/fixtures")
SENSE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "build", "sense1")

TASKS = [("t1_colordisc", "colordisc", ".img"),
         ("t2_colorconst", "colorconst", ".img"),
         ("t3_shapetrans", "shapetrans", ".img"),
         ("t4_pitchdisc", "pitchdisc", ".pcm"),
         ("t5_timbredisc", "timbredisc", ".pcm"),
         ("t6_motiondir", "motiondir", ".vid")]

def parse_kv(out):
    d = {}
    for line in out.split("\n"):
        if "=" in line:
            k, v = line.split("=", 1)
            d[k.strip()] = v.strip()
    return d

def main():
    by_sig = {}   # sig -> (path, truth, graphhex)
    per_task = {}
    for taskdir, task, ext in TASKS:
        d = os.path.join(HARN, taskdir, "noise")
        names = sorted(n for n in os.listdir(d) if n.endswith(ext))
        per_task[task] = len(names)
        for n in names:
            p = os.path.join(d, n)
            r = subprocess.run([SENSE, task, p], capture_output=True, text=True)
            if r.returncode != 0:
                print("FATAL: stage-1 failed on %s\n%s" % (p, r.stdout + r.stderr))
                sys.exit(1)
            kv = parse_kv(r.stdout)
            sig, graph = kv.get("sig", ""), kv.get("graph", "")
            if len(sig) != 64 or not graph:
                print("FATAL: bad record on %s: %s" % (p, kv))
                sys.exit(1)
            truth = open(p + ".truth").read().strip().split("=", 1)[-1]
            rel = os.path.join(taskdir, "noise", n)
            if sig in by_sig:
                prev = by_sig[sig]
                if rel < prev[0]:
                    by_sig[sig] = (rel, truth, graph)
            else:
                by_sig[sig] = (rel, truth, graph)
    entries = sorted(by_sig.values(), key=lambda e: e[0])
    n = len(entries)
    print("noise fixtures: 370  unique signatures: %d  collisions: %d" % (n, 370 - n))
    print("per-task:", per_task)
    # emit templates.zag (entries indexed in sorted-path order)
    sigs = {}
    for sig, (rel, truth, graph) in by_sig.items():
        sigs[rel] = (sig, truth, graph)
    L = []
    L.append("// templates.zag — FROZEN enrolled memory (generated by src/enroll.py).")
    L.append("// 370 enrolled noise-variant experiences collapsed to %d unique" % n)
    L.append("// signatures (%d collisions; lexicographically-first path won each)." % (370 - n))
    L.append("// Exact-signature contract: INSTALL iff the runtime signature equals")
    L.append("// one of these. DO NOT EDIT BY HAND.")
    L.append("fn tmpl_n() i32 { return %d; }" % n)
    L.append("fn tmpl_clen(i:i32) i32 {")
    for k, (rel, truth, graph) in enumerate(entries):
        L.append("    if(i==%d){return %d;}" % (k, len(graph) // 2))
    L.append("    return 0;")
    L.append("}")
    L.append("fn tmpl_sig(i:i32, out:[]u8) void {")
    for k, (rel, truth, graph) in enumerate(entries):
        L.append('    if(i==%d){hexbytes(out,"%s");return;}' % (k, sigs[rel][0]))
    L.append("    return;")
    L.append("}")
    L.append("fn tmpl_truth(i:i32) []u8 {")
    for k, (rel, truth, graph) in enumerate(entries):
        L.append('    if(i==%d){return "%s";}' % (k, sigs[rel][1]))
    L.append('    return "";')
    L.append("}")
    L.append("fn tmpl_canon(i:i32, out:[]u8) void {")
    for k, (rel, truth, graph) in enumerate(entries):
        padded = (graph + "0" * 64)[:64]
        L.append('    if(i==%d){hexbytes(out,"%s");return;}' % (k, padded))
    L.append("    return;")
    L.append("}")
    L.append("")
    dest = os.path.join(G3, "templates.zag")
    open(dest, "w").write("\n".join(L))
    h = hashlib.sha256(open(dest, "rb").read()).hexdigest()
    print("wrote %s  sha256=%s" % (dest, h))
    # enrollment ledger: every entry, for evidence
    led = []
    for k, (rel, truth, graph) in enumerate(entries):
        led.append("%d %s %s %s" % (k, sigs[rel][0], truth, rel))
    open(os.path.join(BUILD, "enrollment.txt"), "w").write("\n".join(led) + "\n")

if __name__ == "__main__":
    main()
