#!/usr/bin/env python3
"""mk_layout.py — generates w_layout.zag: fixed arena memory-map constants.

Deterministic. The arena is one []u8; all tables live at fixed offsets.
All table values are little-endian i64. Run: python3 mk_layout.py > w_layout.zag
"""
import sys

# (name, size_bytes)
regions = [
    ("HDR", 256),
    ("POOL", 131072),
    ("STROFF", 262144),  # 32768 * 8
    ("STRLEN", 262144),  # 32768 * 8
    ("STORE", 8192),     # 64 * 128 (16 i64 each)
    ("SYN", 512),        # 32 * 2 i64
    ("ANT", 256),        # 8 * 2 i64  (padded)
    ("NUM", 512),        # 16 * 2 i64 (padded)
    ("STOP", 512),       # 32 * 8 (padded)
    ("FEAT", 2560),      # 16 * 160 (word_sid,nfeats,feat_sids[8] + pad = 20 i64)
    ("RULE", 1280),      # 8 * 160 (name_sid,nprem,prem0,prem1,concl + pad)
    ("FIX", 25600),      # 200 * 128 (16 i64 each)
    ("ATOM", 65536),     # 1024 * 64 (8 i64 each)
    ("STEP", 131072),    # 1024 * 128 (16 i64 each)
    ("IN", 65536),       # 2048 * 32 (4 i64 each)
    ("LEDGER", 32768),   # 256 * 128 (seq + hash32 + prev32 + pad)
    ("WORK", 65536),
    ("OUT", 65536),
]

off = 0
out = []
out.append("// GENERATED by mk_layout.py — DO NOT EDIT")
for name, size in regions:
    out.append("fn L_%s() i64 { return %d; }" % (name, off))
    out.append("fn L_%s_END() i64 { return %d; }" % (name, off + size))
    off += size
out.append("fn L_ARENA() i64 { return %d; }" % off)

# header field offsets
hdr = ["POOL_USED", "NSTR", "NSTORE", "NSYN", "NANT", "NNUM", "NSTOP",
       "NFEATW", "NRULE", "NFIX", "NATOM", "NSTEP", "NIN", "NLEDGER",
       "LEDGER_TIP", "WORK_USED", "OUT_USED"]
for i, h in enumerate(hdr):
    out.append("fn H_%s() i64 { return %d; }" % (h, i * 8))

# caps
caps = {"MAXSTR": 32768, "MAXSTORE": 64, "MAXSYN": 32, "MAXANT": 8,
        "MAXNUM": 16, "MAXSTOP": 32, "MAXFEATW": 16, "MAXFEATF": 8,
        "MAXRULE": 8, "MAXFIX": 200, "MAXATOM": 1024, "MAXSTEP": 1024,
        "MAXIN": 2048, "MAXLEDGER": 256}
for k, v in caps.items():
    out.append("fn C_%s() i64 { return %d; }" % (k, v))

# corpus ids
for i, c in enumerate(["CONFAB", "SMUGGLE", "GOLD", "PARA", "ALIBI",
                       "GENAUTH", "HALPTR", "HELD"], 1):
    out.append("fn CORP_%s() i64 { return %d; }" % (c, i))

sys.stdout.write("\n".join(out) + "\n")
print("arena bytes: %d" % off, file=sys.stderr)
