#!/usr/bin/env python3
"""gen_pd.py — principle-detection crew: generates principle.zag + expected.json.

Single source of truth for the frozen battery (PREREG.md). The .zag is
generated; edit THIS file, not the .zag.
"""
import json, os

OUT = os.path.dirname(os.path.abspath(__file__))

# ---- classes: id -> parent (0 ROOT) ----
CLS_PARENT = {
    0: -1, 1: 0, 2: 1, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0,
    10: 0, 11: 12, 12: 0, 13: 12, 14: 12, 15: 0, 16: 0,
}
# ---- subjects: id -> class ----
SUBJ_CLASS = {
    100: 1, 101: 2, 102: 2, 103: 1, 104: 1, 105: 3, 106: 3, 107: 3,
    108: 4, 109: 5, 110: 6, 111: 7, 112: 8, 113: 9, 114: 10, 115: 6,
    116: 11, 117: 13, 118: 15, 119: 14, 120: 16, 121: 4,
}
# ---- principles: idx -> (class, prop, expected, confidence) ----
PRINCIPLES = [
    (1, 1, 1, 100),    # P1  mammals: reproduction = LIVE_BIRTH
    (3, 1, 2, 100),    # P2  birds: reproduction = EGGS
    (4, 1, 2, 100),    # P3  fish: reproduction = EGGS
    (5, 1, 2, 100),    # P4  reptiles: reproduction = EGGS
    (1, 2, 1, 100),    # P5  mammals: milk = YES
    (3, 2, 0, 100),    # P6  birds: milk = NO
    (1, 3, 1, 100),    # P7  mammals: breathes = AIR
    (4, 3, 2, 100),    # P8  fish: breathes = GILLS
    (3, 4, 1, 100),    # P9  birds: feathers = YES
    (6, 5, 100, 100),  # P10 water: boiling_point = 100
    (7, 6, 1, 100),    # P11 ice: floats = YES
    (8, 7, 1, 100),    # P12 iron: sinks = YES
    (9, 7, 0, 100),    # P13 wood: sinks = NO
    (12, 11, 1, 100),  # P14 planets: rotation = PROGRADE
    (13, 8, 0, 100),   # P15 mars: human_walked = NO
    (11, 9, 1, 100),   # P16 earth: orbits_sun = YES
    (15, 10, 1, 100),  # P17 moon: orbits_earth = YES
    (13, 9, 1, 100),   # P18 mars: orbits_sun = YES
    (5, 2, 0, 40),     # P19 reptiles: milk = NO (WEAK, probes only)
]
# ---- exemptions: (principle_idx, subject) ----
EXEMPTIONS = [(0, 101), (0, 102), (9, 115), (13, 119)]
# ---- facts: (subj, prop, value, expected_verdict, probe) ----
# verdicts: 0 accept, 1 withhold, 2 accept+refine, 3 accept-noscope, 9 unscored probe
FACTS = [
    (100, 1, 1, 0, 0), (103, 1, 1, 0, 0), (104, 1, 1, 0, 0),
    (105, 1, 2, 0, 0), (106, 1, 2, 0, 0), (107, 1, 2, 0, 0),
    (121, 1, 2, 0, 0), (109, 1, 2, 0, 0), (101, 2, 1, 0, 0),
    (102, 2, 1, 0, 0), (100, 3, 1, 0, 0), (108, 3, 2, 0, 0),
    (105, 4, 1, 0, 0), (105, 2, 0, 0, 0),
    (100, 1, 2, 1, 0), (103, 1, 2, 1, 0), (105, 2, 1, 1, 0),
    (108, 3, 1, 1, 0), (107, 4, 0, 1, 0),
    (101, 1, 2, 2, 0), (102, 1, 2, 2, 0),
    (110, 5, 100, 0, 0), (111, 6, 1, 0, 0), (112, 7, 1, 0, 0),
    (113, 7, 0, 0, 0),
    (110, 5, 90, 1, 0), (111, 6, 0, 1, 0), (112, 7, 0, 1, 0),
    (113, 7, 1, 1, 0),
    (115, 5, 71, 2, 0), (114, 5, 357, 3, 0),
    (117, 8, 0, 0, 0), (116, 9, 1, 0, 0), (118, 10, 1, 0, 0),
    (117, 9, 1, 0, 0),
    (117, 8, 1, 1, 0), (116, 9, 0, 1, 0), (118, 10, 0, 1, 0),
    (116, 11, 1, 0, 0), (117, 11, 1, 0, 0),
    (119, 11, 2, 2, 0), (117, 11, 2, 1, 0),
    (120, 10, 0, 3, 0),
    (109, 2, 0, 9, 1), (109, 2, 1, 9, 1),
]
assert len(FACTS) == 45
assert len(PRINCIPLES) == 19
assert len(EXEMPTIONS) == 4
# sanity: unique (class,prop) over principles
assert len({(c, p) for c, p, _, _ in PRINCIPLES}) == 19
# sanity: scored counts
sc = [f for f in FACTS if f[4] == 0]
assert sum(1 for f in sc if f[3] == 1) == 13, "violations"
assert sum(1 for f in sc if f[3] == 2) == 4, "exceptions"
assert sum(1 for f in sc if f[3] == 0) == 24, "consistent"
assert sum(1 for f in sc if f[3] == 3) == 2, "noscope"


def puts(base, vals):
    return "\n".join(
        "    tput(tab,%d,%d,%d);" % (base, i, v) for i, v in enumerate(vals))


INIT = "\n".join([
    "fn pd_init(tab:[]u8)void {",
    puts(0, [CLS_PARENT[i] for i in range(17)]),
    puts(68, [SUBJ_CLASS[100 + i] for i in range(22)]),
    puts(156, [p[0] for p in PRINCIPLES]),
    puts(232, [p[1] for p in PRINCIPLES]),
    puts(308, [p[2] for p in PRINCIPLES]),
    puts(384, [p[3] for p in PRINCIPLES]),
    puts(460, [e[0] for e in EXEMPTIONS]),
    puts(476, [e[1] for e in EXEMPTIONS]),
    puts(492, [f[0] for f in FACTS]),
    puts(672, [f[1] for f in FACTS]),
    puts(852, [f[2] for f in FACTS]),
    puts(1032, [f[3] for f in FACTS]),
    puts(1212, [f[4] for f in FACTS]),
    "}",
])

LOGIC = r"""// principle.zag — principle-detection crew (pure Zag, zero RNG).
// GENERATED by gen_pd.py — do not hand-edit; edit the generator.
// Derivation: universal instantiation over a class hierarchy (find_principle).
// Arch A (mode a): derive -> direct verdict (confidence-blind rule).
// Arch B (mode b): derive -> materialize implied claim -> trust arbitration
//   (implied trust = principle confidence vs taught trust 50).
// Usage: ./principle <a|b> <rep>     (rep accepted, never printed)
// Build: znc_linux_x86_64_abed8aa1 principle.zag -o principle --no-analyze

fn m_alloc(n:i32)[]u8 {
    if(n<1){let e:[]u8="";return e;}
    let p:*u8=_zag_malloc(n as i64) as *u8;
    if((p as i64)==0){let e2:[]u8="";return e2;}
    let b:[]u8=p[0..n];
    let i:i32=0;
    while(i<n){b[i]=0;i=i+1;}
    return b;
}
fn m_g32(b:[]u8,o:i32)i32 {
    let v:i32=0;
    v=v|((b[o] as i32)&255);
    v=v|(((b[o+1] as i32)&255)<<8);
    v=v|(((b[o+2] as i32)&255)<<16);
    v=v|(((b[o+3] as i32)&255)<<24);
    return v;
}
fn m_s32(b:[]u8,o:i32,v:i32)void {
    b[o]=(v&255) as u8;
    b[o+1]=((v>>8)&255) as u8;
    b[o+2]=((v>>16)&255) as u8;
    b[o+3]=((v>>24)&255) as u8;
}
fn m_pnum(v:i64)void {
    let s:[]u8=_zag_i64_to_str(v);
    _zag_print(s);
    _zag_free(_zag_slice_ptr(s));
}
fn tget(t:[]u8,base:i32,i:i32)i32 {
    return m_g32(t,base+i*4);
}
fn tput(t:[]u8,base:i32,i:i32,v:i32)void {
    m_s32(t,base+i*4,v);
}
fn ops_add(ops:[]u8,n:i32)void {
    m_s32(ops,0,m_g32(ops,0)+n);
}
// table bases: CLS 0 | SUBJ 68 | PC 156 | PP 232 | PE 308 | PCF 384 |
// EXC_P 460 | EXC_S 476 | FS 492 | FP 672 | FV 852 | FE 1032 | FPR 1212 |
// VERD 1392 | INST 1572 | REF 1752

fn find_principle(t:[]u8,ops:[]u8,cls:i32,prop:i32)i32 {
    let c:i32=cls;
    while(c>=0){
        let i:i32=0;
        while(i<19){
            ops_add(ops,1);
            if(tget(t,156,i)==c){
                if(tget(t,232,i)==prop){return i;}
            }
            i=i+1;
        }
        c=tget(t,0,c);
    }
    return -1;
}
fn is_exempt(t:[]u8,ops:[]u8,pi:i32,subj:i32)i32 {
    let k:i32=0;
    while(k<4){
        ops_add(ops,1);
        if(tget(t,460,k)==pi){
            if(tget(t,476,k)==subj){return 1;}
        }
        k=k+1;
    }
    return 0;
}
fn do_install(t:[]u8,f:i32)void {
    tput(t,1572,f,1);
}
// shared derivation front-end; returns principle idx or -2 for no-scope
fn derive(t:[]u8,ops:[]u8,f:i32,out:[]u8)void {
    let subj:i32=tget(t,492,f);
    let prop:i32=tget(t,672,f);
    let val:i32=tget(t,852,f);
    let cls:i32=tget(t,68,subj-100);
    ops_add(ops,4);
    let pi:i32=find_principle(t,ops,cls,prop);
    m_s32(out,0,subj);
    m_s32(out,4,prop);
    m_s32(out,8,val);
    m_s32(out,12,pi);
    if(pi>=0){
        m_s32(out,16,tget(t,308,pi));
        m_s32(out,20,tget(t,384,pi));
    }
}
fn arch_a(t:[]u8,ops:[]u8,f:i32)i32 {
    let out:[]u8=m_alloc(24);
    derive(t,ops,f,out);
    let subj:i32=m_g32(out,0);
    let val:i32=m_g32(out,8);
    let pi:i32=m_g32(out,12);
    _zag_free(_zag_slice_ptr(out));
    if(pi<0){do_install(t,f);return 3;}
    let exp:i32=tget(t,308,pi);
    ops_add(ops,1);
    if(exp==val){do_install(t,f);return 0;}
    if(is_exempt(t,ops,pi,subj)==1){do_install(t,f);tput(t,1752,f,pi+1);return 2;}
    return 1;
}
fn arch_b(t:[]u8,ops:[]u8,f:i32)i32 {
    let out:[]u8=m_alloc(24);
    derive(t,ops,f,out);
    let subj:i32=m_g32(out,0);
    let val:i32=m_g32(out,8);
    let pi:i32=m_g32(out,12);
    _zag_free(_zag_slice_ptr(out));
    if(pi<0){do_install(t,f);return 3;}
    let exp:i32=tget(t,308,pi);
    ops_add(ops,1);
    if(exp==val){do_install(t,f);return 0;}
    if(is_exempt(t,ops,pi,subj)==1){do_install(t,f);tput(t,1752,f,pi+1);return 2;}
    // conflict: arbitrate implied claim (trust = principle confidence)
    // against taught claim (trust 50)
    let pt:i32=tget(t,384,pi);
    ops_add(ops,1);
    if(pt>50){return 1;}
    if(pt<50){do_install(t,f);return 0;}
    return 1;
}
fn main()void {
    let a1:[]u8=_zag_arg(1);
    let a2:[]u8=_zag_arg(2);
    if(a1.len==0||a2.len==0){
        _zag_println("usage: principle <a|b> <rep>");
        return;
    }
    let mode:i32=-1;
    if(_zag_strcmp(a1,"a")==1){mode=0;}
    if(_zag_strcmp(a1,"b")==1){mode=1;}
    if(mode<0){_zag_println("bad mode");return;}
    let tab:[]u8=m_alloc(2048);
    let ops:[]u8=m_alloc(4);
    if(tab.len==0||ops.len==0){_zag_println("alloc failed");return;}
    pd_init(tab);
    let f:i32=0;
    while(f<45){
        let v:i32=0;
        if(mode==0){v=arch_a(tab,ops,f);}
        if(mode==1){v=arch_b(tab,ops,f);}
        tput(tab,1392,f,v);
        _zag_print("F");
        m_pnum((f+1) as i64);
        _zag_print(" ");
        m_pnum(v as i64);
        _zag_println("");
        f=f+1;
    }
    let c0:i32=0;
    let c1:i32=0;
    let c2:i32=0;
    let c3:i32=0;
    let inst:i32=0;
    let ref:i32=0;
    let hh:i64=1469598103934665603;
    f=0;
    while(f<45){
        let v:i32=tget(tab,1392,f);
        if(v==0){c0=c0+1;}
        if(v==1){c1=c1+1;}
        if(v==2){c2=c2+1;}
        if(v==3){c3=c3+1;}
        if(tget(tab,1572,f)==1){inst=inst+1;}
        if(tget(tab,1752,f)>0){ref=ref+1;}
        let x:i64=((f+1) as i64)*1000003+(v as i64)*7919;
        hh=hh^x;
        hh=hh*1099511628211;
        f=f+1;
    }
    let opsn:i32=m_g32(ops,0);
    _zag_print("PD_SUMMARY,mode=");
    if(mode==0){_zag_print("a");}
    if(mode==1){_zag_print("b");}
    _zag_print(",n=45");
    _zag_print(",v0=");
    m_pnum(c0 as i64);
    _zag_print(",v1=");
    m_pnum(c1 as i64);
    _zag_print(",v2=");
    m_pnum(c2 as i64);
    _zag_print(",v3=");
    m_pnum(c3 as i64);
    _zag_print(",installed=");
    m_pnum(inst as i64);
    _zag_print(",refined=");
    m_pnum(ref as i64);
    _zag_print(",ops=");
    m_pnum(opsn as i64);
    _zag_print(",digest=");
    let hexd:[]u8="0123456789abcdef";
    let sh:[]u8=m_alloc(17);
    let ni:i32=0;
    while(ni<16){
        let shift:i64=((15-ni)*4) as i64;
        let nib:i32=((hh>>shift)&15) as i32;
        sh[ni]=hexd[nib];
        ni=ni+1;
    }
    _zag_print(sh[0..16]);
    _zag_println("");
    _zag_println("PD_DONE");
}
"""

# insert init before main: place INIT right after the table-bases comment
src = LOGIC
anchor = "// VERD 1392 | INST 1572 | REF 1752\n"
assert anchor in src
src = src.replace(anchor, anchor + "\n" + INIT + "\n")
with open(os.path.join(OUT, "principle.zag"), "w") as fh:
    fh.write(src)

exp = {}
for i, (s, p, v, e, pr) in enumerate(FACTS):
    exp[str(i + 1)] = {"subj": s, "prop": p, "val": v,
                       "expect": e, "probe": pr}
with open(os.path.join(OUT, "expected.json"), "w") as fh:
    json.dump({"facts": exp,
               "principles": [list(x) for x in PRINCIPLES],
               "exemptions": [list(x) for x in EXEMPTIONS]}, fh, indent=1)
print("wrote principle.zag (%d bytes) + expected.json" %
      os.path.getsize(os.path.join(OUT, "principle.zag")))
