#!/usr/bin/env python3
"""Proxy battery author for the autonomous RSI run.

Same family as battery_r4c.csv (frozen PREREG_R4C class structure), all
items DISJOINT (different value scheme: step 20, offset bases). Ground
truth lives ONLY in proxy_battery.csv, which the SUBJECT never sees —
the proposer (apparatus, RSI-3-D1 analog) alone may read it for
simulation. The real battery's gt stays sealed from the proposer too;
it sees real FIELDS only (for cost/V2 computation).

Outputs (into the run dir):
  proxy_battery.csv      (oracle/glue only — carries gt + class)
  proxy_table.zag.inc    (Zag literal: fields + gt + class codes)
"""
import csv

EQ, LT, GT = 0, 1, 2
SILENT = -1
CLS = {"N-clean": 1, "O-clean": 2, "ADV-NEW": 3, "ADV-OLD": 4, "NEITHER": 5}

def sat(v, aval, op):
    if op == EQ: return v == aval
    if op == LT: return v < aval
    return v > aval

def score(vold, vnew, rels, pick):
    v = vnew if pick == "NEW" else vold
    return sum(1 if sat(v, a, op) else -1 for (a, op) in rels)

def apply_chan(rels, cidx, caval):
    if cidx == SILENT: return rels
    out = [list(r) for r in rels]
    out[cidx][0] = caval
    return [(a, op) for (a, op) in out]

items = []
iid = 0
def add(key, vold, vnew, rels, cidx, caval, gt, cls):
    global iid
    iid += 1
    items.append(dict(id=iid, key=key, vold=vold, vnew=vnew,
                      rels=rels, cidx=cidx, caval=caval, gt=gt, cls=cls))

# value scheme: base 105/205/155, step 20 (real battery: 100/200/150 step 10)
for i in range(6):      # N-clean x6
    o, n, m = 105+20*i, 205+20*i, 155+20*i
    add(1100+i, o, n, [(m, LT), (m, GT), (n, EQ)], SILENT, 0, "NEW", "N-clean")
for i in range(6):      # O-clean x6
    o, n, m = 205+20*i, 105+20*i, 155+20*i
    add(2100+i, o, n, [(m, LT), (m, GT), (o, EQ)], SILENT, 0, "OLD", "O-clean")
for i in range(2):      # ADV-NEW x2
    o, n, m = 105+20*i, 205+20*i, 155+20*i
    add(3100+i, o, n, [(o, EQ), (m, LT), (m, GT)], 0, n, "NEW", "ADV-NEW")
for i in range(2):      # ADV-OLD x2
    o, n, m = 205+20*i, 105+20*i, 155+20*i
    add(4100+i, o, n, [(n, EQ), (m, LT), (m, GT)], 0, o, "OLD", "ADV-OLD")
for i in range(8):      # NEITHER x8
    o, n, m = 105+20*i, 205+20*i, 155+20*i
    add(5100+i, o, n, [(m, LT), (m, GT), (999, EQ)], SILENT, 0, "WITHHOLD", "NEITHER")

assert len(items) == 24

for it in items:
    rels = it["rels"]
    so_pre = score(it["vold"], it["vnew"], rels, "OLD")
    sn_pre = score(it["vold"], it["vnew"], rels, "NEW")
    rels_post = apply_chan(rels, it["cidx"], it["caval"])
    so_post = score(it["vold"], it["vnew"], rels_post, "OLD")
    sn_post = score(it["vold"], it["vnew"], rels_post, "NEW")
    cls, gt = it["cls"], it["gt"]
    if cls == "N-clean":
        assert sn_pre > so_pre and it["cidx"] == SILENT and gt == "NEW", it
    elif cls == "O-clean":
        assert so_pre > sn_pre and it["cidx"] == SILENT and gt == "OLD", it
    elif cls == "ADV-NEW":
        assert so_pre > sn_pre and sn_post > so_post and gt == "NEW", it
    elif cls == "ADV-OLD":
        assert sn_pre > so_pre and so_post > sn_post and gt == "OLD", it
    elif cls == "NEITHER":
        assert so_pre == sn_pre <= 0 and so_post == sn_post and gt == "WITHHOLD", it
    else:
        raise AssertionError(cls)

# disjointness vs the real battery: no shared (key) and no shared value triple
real_keys = set()
import csv as _csv
with open("battery_r4c.csv") as f:
    for row in _csv.DictReader(f):
        real_keys.add(int(row["key"]))
proxy_keys = {it["key"] for it in items}
assert not (proxy_keys & real_keys), "proxy keys overlap real battery"

with open("proxy_battery.csv", "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["id","key","vold","vnew","a1","op1","a2","op2","a3","op3",
                "cidx","caval","gt","class"])
    for it in items:
        (a1,op1),(a2,op2),(a3,op3) = it["rels"]
        w.writerow([it["id"],it["key"],it["vold"],it["vnew"],a1,op1,a2,op2,
                    a3,op3,it["cidx"],it["caval"],it["gt"],it["cls"]])

GT = {"NEW": 1, "OLD": 2, "WITHHOLD": 0}
with open("proxy_table.zag.inc", "w") as f:
    f.write("// generated by gen_proxy_battery.py — DO NOT HAND-EDIT\n")
    f.write("// PROXY battery: fields + gt + class. The SUBJECT must never see this file.\n")
    f.write("// 24 items x 14 i32: id,key,vold,vnew,a1,op1,a2,op2,a3,op3,cidx,caval,gt,cls\n")
    f.write("fn pbatt_data()[336]i32 {\n    return [\n")
    for it in items:
        (a1,op1),(a2,op2),(a3,op3) = it["rels"]
        vals = [it["id"],it["key"],it["vold"],it["vnew"],a1,op1,a2,op2,
                a3,op3,it["cidx"],it["caval"],GT[it["gt"]],CLS[it["cls"]]]
        f.write("        " + ",".join(str(v) for v in vals) + ",\n")
    f.write("    ];\n}\n")
print("wrote proxy_battery.csv and proxy_table.zag.inc (24 items, disjoint keys OK)")
