#!/usr/bin/env python3
"""Single source of truth for the autonomous run's decision rules.

Reads battery_r4c.csv (real, fields only) and proxy_battery.csv
(fields + gt + class) and emits decide.zag.inc containing:
  - fld(b,i,f): field accessor. b=0 real (f:0..10), b=1 proxy (f:0..12,
    f=11 gt code 0/1/2, f=12 class code 1..5). Real gt is NEVER emitted.
    f map: 0=key 1=vold 2=vnew 3=a1 4=op1 5=a2 6=op2 7=a3 8=op3 9=cidx 10=caval.
  - rel_sat2, score_pick, slot_mask, decide(b,i,kept,extra) -> packed i64
    (verdict | consult<<8 | ops<<16). kept/extra are bitmasks bit0=C1..
    bit4=C5. decide() implements askfirst + candidate modifications C1..C5
    (CANDIDATES.md), composable in id order.

This one file is pasted into BOTH proposer.zag and subject.zag, so the
proposer's simulation and the subject's real runs share byte-identical
rule code by construction.
"""
import csv

def load(path, with_gt):
    rows = []
    with open(path) as f:
        for r in csv.DictReader(f):
            fields = [int(r["id"]), int(r["key"]), int(r["vold"]), int(r["vnew"]),
                      int(r["a1"]), int(r["op1"]), int(r["a2"]), int(r["op2"]),
                      int(r["a3"]), int(r["op3"]), int(r["cidx"]), int(r["caval"])]
            if with_gt:
                gt = {"WITHHOLD": 0, "NEW": 1, "OLD": 2}[r["gt"]]
                cls = {"N-clean": 1, "O-clean": 2, "ADV-NEW": 3, "ADV-OLD": 4,
                       "NEITHER": 5}[r["class"]]
                fields += [gt, cls]
            rows.append(fields)
    assert len(rows) == 24
    return rows

real = load("battery_r4c.csv", False)
proxy = load("proxy_battery.csv", True)

# separation: the real battery contributes NO gt column to the include
assert all(len(r) == 12 for r in real)

out = []
out.append("// generated by gen_decide.py — DO NOT HAND-EDIT")
out.append("// Single source of truth for decide(); pasted into proposer.zag and subject.zag.")
out.append("// Real battery: fields only (NO gt). Proxy: fields + gt(f=11) + class(f=12).")
out.append("fn fld(b:i32,i:i32,f:i32)i32 {")
for b, rows, nf in ((0, real, 12), (1, proxy, 14)):
    out.append(f"    if(b=={b}){{")
    for r in rows:
        i = r[0] - 1
        out.append(f"        if(i=={i}){{")
        for fidx, val in enumerate(r[1:]):  # skip id; f indexes from 0=key
            out.append(f"            if(f=={fidx}){{return {val};}}")
        out.append("        }")
    out.append("    }")
out.append("    return -9999;")
out.append("}")
out.append("")
out.append("fn rel_sat2(v:i32,a:i32,op:i32)i32 {")
out.append("    if(op==0){if(v==a){return 1;}return 0;}")
out.append("    if(op==1){if(v<a){return 1;}return 0;}")
out.append("    if(v>a){return 1;}return 0;")
out.append("}")
out.append("")
out.append("// score of pick (0=OLD,1=NEW) on battery b item i; ov=-1 pre-channel,")
out.append("// ov=0/1/2 overrides that relation's anchor with caval.")
out.append("fn score_pick(b:i32,i:i32,pick:i32,ov:i32)i32 {")
out.append("    let v:i32=fld(b,i,1);")
out.append("    if(pick==1){v=fld(b,i,2);}")
out.append("    let s:i32=0;")
out.append("    let r:i32=0;")
out.append("    while(r<3){")
out.append("        let a:i32=fld(b,i,3+2*r);")
out.append("        let op:i32=fld(b,i,4+2*r);")
out.append("        if(ov==r){a=fld(b,i,10);}")
out.append("        if(rel_sat2(v,a,op)==1){s=s+1;}else{s=s-1;}")
out.append("        r=r+1;")
out.append("    }")
out.append("    return s;")
out.append("}")
out.append("")
out.append('fn slot_mask(s:[]u8)i32 {')
out.append('    if(_zag_strcmp(s,"c1")==1){return 1;}')
out.append('    if(_zag_strcmp(s,"c2")==1){return 2;}')
out.append('    if(_zag_strcmp(s,"c3")==1){return 4;}')
out.append('    if(_zag_strcmp(s,"c4")==1){return 8;}')
out.append('    if(_zag_strcmp(s,"c5")==1){return 16;}')
out.append("    return 0;")
out.append("}")
out.append("")
out.append("// The decision procedure: askfirst + candidate policies C1..C5.")
out.append("// kept/extra: bitmask bit0=C1 .. bit4=C5. Returns verdict|consult<<8|ops<<16.")
out.append("// verdict: 0=WITHHOLD 1=NEW 2=OLD.")
out.append("fn decide(b:i32,i:i32,kept:i32,extra:i32)i64 {")
out.append("    let mask:i32=kept|extra;")
out.append("    let so:i32=score_pick(b,i,0,-1);")
out.append("    let sn:i32=score_pick(b,i,1,-1);")
out.append("    let c:i32=0;")
out.append("    if(sn>so){c=1;}else{if(so>sn){c=2;}}")
out.append("    let ci:i32=fld(b,i,9);")
out.append("    let consult:i32=0;")
out.append("    if(c!=1){consult=1;}")
out.append("    if((mask&1)!=0){if(ci!=-1){consult=1;}}")
out.append("    if((mask&2)!=0){if(c==1){if((sn-so)<=2){consult=1;}}}")
out.append("    let v:i32=1;")
out.append("    if(consult==1){")
out.append("        let so2:i32=score_pick(b,i,0,ci);")
out.append("        let sn2:i32=score_pick(b,i,1,ci);")
out.append("        v=0;")
out.append("        if(sn2>so2){v=1;}else{if(so2>sn2){v=2;}}")
out.append("        if((mask&4)!=0){if(ci==-1){v=0;}}")
out.append("        if((mask&16)!=0){")
out.append("            if(v!=0){")
out.append("                let m2:i32=so2-sn2;")
out.append("                if(v==1){m2=sn2-so2;}")
out.append("                if(m2<3){v=0;}")
out.append("            }")
out.append("        }")
out.append("    }else{")
out.append("        if((mask&16)!=0){")
out.append("            if((sn-so)<3){v=0;}")
out.append("        }")
out.append("    }")
out.append("    let ops:i32=7;")
out.append("    if(consult==1){ops=ops+16;if((mask&8)!=0){ops=ops-4;}}")
out.append("    let r:i64=(v as i64)|((consult as i64)<<8)|((ops as i64)<<16);")
out.append("    return r;")
out.append("}")
out.append("")

with open("decide.zag.inc", "w") as f:
    f.write("\n".join(out))
print("wrote decide.zag.inc")
