#!/usr/bin/env python3
"""Generate pure-Zag gate fixtures for the phase-3 joke-volume gate.

Reads the FROZEN held-out corpus + blind helper judgments, folds text
(lowercase; keep bytes 32-126; other chars -> space; collapse whitespace),
and emits:
  src/g_corpus.zag  — g_nitems/g_id/g_cat/g_text/g_url
  src/g_helper.zag  — g_h_n/g_h_intent/g_h_marker (markers folded)
  src/g_intent.zag  — frozen compositional classifier (marker lists from
                      TRAINING_RECORD.md, identical to work/clf_proto.py)
  work/gate_manifest.json — folded texts for the Python scorer (D6 etc.)

Fails loudly if any helper marker is not a byte-verbatim substring of the
folded item text (combination rule 3 precondition).
"""
import json, re, os, sys, hashlib, importlib.util

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "src")

FROZEN_HELDOUT_SHA = "ab065f412d352f8ab7ce2cb72148621bf139d1d55f61d950c572810f256c4c1a"
FROZEN_HELPER_SHA = "7ac206488231befdcf53dcdde9ce2259489024a67dce37b152d090583cc7131f"

INTENT_CODE = {"SINCERE": 1, "JOKING": 2, "SATIRE": 3, "DECEPTIVE": 4, "UNCERTAIN": 5}

spec = importlib.util.spec_from_file_location("cp", os.path.join(HERE, "clf_proto.py"))
cp = importlib.util.module_from_spec(spec)
spec.loader.exec_module(cp)

def sha256_file(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        h.update(f.read())
    return h.hexdigest()

def fold(s):
    s = s.lower()
    out = [ch if 32 <= ord(ch) <= 126 else " " for ch in s]
    return re.sub(r"\s+", " ", "".join(out)).strip()

def zag_esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')

def emit_str_fn(lines, prefix, name, vals):
    lines.append(f"fn {prefix}{name}(i:i32)[]u8 {{")
    for idx, v in enumerate(vals):
        lines.append(f'    if(i=={idx}){{return "{zag_esc(v)}";}}')
    lines.append('    return "";')
    lines.append("}")
    lines.append("")

def emit_int_fn(lines, prefix, name, vals):
    lines.append(f"fn {prefix}{name}(i:i32)i32 {{")
    for idx, v in enumerate(vals):
        lines.append(f"    if(i=={idx}){{return {v};}}")
    lines.append("    return 0;")
    lines.append("}")

def main():
    hp = os.path.join(ROOT, "corpus", "heldout.json")
    ep = os.path.join(ROOT, "corpus", "helper.json")
    hs = sha256_file(hp)
    es = sha256_file(ep)
    assert hs == FROZEN_HELDOUT_SHA, f"heldout SHA mismatch: {hs}"
    assert es == FROZEN_HELPER_SHA, f"helper SHA mismatch: {es}"
    print(f"frozen inputs verified: heldout {hs[:16]}… helper {es[:16]}…")

    held = json.load(open(hp, encoding="utf-8"))["items"]
    helpj = json.load(open(ep, encoding="utf-8"))["judgments"]
    assert len(held) == 64 and len(helpj) == 64
    hmap = {j["id"]: j for j in helpj}
    assert [it["id"] for it in held] == [j["id"] for j in helpj], "id order mismatch"

    os.makedirs(SRC, exist_ok=True)
    manifest = []

    # ---- g_corpus.zag ----
    texts, urls, cats, ids = [], [], [], []
    for it in held:
        t = fold(it["text"])
        u = fold(it["url"])
        texts.append(t); urls.append(u); cats.append(it["arm"]); ids.append(it["id"])
        manifest.append({"id": it["id"], "arm": it["arm"], "sub": it["sub"],
                         "text": t, "url": u, "label": it["label"]})
    lines = ["// GENERATED by work/gen_gate.py from frozen corpus/heldout.json — do not hand-edit.", ""]
    lines.append(f"fn g_nitems()i32 {{ return {len(held)}; }}")
    lines.append("")
    emit_str_fn(lines, "g_", "id", ids)
    emit_str_fn(lines, "g_", "cat", cats)
    emit_str_fn(lines, "g_", "text", texts)
    emit_str_fn(lines, "g_", "url", urls)
    with open(os.path.join(SRC, "g_corpus.zag"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote src/g_corpus.zag ({len(held)} items)")

    # ---- g_helper.zag (markers folded; verified as substrings) ----
    bad = []
    intents, markers = [], []
    for it in held:
        j = hmap[it["id"]]
        m = fold(j["cited"])
        t = fold(it["text"])
        if m not in t:
            bad.append((it["id"], j["cited"], m))
        intents.append(INTENT_CODE[j["helper_intent"]])
        markers.append(m)
    if bad:
        for b in bad:
            print(f"MARKER NOT SUBSTRING: {b}", file=sys.stderr)
        sys.exit("FATAL: helper marker(s) not verbatim substrings of folded text")
    lines = ["// GENERATED by work/gen_gate.py from frozen corpus/helper.json — do not hand-edit.", ""]
    lines.append(f"fn g_h_n()i32 {{ return {len(held)}; }}")
    lines.append("")
    emit_int_fn(lines, "g_", "h_intent", intents)
    emit_str_fn(lines, "g_", "h_marker", markers)
    with open(os.path.join(SRC, "g_helper.zag"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote src/g_helper.zag ({len(held)} judgments, all markers verified)")

    # ---- g_intent.zag : frozen compositional classifier ----
    L = []
    L.append("// GENERATED by work/gen_gate.py — frozen rule from TRAINING_RECORD.md §4.")
    L.append("// JOKING if (FRAME>=1 or ACTION>=1) and HARM>=1;")
    L.append("// elif SAT>=2 -> SATIRE; elif TROPE>=1 -> JOKING; else UNCERTAIN.")
    L.append("// SINCERE (1) is never emitted. Pure Zag; no RNG; no timestamps.")
    L.append("")
    L.append('@import("j_ledger.zag")')
    L.append("")
    L.append("fn g_codes_append(codes:[]u8,tok:[]u8)void {")
    L.append("    let n:i32=j_cstrlen(codes);")
    L.append("    if(n>0){codes[n]=43;n=n+1;}")
    L.append("    let i:i32=0;")
    L.append("    while(i<tok.len){codes[n+i]=tok[i];i=i+1;}")
    L.append("    codes[n+tok.len]=0;")
    L.append("    return;")
    L.append("}")
    L.append("")
    L.append("fn g_markers_append(markers:[]u8,mk:[]u8)void {")
    L.append("    let n:i32=j_cstrlen(markers);")
    L.append("    let i:i32=0;")
    L.append("    while(i<mk.len){markers[n+i]=mk[i];i=i+1;}")
    L.append("    markers[n+mk.len]=126;")
    L.append("    markers[n+mk.len+1]=0;")
    L.append("    return;")
    L.append("}")
    L.append("")
    L.append("fn g_classify(text:[]u8,url:[]u8,codes:[]u8,markers:[]u8)i32 {")
    L.append("    let t:[]u8=j_tolower(text);")
    L.append("    let nf:i32=0;")
    L.append("    let na:i32=0;")
    L.append("    let nh:i32=0;")
    L.append("    let ns:i32=0;")
    L.append("    let nt:i32=0;")
    for w in cp.FRAME:
        L.append(f'    if(j_has_word(t,"{w}")!=0){{nf=nf+1;g_markers_append(markers,"{w}");}}')
    for w in cp.ACTION:
        L.append(f'    if(j_has_word(t,"{w}")!=0){{na=na+1;g_markers_append(markers,"{w}");}}')
    for w in cp.HARM:
        L.append(f'    if(j_has_word(t,"{w}")!=0){{nh=nh+1;g_markers_append(markers,"{w}");}}')
    for w in cp.SAT:
        L.append(f'    if(j_has_word(t,"{w}")!=0){{ns=ns+1;g_markers_append(markers,"{w}");}}')
    for w in cp.TROPE:
        L.append(f'    if(j_has_word(t,"{w}")!=0){{nt=nt+1;g_markers_append(markers,"{w}");}}')
    L.append("    let s1:i32=nf+na;")
    L.append("    let hit1:i32=0;")
    L.append("    if(s1>=1){hit1=nh;}")
    L.append("    let intent:i32=5;")
    L.append('    if(hit1>=1){intent=2;g_codes_append(codes,"R_FRAME_HARM");}')
    L.append("    if(intent==5){")
    L.append('        if(ns>=2){intent=3;g_codes_append(codes,"R_SATIRE");}')
    L.append("    }")
    L.append("    if(intent==5){")
    L.append('        if(nt>=1){intent=2;g_codes_append(codes,"R_TROPE");}')
    L.append("    }")
    L.append("    if(intent==5){")
    L.append('        g_codes_append(codes,"R_NO_MARKERS");')
    L.append("    }")
    L.append("    return intent;")
    L.append("}")
    L.append("")
    with open(os.path.join(SRC, "g_intent.zag"), "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print("wrote src/g_intent.zag (frozen classifier)")

    with open(os.path.join(HERE, "gate_manifest.json"), "w", encoding="utf-8") as f:
        json.dump({"items": manifest}, f, indent=1)
    print("wrote work/gate_manifest.json")

if __name__ == "__main__":
    main()
