#!/usr/bin/env python3
"""Task 2 oracle — INDEPENDENT reference implementation.

Independence statement: this oracle is written in Python (not Zag), directly
from the frozen formulas in coding/reflection/PREREG.md §2, using
straightforward sample math (math.sin, math.floor, struct.pack). It shares no
code, no algorithms, and no source text with the learner or with the synth
prior-art corpus. The learner's approach (Zag f64 Taylor-series sine, phase
in cycles, piecewise ADSR) was developed separately; agreement between the
two is established only by the byte-exact comparison, whose safety margin
(boundary-distance analysis) is documented in oracle/ANALYSIS.md.

Vectors (frozen):
  V1: 440 Hz sine, 1.0 s, amp 0.5:
      s[n] = floor(32767 * 0.5 * sin(2*pi*440*n/44100)), n in [0,44100)
  V2: 880 Hz sine, 0.5 s, amp 0.8, ADSR A=0.05 D=0.10 S=0.7 note_off=0.35 R=0.15
      sample boundaries: A_s=2205, D_s=4410, note_off=15435, R_s=6615
      attack:    linear 0->1 over [0,2205)
      decay:     1->0.7 over [2205,6615)
      sustain:   0.7 over [6615,15435)
      release:   0.7->0 over [15435,22050)
      s[n] = floor(32767 * 0.8 * env[n] * sin(2*pi*880*n/44100))
  V3: mix of two tones (440 Hz @0.5 + 660 Hz @0.3, 0.5 s):
      m[n] = clamp(s1[n]+s2[n], -32768, 32767) in the sample domain,
      s1[n] = floor(32767*0.5*sin(2*pi*440*n/44100)),
      s2[n] = floor(32767*0.3*sin(2*pi*660*n/44100))

Output: 16-bit PCM mono 44100 Hz WAV, standard 44-byte RIFF header.
Never played as audio; compared as bytes only.
"""
import math
import struct
import hashlib
import sys
import os

SR = 44100


def wav_bytes(samples):
    n = len(samples)
    data = struct.pack('<%dh' % n, *samples)
    header = struct.pack('<4sI4s4sIHHIIHH4sI',
                         b'RIFF', 36 + len(data), b'WAVE',
                         b'fmt ', 16, 1, 1, SR, SR * 2, 2, 16,
                         b'data', len(data))
    assert len(header) == 44
    return header + data


def v1_samples():
    return [math.floor(32767 * 0.5 * math.sin(2 * math.pi * 440 * n / 44100))
            for n in range(44100)]


def v2_samples():
    out = []
    for n in range(22050):
        if n < 2205:
            env = n / 2205
        elif n < 6615:
            env = 1 - 0.3 * (n - 2205) / 4410
        elif n < 15435:
            env = 0.7
        else:
            env = 0.7 * (1 - (n - 15435) / 6615)
        out.append(math.floor(32767 * 0.8 * env *
                              math.sin(2 * math.pi * 880 * n / 44100)))
    return out


def v3_samples():
    out = []
    for n in range(22050):
        s1 = math.floor(32767 * 0.5 * math.sin(2 * math.pi * 440 * n / 44100))
        s2 = math.floor(32767 * 0.3 * math.sin(2 * math.pi * 660 * n / 44100))
        m = s1 + s2
        if m > 32767:
            m = 32767
        elif m < -32768:
            m = -32768
        out.append(m)
    return out


VECTORS = {'1': v1_samples, '2': v2_samples, '3': v3_samples}


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(
        os.path.abspath(__file__))
    digests = {}
    for v, fn in sorted(VECTORS.items()):
        blob = wav_bytes(fn())
        path = os.path.join(outdir, 'oracle_v%s.wav' % v)
        with open(path, 'wb') as f:
            f.write(blob)
        digests[v] = hashlib.sha256(blob).hexdigest()
        print('vector %s: %d bytes sha256=%s' % (v, len(blob), digests[v]))
    with open(os.path.join(outdir, 'FREEZE.txt'), 'w') as f:
        f.write('# Oracle freeze — generated by oracle.py from PREREG.md §2 formulas\n')
        for v in sorted(digests):
            f.write('oracle_v%s.wav sha256=%s\n' % (v, digests[v]))


if __name__ == '__main__':
    main()
