#!/usr/bin/env python3
"""Generate Phase-2 base.zag from the frozen fork mg_chunk.zag.

base.zag = the fork's shared primitives, verbatim, no behavior change:
  * little-endian accessors over []u8 arenas
  * output buffer (ob_raw / ob_i64 / ob_nl)
  * byte-string helpers (has_sub, has_byte, beq, find_sub, parse_digits, ...)
  * chunk primitives (enum_words, find_word, count_words_bytes, chunk_name, ...)
  * parse fns from the question-kinds section (parse_target_letter,
    parse_pos_n, parse_after, parse_between) — but NOT classify/kind_name/
    skind, which Phase 2 redefines in hand_a.zag (extended kind set).

The hand-written Phase-2 sources (hand_a/b/c1/c2/c3.zag, derive.zag)
@import("base.zag") for these primitives.
"""
import sys

FORK = "/home/hatch/workspace/mg_chunking/mg_chunk.zag"
OUT = "/home/hatch/workspace/chunking_learned/base.zag"
src = open(FORK).read()

MARKERS = [
    "little-endian accessors",
    "output buffer",
    "byte-string helpers",
    "chunk primitives",
    "question kinds",
    "magnifying-glass zoom",  # boundary only, not extracted
]
idx = [src.find("// ---------- " + m) for m in MARKERS]
for m, i in zip(MARKERS, idx):
    assert i >= 0, m
secs = {}
for n, m in enumerate(MARKERS[:-1]):
    end = idx[n + 1] if n + 1 < len(MARKERS) else src.find("fn main() i32 {")
    secs[m] = src[idx[n]:end]

kinds = secs["question kinds"]
parse_fns = kinds[kinds.find("fn parse_target_letter"):]
assert "fn parse_target_letter" in parse_fns and "fn parse_between" in parse_fns

HEADER = """// base.zag — shared primitives for Phase 2 (learned chunking).
//
// GENERATED by gen_phase2.py from the frozen magnifying-glass fork
// (~/workspace/mg_chunking/mg_chunk.zag, commit
// 1de59c334aea10907cdc34545c7a3e97a868c6d2). Verbatim extraction of the
// fork's little-endian accessors, output buffer, byte-string helpers,
// chunk primitives, and parse functions. No behavior change. The fork's
// classify/kind_name/skind are NOT included: Phase 2 defines an extended
// classifier (kinds 1-17) in hand_a.zag.
@import("R33_NATIVE_IO_V1.zag")

"""

out = [HEADER]
for m in ["little-endian accessors", "output buffer",
          "byte-string helpers", "chunk primitives"]:
    out.append(secs[m])
out.append("// ---------- parse functions (from the fork's question-kinds section) ----------\n")
out.append(parse_fns)
open(OUT, "w").write("".join(out))
print("wrote base.zag (%d lines)" % "".join(out).count("\n"))
