#!/usr/bin/env python3
"""extract_bank.py -- Build exemplar bank for abl_bank from battery ledger.

Reads the full-mode adversarial ledger, joins with truth from R2-7 gen_ledger,
and selects 20 TRUE (formation correct) and 20 FALSE (formation wrong) exemplars
per task, using confidence as the 1-NN feature.

Outputs Zag code with the exemplar tables.
Deterministic; no RNG.
"""
import json, re, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
FORK = os.path.normpath(os.path.join(HERE, ".."))
R27 = os.path.normpath(os.path.join(FORK, "..", "R2-7"))

TASKS = ["colordisc","colorconst","shapetrans","pitchdisc","timbredisc","motiondir"]

# Map judgment names to ids (from r216.zag jname)
JMAP = {
    "colordisc": {"SAME":0, "DIFFERENT":1},
    "colorconst": {"SAME_SURFACE":0, "DIFFERENT":1},
    "shapetrans": {"CIRCLE":0, "TRIANGLE":1, "SQUARE":2},
    "pitchdisc": {"SAME":0, "HIGHER":1, "LOWER":2},
    "timbredisc": {"PURE":0, "BRIGHT":1, "DARK":2, "RICH":3},
    "motiondir": {"STILL":0,"N":1,"NE":2,"E":3,"SE":4,"S":5,"SW":6,"W":7,"NW":8},
}

def load_truth():
    truth={}
    for line in open(os.path.join(R27,"evidence","gen_ledger.jsonl")):
        d=json.loads(line)
        truth[d["id"]]=d["truth"]
    return truth

def parse_ledger(path):
    """Yield (fixture_id, task, judgment_name, conf)."""
    pat=re.compile(r'fixture=r2fx_t(\d+)_i(\d+)_f(\d+).*?task=(\w+).*?judgment=(\w+).*?conf=(\d+)')
    # fixture id format: r2fx_t<task>_i<index>_f<family>
    # Need to map back to original id: <split>_<task>_<index>
    # The ledger doesn't have split. We'll need to infer from the list.
    # Actually, let's parse the list file to get the mapping.
    return []

def main():
    ledger_path=os.path.join(FORK,"evidence","batt_b_adv_union_r1.ledger")
    if not os.path.exists(ledger_path):
        print("Ledger not found:",ledger_path)
        sys.exit(1)
    truth=load_truth()
    # We'll need the list to map fixture->original id
    list_path=os.path.join(FORK,"evidence","b_adv.list")
    id_map={}  # (task_idx, index, family) -> original_id
    for line in open(list_path):
        p=line.strip()
        m=re.match(r'.*/(r2n|r2a|r2a2)_(\w+)_(\d+)\.r2fx$',p)
        if m:
            split,task,idx=m.groups()
            # Get family and truth from ledger
            oid="%s_%s_%s"%(split,task,idx)
            # We'll look up family from truth dict via a separate index
            id_map[(task,int(idx))]=oid
    # Actually, simpler: the ledger fixture=r2fx_t4_i0_f0
    # t=task idx, i=index, f=family. We need split. The list is sorted,
    # and the ledger is in list order. So we can zip them.
    with open(list_path) as f:
        list_paths=[l.strip() for l in f]
    # Parse ledger
    import re
    led_pat=re.compile(r'fixture=r2fx_t(\d+)_i(\d+)_f(\d+)\s+task=(\w+)\s+judgment=(\S+)\s+conf=(\d+)')
    exemplars={t:{"true":[],"false":[]} for t in TASKS}
    with open(ledger_path) as f:
        for lineno, line in enumerate(f):
            m=led_pat.search(line)
            if not m: continue
            t_idx,idx,fam,task,jname,conf=m.groups()
            t_idx,idx,fam,conf=int(t_idx),int(idx),int(fam),int(conf)
            # Get original id from list order
            if lineno>=len(list_paths): continue
            p=list_paths[lineno]
            mm=re.match(r'.*/(r2n|r2a|r2a2)_(\w+)_(\d+)\.r2fx$',p)
            if not mm: continue
            split,ltask,lidx=mm.groups()
            oid="%s_%s_%s"%(split,ltask,lidx)
            ttruth=truth.get(oid)
            if not ttruth: continue
            # Map judgment name to id, compare to truth
            jid=JMAP[task].get(jname, -1)
            # Truth names match judgment names
            tid=JMAP[task].get(ttruth, -1)
            correct=(jid==tid and jid>=0)
            key="true" if correct else "false"
            exemplars[task][key].append(conf)
    # Select 20 per task per class (first 20 sorted for determinism)
    for task in TASKS:
        for key in ["true","false"]:
            vals=sorted(exemplars[task][key])[:20]
            exemplars[task][key]=vals
            print("%s %s: n=%d"%(task,key,len(vals)))
    # Output Zag code
    print("\n// Exemplar bank for abl_bank (confidence 1-NN). Generated by extract_bank.py.")
    for ti,task in enumerate(TASKS):
        tvals=exemplars[task]["true"]
        fvals=exemplars[task]["false"]
        # Pad to 20 with -1 if needed
        tvals=(tvals+[-1]*20)[:20]
        fvals=(fvals+[-1]*20)[:20]
        print("fn bank_true_%d(i:i32) i64 {"%ti)
        for i,v in enumerate(tvals):
            print("    if(i == %d) { return %d; }"%(i,v))
        print("    return -1;\n}")
        print("fn bank_false_%d(i:i32) i64 {"%ti)
        for i,v in enumerate(fvals):
            print("    if(i == %d) { return %d; }"%(i,v))
        print("    return -1;\n}")

if __name__=="__main__":
    main()
