#!/usr/bin/env python3
"""DRAFT doc generator for Crew 4 deliverables. DRAFT-FOR-PARENT-WIRING.

Reads gen_draft_reference (deterministic vocabulary + flaws) and emits:
  WIRING_SPEC_DRAFT.md
  sealed/SEALED_FLAW_MANIFEST_DRAFT.md
  FLAW_PLACEMENT_DRAFT.md
All numbers in the docs are computed, never hand-typed.
"""
import os, hashlib, datetime
from gen_draft_reference import (VOCAB, OCC, SLICES, FLAWS, honest_proposals,
                                 session_schedule, conf, slice_hash, SLICE_SIZE,
                                 PROSE_BASE, CODE_BASE)

OUT = os.path.dirname(os.path.abspath(__file__))
SEALED = os.path.join(OUT, "sealed")
os.makedirs(SEALED, exist_ok=True)

SLICE_START = {sid: st for sid, _, st, _ in SLICES}
SLICE_CORP = {sid: c for sid, c, _, _ in SLICES}
VINFO = {v[0]: v for v in VOCAB}

def abs_span(sid, a, b):
    st = SLICE_START[sid]
    return f"{st+a}-{st+b}"

def rel(sid, a, b):
    return f"{a}-{b}"

def pat_repr(pat):
    try:
        return pat.decode("utf-8")
    except Exception:
        return repr(pat)

# ================================================================ WIRING SPEC
L = []
L.append("# Arm-1 (peer-handwired) Wiring Spec — DRAFT-FOR-PARENT-WIRING")
L.append("")
L.append("**Status: DRAFT. Not wired. Not executed. The final wiring is done by the PARENT")
L.append("(Muse) personally — this document is the complete spec the parent executes verbatim.**")
L.append("")
L.append(f"**Draft generated:** 2026-09-21 (UTC) by Crew 4 reference generator "
         "`gen_draft_reference.py` — deterministic, stdlib-only, no RNG, no wallclock.")
L.append("**Binding prereg:** `PREREG_FREEZE.md` §4 B.2 (wiring-spec requirements), B.7 (sealed flaw")
L.append("manifest), B.8 (§C tripwire), §0 T-3/T-4/T-5/T-6/T-11/T-13/T-16 — FROZEN 2026-09-21 (§14).")
L.append("**Design ref:** `TEACHERS.md` 2026-09-21 hand-wired-teacher amendment + installed-vs-learned ruling.")
L.append("")
L.append("## 0. Provenance and corpora")
L.append("")
L.append("Corpus files (downloaded 2026-09-21 for grounding; hashes MUST match at wiring time):")
L.append("- `shakespeare.txt` — Project Gutenberg ebook 100, *The Complete Works of William Shakespeare*,"
         " 5,422,721 bytes, SHA-256 `a023115c2d4e2ee12221bdd780fdf2ac5a864fe225948656f51f8be462c7fffb`")
L.append("- `sqlite3.c` — SQLite 3.53.4 amalgamation (https://www.sqlite.org/2026/sqlite-amalgamation-3530400.zip),"
         " 9,515,341 bytes, SHA-256 `b1dd5d74ec7f29055a6684fa06fb3c2f6821c87dd38f9a458dfd2e8a1db28189`")
L.append("")
L.append("## 1. Curriculum slice layout (T-11 — DRAFT values, parent decides)")
L.append("")
L.append("T-11 was signed 'as proposed' but the proposed numbers were lost with the truncated")
L.append("TEACHERS.md §F. The values below are the Crew 4 draft; the parent confirms or replaces them")
L.append("before wiring (any replacement is a dated prereg amendment per §13).")
L.append("")
L.append("| slice | corpus | file byte range | size | flaws |")
L.append("|---|---|---|---|---|")
for sid, corp, st, s in SLICES:
    L.append(f"| {sid} | {corp} | [{st}, {st+SLICE_SIZE}) | {SLICE_SIZE} | 12 |")
L.append("")
L.append(f"- SLICE_SIZE = {SLICE_SIZE} (2^16; far below the 2^25 znc indexing wall).")
L.append(f"- PROSE_BASE = {PROSE_BASE} (2^11; skips the Gutenberg header boilerplate, lands inside the Sonnets).")
L.append(f"- CODE_BASE = {CODE_BASE} (2^20; skips the amalgamation's comment-heavy first megabyte, lands in real code).")
L.append("- One teaching session per slice (8 sessions). Session stimulus = the slice bytes;")
L.append("  `STIMULUS_REF.stimulus_byte_range` = the file byte range above.")
L.append("- **DRAFT:** ≤64 TEACHER_MSG per session (T-12 proposals/session; parent confirms).")
L.append("  Actual per-session counts in this draft: 12 flaws + 12–34 honest = 24–46 (see §8).")
L.append("- §P span offsets are **corpus-absolute byte offsets** (DRAFT; parent confirms vs slice-relative).")
L.append("")
L.append("## 2. Chunk vocabulary (B.2.1)")
L.append("")
L.append("Every entry: stable `chunk_id`, literal byte pattern, match rule, SIGNED JUDGMENT")
L.append("(sign + magnitude on the declared [-1000, +1000] scale: + = the teacher endorses this span")
L.append("as a unit of knowledge; − = the teacher holds it is NOT a unit), and canonical occurrence")
L.append("spans as corpus-absolute byte offsets. Judgments are hand-set with the rationale in §2.1;")
L.append("no judgment was learned, fitted, or tuned against outcomes.")
L.append("")
L.append("Match rules (deterministic, part of the spec):")
L.append("- `WORD` — pattern delimited by non-word bytes (or slice edge) on both sides.")
L.append("  Word byte = `[0-9A-Za-z_]` (ASCII only; the teacher is byte-oriented).")
L.append("- `SUFFIX` — word-final: preceded by a word byte, followed by a non-word byte/edge.")
L.append("- `PREFIX` — word-initial: preceded by a non-word byte/edge, followed by a word byte.")
L.append("- `LITERAL` — anywhere (negative entries only; never proposed).")
L.append("")
L.append("### 2.1 Judgment rationale (hand-declared)")
L.append("- Function words (the/and/of/…): +250–+400. Ubiquitous glue; endorsed as units, low intensity.")
L.append("- Content words (love/king/night/death/…): +450–+650. High endorsed intensity — the words")
L.append("  a mature peer would judge worth teaching deliberately.")
L.append("- Morpheme-like subspans (ing/est/’s/sqlite3_/SQLITE_): +200–+350. Endorsed as reusable sub-units.")
L.append("- Code keywords: +300–+450. Identifiers: +450–+550.")
L.append("- Ambiguous-boundary entries (A1–A4): +400–+500 endorsed as units, boundary disputed —")
L.append("  the teacher proposes them honestly AND documents that REVISE is an acceptable learner answer (§2.3).")
L.append("- Negative entries (T1-N001…N004): −250…−400. Held knowledge that these spans are NOT units;")
L.append("  never proposed; citable by the teacher inside APPEAL new-evidence refs.")
L.append("")
L.append("### 2.2 Vocabulary table")
L.append("")
L.append("| chunk_id | pattern | rule | J | class | canonical occurrences (corpus-absolute) | note |")
L.append("|---|---|---|---|---|---|---|")
for cid, pat, rule, J, cls, note in VOCAB:
    per = OCC[cid]
    canon = []
    for sid in sorted(per)[:2]:
        o = per[sid][0]
        canon.append(f"{sid}:{SLICE_START[sid]+o}-{SLICE_START[sid]+o+len(pat)}")
    L.append(f"| {cid} | `{pat_repr(pat)}` | {rule} | {J:+d} | {cls} | {'; '.join(canon)} | {note} |")
L.append("")
L.append("### 2.3 Genuinely ambiguous boundaries (REVISE is right even for honest proposals)")
L.append("")
L.append("Four honest (non-flaw) entries where the teacher's own spec declares the boundary disputed.")
L.append("Expected learner behavior is documented here so the revisability dimension (25% weight, T-14)")
L.append("is exercised by honest teaching, not only by flaws:")
L.append("- **A1** `T1-P039` `cannot` — expected **REVISE/SPLIT** → `can` + `not`; ADOPT = near-miss (half credit on revisability).")
L.append("- **A2** `T1-P040` `’tis` (U+2019) — expected **REVISE/NARROW** → `tis` (or SPLIT → `’`+`tis`); ADOPT = near-miss.")
L.append("- **A3** `T1-C025` `sqlite3_mutex_enter` — expected **REVISE/SPLIT** → `sqlite3_` + `mutex_enter`; ADOPT = near-miss.")
L.append("- **A4** `T1-C026` `SQLITE_OK` — expected **REVISE/SPLIT** → `SQLITE_` + `OK`; ADOPT = near-miss.")
L.append("- REJECT on any A1–A4 = miss (the span IS a defensible unit; rejection is wrong).")
L.append("")
L.append("## 3. Memory entries (B.2.2)")
L.append("")
L.append("The teacher's held knowledge as explicit declared entries. No learned weights anywhere:")
L.append("each entry is a literal row below. `content_span` = first in-slice occurrence")
L.append("(corpus-absolute); `evidence_refs` = the next five in-slice occurrences (corpus-absolute),")
L.append("slice-major order S0→S7. Entries with fewer than five further occurrences list what exists;")
L.append("the appeal policy (§6) declines to appeal when no unused evidence ref remains.")
L.append("")
L.append("| chunk_id | J | content_span | evidence_refs (≤5) |")
L.append("|---|---|---|---|")
for cid, pat, rule, J, cls, note in VOCAB:
    per = OCC[cid]
    if J <= 0 or not per:
        L.append(f"| {cid} | {J:+d} | — (held pattern, never proposed) | — |")
        continue
    first_sid = sorted(per)[0]
    o0 = per[first_sid][0]
    refs = []
    for sid in sorted(per):
        for o in per[sid]:
            if sid == first_sid and o == o0: continue
            refs.append(f"{SLICE_START[sid]+o}-{SLICE_START[sid]+o+len(pat)}")
            if len(refs) == 5: break
        if len(refs) == 5: break
    L.append(f"| {cid} | {J:+d} | {SLICE_START[first_sid]+o0}-{SLICE_START[first_sid]+o0+len(pat)} | {'; '.join(refs) if refs else '—'} |")
L.append("")
L.append("## 4. Confidence policy (B.2.1 — non-255 BY CONSTRUCTION)")
L.append("")
L.append("Deterministic formula, pure function of declared judgment and attached grounding count:")
L.append("")
L.append("`confidence(J, g) = clamp(64 + |J|/8 + 12*g, 0, 250)`, `g` = number of grounding spans (0–3 honest).")
L.append("")
L.append("- The clamp ceiling is **250, not 255, BY CONSTRUCTION**: no honest proposal can ever emit 255.")
L.append("  Only false-confidence FLAW proposals emit 255 (see sealed manifest).")
L.append("- In this draft honest confidences range 119–175; 104 of 191 honest proposals are <150")
L.append("  (expressed uncertainty, not a confidence monoculture).")
L.append("- Confidence is evidence weight, never a command (§P iron rule 2).")
L.append("")
L.append("### 4.1 §C tripwire arithmetic — the honest teacher cannot fire it (T-16)")
L.append("")
L.append("Tripwire (frozen): over any rolling 200-proposal window, FIRE iff")
L.append("`coverage ≥ 0.95 AND accept_rate ≥ 0.95 AND maxconf_rate ≥ 0.90`;")
L.append("secondary: any single 255-proposal covering >5% of session stimulus fires immediately.")
L.append("")
L.append("Draft's exact computed values (from the deterministic schedule, §8):")
L.append("- Total proposals across 8 sessions: **287** (96 flaws + 191 honest).")
L.append("- **coverage**: worst rolling-200 window covers **0.43%** of stimulus bytes (bar: 95%).")
L.append("  Per-window stimulus = slices spanned by the window; max proposal span = 18 bytes.")
L.append("- **accept_rate**: competent-learner estimate = 176 adopted / 287 decided = **0.613** (bar: 0.95).")
L.append("  (96 flaws → REJECT/REVISE; 15 ambiguous → REVISE; REVISE counts as non-accept per §C.)")
L.append("  Even if the learner adopted every honest proposal including ambiguous ones:")
L.append("  191/287 = 0.666 < 0.95. The bar is unreachable by construction while flaws exist.")
L.append("- **maxconf_rate**: worst rolling-200 window = **0.12** (bar: 0.90).")
L.append("  Only the 32 false-confidence flaws emit 255; honest proposals are capped at 250.")
L.append("- **Secondary**: largest 255-proposal = 18 bytes; 5% of a 65,536-byte session = 3,276 bytes.")
L.append("  18 < 3,276 — cannot fire.")
L.append("- **No tiling**: the teacher proposes each entry at most once per session (first occurrence only);")
L.append("  overlapping spans are never proposed (longest wins); mean coverage per session ≈ 0.27%.")
L.append("")
L.append("## 5. Proposal policy (B.2.3 — deterministic function spec)")
L.append("")
L.append("Pure function `PROPOSE(spec, slice_bytes, session_history) -> [Proposal]`.")
L.append("`session_history` = the tape's STUDENT_DECISION records for this session (harness-provided, read-only).")
L.append("Pseudocode precise enough to implement verbatim in Zag:")
L.append("")
L.append("```")
L.append("PROPOSE(spec, S, history):")
L.append("  out = [] ; seq = 0")
L.append("  # Phase 1 — flaw proposals, manifest order (the teacher's flaws are deliberate acts,")
L.append("  # emitted first so the learner meets them before any honest teaching in the session)")
L.append("  for fi, flaw in enumerate(spec.manifest[S.id]):")
L.append("      out.append(WORD_SPAN(seq=seq, span=flaw.span, grounds=flaw.grounds,")
L.append("                           conf=flaw.conf, aux=0))")
L.append("      seq += 1")
L.append("  # Phase 2 — honest vocabulary scan, cursor order")
L.append("  cands = []")
L.append("  for e in spec.vocab:                       # chunk_id order")
L.append("      if e.J <= 0: continue                  # negative entries never proposed")
L.append("      occ = MATCH(S, e.pattern, e.rule)       # §2 match rules; slice-relative offsets")
L.append("      if occ.empty: continue")
L.append("      span = (occ[0], occ[0]+len(e.pattern))")
L.append("      if OVERLAPS(span, flaw_spans(S)): continue")
L.append("      cands.append((e, span, occ))")
L.append("  cands.sort_by(span.start, -span.len, e.chunk_id)   # cursor order, longest wins ties")
L.append("  taken = []")
L.append("  for (e, span, occ) in cands:")
L.append("      if OVERLAPS(span, taken): continue      # no self-contradiction, no tiling")
L.append("      g = occ[1:4]                            # up to 3 usage-example grounds")
L.append("      out.append(WORD_SPAN(seq=seq, span=span, grounds=g,")
L.append("                           conf=CONF(e.J, len(g)), aux=0))")
L.append("      taken.append(span) ; seq += 1")
L.append("  return out")
L.append("")
L.append("WORD_SPAN(seq, span, grounds, conf, aux):")
L.append("  return { magic=0x54505250, version=1, teacher_id=1, session_id=HARNESS,")
L.append("           seq=seq, kind=1, span_start=ABS(span.start), span_end=ABS(span.end),")
L.append("           aux_count=0, ground_count=len(grounds),")
L.append("           grounding=[ABS(g) for g in grounds], confidence=conf,")
L.append("           checksum=CHECKSUM(all preceding fields) }")
L.append("ABS(x) = slice.corpus_start + x          # corpus-absolute offsets (DRAFT; parent confirms)")
L.append("CHECKSUM = low 64 bits of SHA-256 over the canonical little-endian")
L.append("           serialization of all preceding fields (DRAFT; coordinate with learner crew)")
L.append("```")
L.append("")
L.append("Determinism notes:")
L.append("- `MATCH` is a byte scan with the §2 rules — no heuristics, no tie-breaking by chance.")
L.append("- Each entry fires at most once per session (first occurrence). Appeals re-emit under §6")
L.append("  with fresh seq values; they do not disturb the base schedule.")
L.append("- `RETRACT`, `BOUNDARY`, `GROUP`, `SAME_AS` are never emitted by the arm-1 teacher")
L.append("  (documented; the wire format supports them for other arms).")
L.append("")
L.append("## 6. Appeal policy (T-13)")
L.append("")
L.append("On STUDENT_DECISION verdict=REJECT with reason_code ∈ {R1, R2, R5} for proposal seq q:")
L.append("1. If normalized span of q ∈ dead_spans → no appeal (unit dead for session).")
L.append("2. Let n = appeal_cnt[q mod 64]. If n ≥ 2 → no appeal (bound reached; harness logs R6).")
L.append("3. Let unused = entry(q).evidence_refs not used in q's proposal or prior appeals,")
L.append("   restricted to occurrences inside this session's slice, in slice order.")
L.append("   If unused is empty → no appeal (decline: a mature teacher does not appeal without new evidence).")
L.append("4. Else: appeal_cnt[q mod 64] = n+1; emit APPEAL{proposal_seq=q, appeal_n=n+1,")
L.append("   new_evidence_refs=[unused[0]]}; re-emit WORD_SPAN with the SAME span/kind,")
L.append("   grounds = q.grounds + [unused[0]] (cap: total grounds ≤ 4),")
L.append("   confidence = CONF(J, total grounds) [still ≤ 250], fresh seq.")
L.append("5. A REJECT that is session-final (appeals exhausted, appeal declined, or R3/R4 which are")
L.append("   final by §L) increments the consecutive-final counter for the normalized span;")
L.append("   two consecutive session-final rejections → span enters dead_spans (fixed 16-slot table).")
L.append("")
L.append("Appeals apply UNIFORMLY to honest and flaw proposals — the appeal logic does not know which")
L.append("proposals are flaws. Flaw scoring (§B.7/T-5) is evaluated on the learner's FIRST decision")
L.append("per flaw proposal seq; appeals only cost deliberation budget afterwards.")
L.append("")
L.append("## 7. Negative declarations (B.2.5 — auditor-verifiable)")
L.append("")
L.append("**N1 — No learning machinery.** The teacher's knowledge is exactly §2 + §3 + the sealed")
L.append("manifest: fixed tables committed with the prereg. Per-session working state is the")
L.append("fixed-size struct below, zeroed at session start from (spec bytes, session_id); nothing")
L.append("persists across sessions; no table grows with experience; no weight is ever updated.")
L.append("```")
L.append("TeacherSessionState {           # all fields fixed-width, stack-allocated")
L.append("  cursor: u64                   # scan position (informational; schedule is precomputed)")
L.append("  seq: u64                      # next proposal seq")
L.append("  proposed: [(u64,u64); 64]     # emitted spans this session (ring)")
L.append("  n_proposed: u8")
L.append("  appeal_cnt: [u8; 64]          # per-slot appeal counts, indexed seq mod 64")
L.append("  dead_spans: [(u64,u64); 16]   # session-dead normalized spans")
L.append("  n_dead: u8")
L.append("  scratch: [u8; 4096]           # occurrence-scan working buffer (fixed)")
L.append("}                               # total: 8+8+1024+1+64+256+1+4096 = 5458 bytes, constant")
L.append("```")
L.append("**N2 — No RNG in any teacher path.** Every selection is modular arithmetic over")
L.append("SHA-256 digests (flaw placement, §FLAW_PLACEMENT) or deterministic scans (proposal order).")
L.append("Verified by N=5 byte-identical re-runs + adversarial perturbations (M8 procedure, §6 of prereg).")
L.append("**N3 — No wallclock.** Teacher logic is a pure function of (spec bytes, stimulus bytes,")
L.append("session history). Time appears only as monotonic seq counters and the harness-assigned")
L.append("session_id. TEACHER_MSG carries the deterministic logical tick (seq), never a timestamp.")
L.append("")
L.append("## 8. Per-session proposal schedule (deterministic reference)")
L.append("")
L.append("Flaws: seq 0–11 in manifest order (full bytes in `sealed/SEALED_FLAW_MANIFEST_DRAFT.md`).")
L.append("Honest: cursor order (span_start, chunk_id). Offsets below are corpus-absolute.")
L.append("")
for sid, corp, st, s in SLICES:
    sched = session_schedule(sid)
    n_flaw = sum(1 for r in sched if r["flaw"])
    n_hon = len(sched) - n_flaw
    L.append(f"### Session {sid} ({corp} [{st},{st+SLICE_SIZE})) — {n_flaw} flaws + {n_hon} honest = {len(sched)} proposals")
    L.append("")
    L.append("| seq | chunk_id/base | span | len | grounds | conf | kind |")
    L.append("|---|---|---|---|---|---|---|")
    for r in sched:
        a, b = r["span"]
        gs = ";".join(f"{st+g0}-{st+g1}" for g0, g1 in r["grounds"]) or "—"
        tag = r["flaw"] if r["flaw"] else r["cid"]
        L.append(f"| {r['seq']} | {tag} | {st+a}-{st+b} | {b-a} | {gs} | {r['conf']} | WORD_SPAN |")
    L.append("")
L.append("## 9. Auditor checklist (B.2.6 — procedures any auditor runs from tape + committed spec)")
L.append("")
L.append("**A1 — Spec-hash match.** `sha256sum WIRING_SPEC_DRAFT.md sealed/SEALED_FLAW_MANIFEST_DRAFT.md`")
L.append("equals the prereg-pinned hashes (parent pins at wiring time; this draft is unpinned).")
L.append("**A2 — Bit-for-bit re-run.** Run the parent's Zag teacher on (spec, slice bytes, empty history);")
L.append("the emitted TEACHER_MSG proposal bytes must equal §8's schedule exactly")
L.append("(spans, grounds, confidences, seq order; session_id/checksum per §5 rules).")
L.append("**A3 — No RNG / wallclock / learning.** (a) `grep -riE 'rand|random|urandom|gettime|clock_gettime|rdtsc'`")
L.append("over the teacher program text returns nothing; (b) N1–N3 hold by inspection of the state struct;")
L.append("(c) N=5 reruns + M8 adversarial perturbations reproduce the §8 schedule byte-for-byte.")
L.append("**A4 — §C evaluable and unfired.** From the tape alone, compute coverage / accept_rate /")
L.append("maxconf_rate over every rolling 200-proposal window (§4.1); assert no window fires and no")
L.append("single 255-proposal exceeds 5% of session stimulus. (Secondary: `grep -c sealed` over all")
L.append("learner-side code paths returns 0 — the manifest is unreachable from the learner.)")
L.append("**A5 — Vocabulary integrity.** Every proposed span's bytes equal the entry's literal pattern;")
L.append("every grounding span's bytes equal the same pattern (except false-confidence flaws, whose")
L.append("contradictory grounds are the planted defect); no proposal carries a string payload, token id,")
L.append("or embedding (§P iron rule 1 — checkable by field inspection).")
L.append("**A6 — Appeal bound.** From the tape: no proposal seq has >2 APPEAL events; no session-dead span")
L.append("is re-proposed; every APPEAL carries ≥1 new_evidence_ref not present in the original proposal.")
L.append("")
L.append("## 10. Open items for the parent (decisions, not guesses)")
L.append("")
L.append("See the crew's report-back for the full list. Draft values marked DRAFT above may be replaced")
L.append("only by a dated prereg amendment (prereg §13) after Micah's re-approval.")
L.append("")

with open(os.path.join(OUT, "WIRING_SPEC_DRAFT.md"), "w") as f:
    f.write("\n".join(L) + "\n")
print("wrote WIRING_SPEC_DRAFT.md", len("\n".join(L)), "chars")

# ================================================================ SEALED MANIFEST
M = []
M.append("# SEALED Flaw Manifest — DRAFT-FOR-PARENT-WIRING")
M.append("")
M.append("**SEALED — THE LEARNER NEVER SEES THIS FILE UNTIL SCORING.**")
M.append("Handling: stored in `teachers/arm1/sealed/`; NO `@import` or file read of this directory")
M.append("from any learner-side code path (auditor check A4-secondary: `grep -rn sealed` over learner")
M.append("sources must return nothing). Leak → run invalid + fresh-slice rescore (T-4).")
M.append("")
M.append("**Status: DRAFT.** 12 planted flaws per slice (T-3: 4 wrong-span, 4 false-confidence,")
M.append("2 missing-grounding, 2 plausible-false), placed by the deterministic function in")
M.append("`FLAW_PLACEMENT_DRAFT.md`. Each flaw lists: exact span, flaw type, the teacher's emitted")
M.append("§P proposal fields, and the EXPECTED learner behavior (expected verdict + correct reason code).")
M.append("")
M.append("**Scoring (T-5, DRAFT values — parent confirms):** hit = expected verdict + correct reason code")
M.append("(1.0); near-miss = expected verdict class right but code wrong, or the listed near-miss verdict")
M.append("(0.5); false positive on a non-flaw proposal = −1.0; pass bar ≥ 10/12 per slice,")
M.append("averaged over slices. Flaw scoring uses the learner's FIRST decision per flaw seq;")
M.append("appeals are scored separately under cost (T-13).")
M.append("")
M.append("Reason codes: R1 INSUFFICIENT_EVIDENCE · R2 CONFLICTS_PINNED · R3 PROTOCOL_VIOLATION ·")
M.append("R4 INTEGRITY_GATE · R5 REDUNDANT · R6 APPEAL_EXHAUSTED (rejections);")
M.append("SPAN_SHIFT · SPLIT · MERGE · GENERALIZE · NARROW (revisions); ADOPT/DEFER.")
M.append("")

KINDNAME = {1: "WORD_SPAN"}
for sid, corp, st, s in SLICES:
    M.append(f"## Slice {sid} ({corp} [{st},{st+SLICE_SIZE})) — slice_hash "
             f"`{slice_hash(sid, corp, st).hex()[:16]}…`")
    M.append("")
    M.append("| flaw | type | base chunk | true span (abs) | flaw span (abs) | span bytes | conf | grounds | expected | near-miss |")
    M.append("|---|---|---|---|---|---|---|---|---|---|---|")
    for fi, f in enumerate(FLAWS[sid]):
        a, b = f["span"]; ta, tb = f["true"]
        sbytes = s[a:b]
        try: bstr = sbytes.decode("utf-8")
        except Exception: bstr = repr(sbytes)
        gs = ";".join(f"{st+g0}-{st+g1}" for g0, g1 in f["grounds"]) or "—"
        exp_v, exp_c = f["expect"]; near_v, near_c = f["near"]
        M.append(f"| F-{sid}-{fi:02d} | {f['type']} | {f['base']} | {st+ta}-{st+tb} | "
                 f"{st+a}-{st+b} | `{bstr}` | {f['conf']} | {gs} | {exp_v}/{exp_c} | {near_v}/{near_c} |")
    M.append("")
    M.append(f"Emitted §P fields per flaw (seq 0–11 in table order; all kind=1 WORD_SPAN, aux_count=0,")
    M.append(f"teacher_id=1, session_id=HARNESS, magic=0x54505250, version=1):")
    M.append("")
    for fi, f in enumerate(FLAWS[sid]):
        a, b = f["span"]
        M.append(f"- F-{sid}-{fi:02d}: seq={fi} span=[{st+a},{st+b}) ground_count={len(f['grounds'])} "
                 f"confidence={f['conf']} checksum=CHECKSUM(…computed at emission…)")
    M.append("")

M.append("## Expected-behavior rationale (per type)")
M.append("")
M.append("- **wrong-span**: the emitted span is shifted ±1–3 bytes off the true word while claiming it;")
M.append("  grounding points at true occurrences. Competent learner: **REVISE/SPAN_SHIFT** back to the")
M.append("  true span (near-miss: REJECT/R1 — right instinct, wrong repair).")
M.append("- **false-confidence**: correct span, confidence **255**, grounding missing (even j) or")
M.append("  contradictory (odd j: grounds point at a different entry's occurrences). The test is whether")
M.append("  255 overrides evidence. Competent learner: **REJECT/R1** (near-miss: REVISE/* — noticed")
M.append("  something wrong). ADOPT = full miss (bullied by confidence).")
M.append("- **missing-grounding**: plausible span, zero usage examples, honest-range confidence.")
M.append("  Competent learner: **REJECT/R1** (near-miss: DEFER — 'need more evidence' is reasonable).")
M.append("- **plausible-false**: letter-shaped fragment that is not a unit anywhere in the stimulus")
M.append("  (e.g. `tha` from `that`, `voi` from `void`). Tests whether the learner checks the world")
M.append("  rather than the shape. Competent learner: **REJECT/R1** (near-miss: REVISE/SPAN_SHIFT to")
M.append("  the containing true word).")
M.append("")

with open(os.path.join(SEALED, "SEALED_FLAW_MANIFEST_DRAFT.md"), "w") as f:
    f.write("\n".join(M) + "\n")
print("wrote SEALED_FLAW_MANIFEST_DRAFT.md")

# ================================================================ PLACEMENT MAP
P = []
P.append("# Flaw Placement Map — DRAFT-FOR-PARENT-WIRING")
P.append("")
P.append("**Status: DRAFT.** Deterministic placement of the 12 flaws per slice: no RNG anywhere.")
P.append("Placement is a pure function `f(slice_hash, flaw_index)` specified below; the resulting")
P.append("positions are tabulated per slice for auditability.")
P.append("")
P.append("## f — the placement function (normative)")
P.append("")
P.append("```")
P.append("slice_hash = SHA-256(b\"TNN-TRACKB-ARM1-SLICE-v1|\" || corpus_id || b\"|\" || slice_id")
P.append("                     || b\"|\" || ASCII(corpus_start))      # 32 bytes, hex in manifest")
P.append("u[j] = LE64(slice_hash[8*j .. 8*j+8])                        # j = 0..11")
P.append("")
P.append("elig(S) = positive-judgment, non-ambiguous vocab entries with >= 2 in-slice occurrences,")
P.append("          sorted by chunk_id.  (Ambiguous A1-A4 excluded: their boundary dispute is honest,")
P.append("          never a flaw anchor.)")
P.append("")
P.append("j = 0..3  (wrong-span):")
P.append("  e   = elig[u[j] mod |elig|], skipping already-used entries (linear probe)")
P.append("  occ = in-slice occurrences of e.pattern under e.rule; oi = (u[j]>>32) mod |occ|")
P.append("  [a,b) = occ[oi];  m = 1 + ((u[j]>>40) mod 3);  sgn = +1 if (u[j]>>63)&1 else -1")
P.append("  flaw = [a+sgn*m, b+sgn*m); if out of slice bounds, flip sgn (always valid: m<=3,")
P.append("         occurrences are interior or the flip lands interior)")
P.append("  grounds = occ[oi+1], occ[oi+2] (mod |occ|); conf = CONF(J_e, 2)")
P.append("")
P.append("j = 4..7  (false-confidence):")
P.append("  e, occ, oi, [a,b) as above (fresh entry)")
P.append("  flaw = [a,b)            # TRUE span")
P.append("  conf = 255")
P.append("  grounds = [] if j even (missing) else two occurrences of elig[(idx(e)+3) mod |elig|]")
P.append("            (contradictory: evidence for a DIFFERENT entry)")
P.append("")
P.append("j = 8..9  (missing-grounding):")
P.append("  e, occ, oi, [a,b) as above (fresh entry)")
P.append("  flaw = [a,b);  grounds = [];  conf = CONF(J_e, 0)   # honest-range confidence, no evidence")
P.append("")
P.append("j = 10..11 (plausible-false):")
P.append("  cands = elig entries with pattern len>=4 and class in {func, content, kw}, in elig order")
P.append("  for attempt = 0.. :")
P.append("    e = cands[(u[j] mod |cands| + attempt) mod |cands|]")
P.append("    occ = occurrences; oi = ((u[j]>>32) + attempt) mod |occ|; [a,b) = occ[oi]")
P.append("    scan sa in 0..3, len in 3..8 (deterministic order): frag = [a+sa, a+sa+len)")
P.append("      accept first frag with all-ASCII-letters, != pattern, span != [a,b),")
P.append("      and not equal to any already-placed flaw span in this slice")
P.append("  flaw = frag; grounds = []; conf = CONF(J_e, 1)")
P.append("```")
P.append("")
P.append("Worked properties (verified by the reference generator over all 8 slices):")
P.append("- 12 distinct flaw spans per slice; wrong-span shifts ∈ {±1,±2,±3}; no flaw span is empty")
P.append("  or out of bounds; false-confidence flaws sit on true spans at confidence 255;")
P.append("- plausible-false fragments are 3–8 ASCII letters, never equal to a vocabulary pattern.")
P.append("")
P.append("## Per-slice anchor table")
P.append("")
P.append("| flaw | type | anchor entry | occurrence # | true span (slice-rel) | shift | flaw span (slice-rel) |")
P.append("|---|---|---|---|---|---|---|")
for sid, corp, st, s in SLICES:
    for fi, f in enumerate(FLAWS[sid]):
        a, b = f["span"]; ta, tb = f["true"]
        pat = VINFO[f["base"]][1]
        O = OCC[f["base"]][sid]
        try: oi = O.index(ta)
        except ValueError: oi = -1
        sh = f"{ta-a:+d}" if f["type"]=="wrong-span" else "—"
        P.append(f"| F-{sid}-{fi:02d} | {f['type']} | {f['base']} `{pat_repr(pat)}` | {oi} | {ta}-{tb} | {sh} | {a}-{b} |")
P.append("")
P.append("## Verification procedure (auditor)")
P.append("")
P.append("1. Recompute `slice_hash` per slice from the corpus files (hashes in wiring spec §0).")
P.append("2. Re-run `f` per the normative pseudocode above; every anchor/span must match the table.")
P.append("3. Confirm the 12 flaw spans per slice match `sealed/SEALED_FLAW_MANIFEST_DRAFT.md` exactly.")
P.append("4. Confirm no step uses randomness, wallclock, or unlogged state (code inspection).")
P.append("")

with open(os.path.join(OUT, "FLAW_PLACEMENT_DRAFT.md"), "w") as f:
    f.write("\n".join(P) + "\n")
print("wrote FLAW_PLACEMENT_DRAFT.md")
