#!/usr/bin/env python3
"""Convert stores/*.tsv to k_tables.zag (Zag string-literal tables).

Validates: field counts, lowercase ASCII, sorted, deduplicated, no tabs in
fields, no joke-like content markers. Emits one fn per store:
  k_pun_table(), k_idiom_table(), k_world_table(), k_phon_table()

Tier subsetting: --tier N/D keeps every (D/N)-th entry by deterministic
interleave (0=all). Because stores are alphabetically sorted, interleaving
preserves breadth (no handpicking around test items).

Usage: tsv2zag.py --tier 1/4 --out k_tables.zag stores/*.tsv
"""
import sys, argparse

STORES = {
    "pun.tsv":   ("k_pun_table", 4),
    "idiom.tsv": ("k_idiom_table", 3),
    "world.tsv": ("k_world_table", 4),
    "phon.tsv":  ("k_phon_table", 4),
}

def zag_escape(s: str) -> str:
    # Escape for a Zag string literal. NOTE (AGENTS.md znc lesson): the
    # runtime string is the UNESCAPED bytes; escape only for the literal.
    out = []
    for ch in s:
        if ch == "\\": out.append("\\\\")
        elif ch == '"': out.append('\\"')
        elif ch == "\t": out.append("\\t")
        elif ch == "\n": out.append("\\n")
        else: out.append(ch)
    return "".join(out)

def load(path, expect_fields):
    recs = []
    with open(path, encoding="utf-8") as f:
        for ln, line in enumerate(f, 1):
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            assert "\t" in line, f"{path}:{ln}: no tab"
            fields = line.split("\t")
            assert len(fields) == expect_fields, \
                f"{path}:{ln}: {len(fields)} fields, want {expect_fields}"
            for fi, fld in enumerate(fields):
                assert fld == fld.strip(), f"{path}:{ln}: leading/trailing space"
                # lowercase enforced on MATCHABLE fields only; the gloss
                # (last field) is audit-only and carries A=/B=/fig=/lit=/
                # fact=/sounds like markers.
                if fi < len(fields) - 1:
                    assert fld == fld.lower(), f"{path}:{ln}: not lowercase: {fld!r}"
                for ch in fld:
                    assert 32 <= ord(ch) < 127, f"{path}:{ln}: non-ASCII {ch!r}"
            recs.append(line)
    # sorted by first field
    keys = [r.split("\t")[0] for r in recs]
    assert keys == sorted(keys), f"{path}: not sorted"
    assert len(set(keys)) == len(keys), f"{path}: duplicate keys"
    return recs

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tier", default="1/1",
                    help="N/D interleave subset, e.g. 1/4 (default 1/1=all)")
    ap.add_argument("--out", required=True)
    ap.add_argument("tsvs", nargs="+")
    a = ap.parse_args()
    num, den = (int(x) for x in a.tier.split("/"))
    assert 1 <= num <= den

    fns = []
    for tsv in a.tsvs:
        name = tsv.rsplit("/", 1)[-1]
        fn, nf = STORES[name]
        recs = load(tsv, nf)
        # deterministic interleave: indices num-1, num-1+den, ...
        if not (num == 1 and den == 1):
            recs = [r for i, r in enumerate(recs) if i % den == num - 1]
        body = "".join(zag_escape(r) + "\\n" for r in recs)
        fns.append(f'fn {fn}() []u8 {{\n    return "{body}";\n}}')
        print(f"{name}: {len(recs)} entries (tier {a.tier})")

    with open(a.out, "w", encoding="utf-8") as f:
        f.write("// k_tables.zag — GENERATED by tsv2zag.py; do not hand-edit.\n")
        f.write(f"// tier={a.tier}\n\n")
        f.write("\n\n".join(fns) + "\n")
    print("wrote", a.out)

main()
