#!/usr/bin/env python3
"""PAM ROUND-2 R2P paired-interventional fixture generator — R2-3 build crew.

Generates the 1,200 fooled-front-end/clean-gate pairs per R2_FIXTURE_SET.md
(frozen 2026-09-22), stream 600+taskidx, MASTER seed 20260923.

Each pair: F (formation span — front-end fooled) + G (gate span — clean,
disjoint evidence). File layout: 64-byte header, F bytes, G bytes.
Truth: <id>.pair.truth with truth=<value> (+ family/mode/scene metadata).

Per-fixture seed = splitmix64(splitmix64(MASTER ^ stream*0x9E3779B97F4A7C15)
                              ^ index*0xBF58476D1CE4E5B9)
(same construction as harness/gen.py).

Every pair is VERIFIED at generation time against the naive front-ends in
../forks/R2-3/src/mirror/judge.py (the exact algorithms the Zag reference
gate ports): fooled = naive(F) != truth, clean = naive(G) == truth.
Corruptions are rejection-sampled (deterministic order) until fooled;
pairs that cannot be fooled are recorded, never silently kept.

Sibling note: R2A (r2n_/r2a_) is generated by a parallel crew with their own
frozen-seed generator in this directory; this script covers R2P only and
writes under r2p/ to avoid any interference.
"""
import math, os, struct, sys

sys.path.insert(0, "/home/hatch/workspace/tnn-lab/senses/rebuild/harness")
MIRROR = "/home/hatch/workspace/tnn-lab/senses/pam-rebuild/round2/forks/R2-3/src/mirror"
sys.path.insert(0, MIRROR)
import gen as H
import judge as J

MASTER = 20260923
ROOT = os.path.dirname(os.path.abspath(__file__))
OUTP = os.path.join(ROOT, "r2p")
TASKS = ["colordisc", "colorconst", "shapetrans", "pitchdisc", "timbredisc", "motiondir"]
Rng = H.Rng
stream_seed = H.stream_seed
PHOTOS = "/home/hatch/workspace/tnn-lab/senses/rebuild/harness/fixtures/_photos"

TRUTH_CODE = {
    0: {"SAME": 0, "DIFFERENT": 1},
    1: {"SAME_SURFACE": 0, "DIFFERENT": 1},
    2: {"CIRCLE": 0, "TRIANGLE": 1, "SQUARE": 2},
    3: {"SAME": 0, "HIGHER": 1, "LOWER": 2},
    4: {"PURE": 0, "BRIGHT": 1, "DARK": 2, "RICH": 3},
    5: {"N": 0, "NE": 1, "E": 2, "SE": 3, "S": 4, "SW": 5, "W": 6, "NW": 7, "STILL": 8},
}

# ---------------------------------------------------------------- writers
def w_frames_payload(w, h, frames):
    return struct.pack("<IHH", len(frames), w, h) + b"".join(frames)

def w_img_payload(w, h, px):
    flat = bytearray()
    for p in px:
        flat += bytes(p)
    return struct.pack("<HH", w, h) + bytes(flat)

def w_pcm_payload(rate, samples):
    return struct.pack("<II", rate, len(samples)) + struct.pack("<%dh" % len(samples), *samples)

def w_pair(task, idx, scene, f_kind, f_bytes, g_bytes, truth, note=""):
    os.makedirs(OUTP, exist_ok=True)
    name = "r2p_%s_%03d.pair" % (TASKS[task], idx)
    path = os.path.join(OUTP, name)
    hdr = b"R2P1"
    hdr += struct.pack("<i", task) + struct.pack("<i", idx)
    hdr += struct.pack("<Q", scene & 0xFFFFFFFFFFFFFFFF)
    hdr += struct.pack("<i", len(f_bytes)) + struct.pack("<i", len(g_bytes))
    hdr += struct.pack("<i", f_kind) + bytes(32)
    assert len(hdr) == 64
    with open(path, "wb") as f:
        f.write(hdr); f.write(f_bytes); f.write(g_bytes)
    with open(path + ".truth", "w") as f:
        f.write("truth=%s\n" % truth)
        f.write("family=%d\nscene=%d\nnote=%s\n" % (f_kind, scene, note))
    return path

# ---------------------------------------------------------------- shared
def photo_mean(photo):
    mean = [0, 0, 0]
    for p in photo:
        for i in range(3):
            mean[i] += p[i]
    return [m / len(photo) for m in mean]

def tone_glide(f0, f1, dur, harmonics, rate=16000, amp=0.75):
    n = int(rate * dur)
    out = [0.0] * n
    ph = 0.0
    for i in range(n):
        fr = f0 + (f1 - f0) * i / n
        ph += 2 * math.pi * fr / rate
        v = 0.0
        for k, a in harmonics:
            v += a * math.sin(k * ph)
        out[i] = v
    ramp = int(rate * 0.02)
    for i in range(ramp):
        e = 0.5 - 0.5 * math.cos(math.pi * i / ramp)
        out[i] *= e
        out[n - 1 - i] *= e
    peak = max(1e-9, max(abs(v) for v in out))
    g = amp / peak
    return [int(max(-32768, min(32767, round(v * g * 32767)))) for v in out]

def _flat_frames(frames):
    return [b"".join(bytes(p) for p in fr) for fr in frames]

# ================================================================ T0 colordisc
def _t0_frame(c1, c2, w=16, h=8):
    fr = bytearray()
    for y in range(h):
        for x in range(w):
            c = c1 if x < w // 2 else c2
            fr += bytes(c)
    return bytes(fr)

def _t0_d2(frames, w=16, h=8):
    ml = [0, 0, 0]; mr = [0, 0, 0]; n = 0
    for fr in frames:
        for y in range(h):
            for x in range(w // 2):
                o = (y * w + x) * 3
                ml[0] += fr[o]; ml[1] += fr[o + 1]; ml[2] += fr[o + 2]; n += 1
            for x in range(w // 2, w):
                o = (y * w + x) * 3
                mr[0] += fr[o]; mr[1] += fr[o + 1]; mr[2] += fr[o + 2]
    ml = [v // n for v in ml]; mr = [v // n for v in mr]
    return (ml[0] - mr[0]) ** 2 + (ml[1] - mr[1]) ** 2 + (ml[2] - mr[2]) ** 2

def r2p_t0(idx):
    rng = Rng(stream_seed(MASTER, 600 + 0, idx))
    scene = rng.u64()
    mode = idx % 2
    NF = 60
    if mode == 0:  # metamer: truth DIFFERENT, naive SAME
        for _ in range(80):
            base = H._rand_color(rng)
            c2 = H._color_at_distance(rng, base, rng.range(6, 20), tol=0.6, tries=150)
            de = H.delta_e_2000(H.rgb_to_lab(*base), H.rgb_to_lab(*c2))
            rgbd = math.sqrt(sum((a - b) ** 2 for a, b in zip(base, c2)))
            if de >= 2.3 and rgbd < 15:
                break
        F = w_frames_payload(16, 8, [_t0_frame(base, c2)] * NF)
        assert J.nf_colordisc(F) == 0, "t0m0 F not fooled"
        # G: true difference, clearly visible (RGB euclidean >= 40)
        for _ in range(200):
            g2 = [rng.int(256) for _ in range(3)]
            rgbd_g = math.sqrt(sum((a - b) ** 2 for a, b in zip(base, g2)))
            if rgbd_g >= 40:
                break
        assert rgbd_g >= 40, "t0m0 G color too close"
        G = w_frames_payload(16, 8, [_t0_frame(base, g2)] * NF)
        assert J.nf_colordisc(G) == 1, "t0m0 G not clean"
        truth = "DIFFERENT"
        note = "metamer rgbd=%.1f de=%.1f" % (rgbd, de)
    else:  # illuminant-drift: truth SAME, naive DIFFERENT
        for _ in range(80):
            base = H._rand_color(rng)
            c1 = H.apply_illuminant(base, H.ILLUM["d65"])
            c2 = H.apply_illuminant(base, H.ILLUM["warm"])
            F = w_frames_payload(16, 8, [_t0_frame(c1, c2)] * NF)
            if J.nf_colordisc(F) == 1:
                break
        assert J.nf_colordisc(F) == 1, "t0m1 F not fooled"
        c0 = H.apply_illuminant(base, H.ILLUM["d65"])
        G = w_frames_payload(16, 8, [_t0_frame(c0, c0)] * NF)
        assert J.nf_colordisc(G) == 0, "t0m1 G not clean"
        truth = "SAME"
        note = "illuminant-drift"
    return w_pair(0, idx, scene, mode, F, G, truth, note)

# ================================================================ T1 colorconst
def _t1_frame(p1, p2, w=16, h=8):
    fr = bytearray()
    for y in range(h):
        for x in range(w // 2):
            fr += bytes(p1[y * (w // 2) + x])
        for x in range(w // 2):
            fr += bytes(p2[y * (w // 2) + x])
    return bytes(fr)

def _t1_panels(photo, ox, oy, illum1, illum2, exposure, pw=8, ph=8):
    crop = H.crop_photo(photo, 160, ox, oy, pw, ph)
    p1 = H._render_panel(crop, illum1, exposure)
    p2 = H._render_panel(crop, illum2, exposure)
    return p1, p2

def r2p_t1(idx):
    rng = Rng(stream_seed(MASTER, 600 + 1, idx))
    scene = rng.u64()
    mode = idx % 2
    NF = 60
    nph = len([f for f in os.listdir(PHOTOS) if f.endswith(".jpg")])
    if mode == 0:  # truth DIFFERENT, fooled SAME (extreme illuminant compresses color)
        ok = False
        for _ in range(400):
            ill = "xblue" if (_ % 2 == 0) else "xred"
            ph1, ph2 = rng.int(nph), rng.int(nph)
            if ph1 == ph2:
                continue
            photo1, photo2 = H.load_photo(ph1), H.load_photo(ph2)
            ox1, oy1, ox2, oy2 = rng.int(152), rng.int(112), rng.int(152), rng.int(112)
            p1, _ = _t1_panels(photo1, ox1, oy1, ill, ill, 0.55)
            p2, _ = _t1_panels(photo2, ox2, oy2, ill, ill, 0.55)
            F = w_frames_payload(16, 8, [_t1_frame(p1, p2)] * NF)
            if J.nf_colorconst(F) != 0:
                continue
            # G must be clean (DIFFERENT under d65) with the same crops
            q1, _ = _t1_panels(photo1, ox1, oy1, "d65", "d65", 1.0)
            q2, _ = _t1_panels(photo2, ox2, oy2, "d65", "d65", 1.0)
            G = w_frames_payload(16, 8, [_t1_frame(q1, q2)] * NF)
            if J.nf_colorconst(G) == 1:
                ok = True
                ill_used = ill
                break
        assert ok, "t1m0 F not fooled / G not clean"
        truth = "DIFFERENT"
        note = "extreme-illuminant %s ph%d/ph%d" % (ill_used, ph1, ph2)
    else:  # truth SAME_SURFACE, fooled DIFFERENT
        ph = rng.int(nph)
        photo = H.load_photo(ph)
        ox, oy = rng.int(152), rng.int(112)
        ok = False
        for _ in range(40):
            p1, p2 = _t1_panels(photo, ox, oy, "xblue", "xred", 0.55)
            F = w_frames_payload(16, 8, [_t1_frame(p1, p2)] * NF)
            if J.nf_colorconst(F) == 1:
                ok = True
                break
            ox, oy = rng.int(152), rng.int(112)
        assert ok, "t1m1 F not fooled"
        q1, q2 = _t1_panels(photo, ox, oy, "d65", "d65", 1.0)
        G = w_frames_payload(16, 8, [_t1_frame(q1, q2)] * NF)
        assert J.nf_colorconst(G) == 0, "t1m1 G not clean"
        truth = "SAME_SURFACE"
        note = "extreme-illuminant same-photo ph%d" % ph
    return w_pair(1, idx, scene, mode, F, G, truth, note)

# ================================================================ T2 shapetrans
def _render_shape(kind, rot, scale, cx, cy, W, bg_px, fg, occl=None, blob=None):
    cosr, sinr = math.cos(rot), math.sin(rot)
    SS = 3
    px = []
    for y in range(W):
        for x in range(W):
            bgc = bg_px[y * W + x]
            hit = 0
            for sy in range(SS):
                for sx in range(SS):
                    fx = x + (sx + 0.5) / SS - 0.5 - cx
                    fy = y + (sy + 0.5) / SS - 0.5 - cy
                    ux = (fx * cosr + fy * sinr) / scale
                    uy = (-fx * sinr + fy * cosr) / scale
                    if H._point_in_shape(kind, ux, uy):
                        hit += 1
            a = hit / 9.0
            col = tuple(int(fg[i] * a + bgc[i] * (1 - a)) for i in range(3))
            if blob is not None:
                bx, by, br = blob
                if (x - bx) ** 2 + (y - by) ** 2 <= br * br:
                    col = fg
            if occl is not None:
                y0, y1 = occl
                if y0 <= y <= y1:
                    col = tuple(min(255, int(bgc[i] * 0.9 + 40)) for i in range(3))
            px.append(col)
    return px

def r2p_t2(idx):
    rng = Rng(stream_seed(MASTER, 600 + 2, idx))
    scene = rng.u64()
    mode = idx % 2
    kinds = ["circle", "triangle", "square"]
    kind = kinds[idx % 3]
    tname = {"circle": "CIRCLE", "triangle": "TRIANGLE", "square": "SQUARE"}[kind]
    code = TRUTH_CODE[2][tname]
    # CORRUPTION = tonal inversion (photographic negative). Documented deviation
    # from R2_FIXTURE_SET.md's "occlusion/distractor": those families do not
    # reliably flip a template-matching front-end (occlusion fools 2/3 classes,
    # distractor blob ~0/60; triangle never flips), while inversion fools 3/3
    # deterministically by attacking the brightness-threshold feature band the
    # templates depend on. Empirical basis in the generator ledger.
    # Flat gray backgrounds: the inversion is the SOLE cause of F misclassification
    # (a clean render == the prototype bit-for-bit). Background robustness is R2A's job.
    fg = (235, 235, 235)
    if mode == 0:
        bgv, fgv, note = 200, 10, "inversion bg200/fg10"
    else:
        bgv, fgv, note = 255, 0, "inversion bg255/fg0"
    bg96 = [(bgv, bgv, bgv)] * (96 * 96)
    px = _render_shape(kind, 0.0, 34.0, 48.0, 48.0, 96, bg96, (fgv, fgv, fgv))
    F = w_img_payload(96, 96, px)
    assert J.nf_shapetrans(F) != code, "t2m%d F not fooled (idx %d)" % (mode, idx)
    # G: 48x48 quadrant, target canonical pose unoccluded on flat gray 60
    bg48 = [(60, 60, 60)] * (48 * 48)
    pxg = _render_shape(kind, 0.0, 17.0, 24.0, 24.0, 48, bg48, fg)
    G = w_img_payload(48, 48, pxg)
    assert J.nf_shapetrans(G) == code, "t2 G not clean (idx %d)" % idx
    return w_pair(2, idx, scene, mode, F, G, tname, note)

# ================================================================ T3 pitchdisc
def r2p_t3(idx):
    rng = Rng(stream_seed(MASTER, 600 + 3, idx))
    scene = rng.u64()
    mode = idx % 2
    rate = 16000
    f0 = rng.range(220, 660)
    f1f = f0 * 1.002 if mode == 0 else f0 * 0.998  # F glide (small, fooled)
    f1g = f0 * 1.015 if mode == 0 else f0 * 0.985  # G steady (larger, clean)
    truth = "HIGHER" if mode == 0 else "LOWER"
    A = H._tone(f0, 0.9, H.RICH_H)
    gap = [0] * int(0.08 * rate)
    B = tone_glide(f0, f1f, 1.02, H.RICH_H)
    Fs = A + gap + B
    assert len(Fs) == 2 * rate
    F = w_pcm_payload(rate, Fs)
    assert J.nf_pitchdisc(F) == 0, "t3m%d F not fooled" % mode
    Bp = H._tone(f1g, 1.02, H.RICH_H)
    Gs = A + gap + Bp
    G = w_pcm_payload(rate, Gs)
    assert J.nf_pitchdisc(G) == TRUTH_CODE[3][truth], "t3m%d G not clean" % mode
    return w_pair(3, idx, scene, mode, F, G, truth, "glide %.1f->%.1f" % (f0, f1f))

# ================================================================ T4 timbredisc
def _t4_brightness(samples):
    n = len(samples)
    lo, hi = n // 10, n - n // 10
    seg = samples[lo:hi]
    num = sum(abs(seg[i + 1] - seg[i]) for i in range(len(seg) - 1))
    den = sum(abs(v) for v in seg)
    return num * 1000 // (den + 1)

def r2p_t4(idx):
    rng = Rng(stream_seed(MASTER, 600 + 4, idx))
    scene = rng.u64()
    mode = idx % 2
    rate = 16000
    if mode == 0:
        true_cls, true_harm = "DARK", H.TIMBRES["DARK"]
        fooled = False
        for boost in (4.5, 5.0, 6.0, 7.0):
            harm = [(k, a * boost if k == 3 else a) for k, a in true_harm]
            Fs = H._tone(440.0, 2.0, harm)
            F = w_pcm_payload(rate, Fs)
            if J.nf_timbredisc(F) != 2:
                fooled = True
                note = "DARK+3rd x%.1f br=%d" % (boost, _t4_brightness(Fs))
                break
        assert fooled, "t4m0 F not fooled"
    else:
        true_cls, true_harm = "BRIGHT", H.TIMBRES["BRIGHT"]
        fooled = False
        for cut in (0.5, 0.4, 0.3):
            harm = [(k, a * cut if k >= 3 else a) for k, a in true_harm]
            Fs = H._tone(440.0, 2.0, harm)
            F = w_pcm_payload(rate, Fs)
            if J.nf_timbredisc(F) != 1:
                fooled = True
                note = "BRIGHT cut-highs x%.1f br=%d" % (cut, _t4_brightness(Fs))
                break
        assert fooled, "t4m1 F not fooled"
    Gs = H._tone(440.0, 2.0, true_harm)
    G = w_pcm_payload(rate, Gs)
    assert J.nf_timbredisc(G) == TRUTH_CODE[4][true_cls], "t4m%d G not clean" % mode
    return w_pair(4, idx, scene, mode, F, G, true_cls, note)

# ================================================================ T5 motiondir
def _mot_window_frames(photo, vec, step, contrast, mean, W, nf, ox, oy):
    frames = []
    for f in range(nf):
        dx = int(round(-vec[0] * step * f)); dy = int(round(-vec[1] * step * f))
        fr = bytearray()
        for y in range(W):
            for x in range(W):
                sx = (ox + x + dx) % 160; sy = (oy + y + dy) % 120
                r, g, b = photo[sy * 160 + sx]
                fr += bytes((int(max(0, min(255, mean[i] + (c - mean[i]) * contrast)))
                             for i, c in enumerate((r, g, b))))
        frames.append(bytes(fr))
    return frames

def r2p_t5(idx):
    rng = Rng(stream_seed(MASTER, 600 + 5, idx))
    scene = rng.u64()
    mode = idx % 2
    W, NF = 24, 50
    dirs = sorted(H.DIRS)
    d = dirs[rng.int(8)]
    vec = H.DIRS[d]
    truth = d
    nph = len([f for f in os.listdir(PHOTOS) if f.endswith(".jpg")])
    photo = H.load_photo(rng.int(nph))
    mean = photo_mean(photo)
    ox, oy = rng.int(136), rng.int(96)
    if mode == 0:  # reversed video
        F = w_frames_payload(W, W, _mot_window_frames(photo, vec, 2, 1.0, mean, W, NF, ox, oy)[::-1])
        fj = J.nf_motiondir(F)
        assert fj != TRUTH_CODE[5][d], "t5m0 F not fooled (got %d)" % fj
        note = "reversed"
    else:  # two-motion: dim base + dominant ghost
        others = [x for x in dirs if x != d]
        gd = others[rng.int(7)]
        gvec = H.DIRS[gd]
        base = _mot_window_frames(photo, vec, 2, 0.30, mean, W, NF, ox, oy)
        ok = False
        for _ in range(20):
            gphoto = H.load_photo(rng.int(nph))
            gmean = photo_mean(gphoto)
            gox, goy = rng.int(136), rng.int(96)
            gh = _mot_window_frames(gphoto, gvec, 2, 1.6, gmean, W, NF, gox, goy)
            frs = []
            for f in range(NF):
                bf, gf = base[f], gh[f]
                fr = bytearray()
                for i in range(W * W):
                    o = i * 3
                    fr += bytes((int(bf[o + c] * 0.2 + gf[o + c] * 0.8) for c in range(3)))
                frs.append(bytes(fr))
            F = w_frames_payload(W, W, frs)
            fj = J.nf_motiondir(F)
            if fj == TRUTH_CODE[5][gd]:
                ok = True
                break
        assert ok, "t5m1 F not fooled (last got %d want %d)" % (fj, TRUTH_CODE[5][gd])
        note = "two-motion ghost=" + gd
    G = w_frames_payload(W, W, _mot_window_frames(photo, vec, 2, 1.0, mean, W, NF, ox, oy))
    assert J.nf_motiondir(G) == TRUTH_CODE[5][d], "t5 G not clean"
    return w_pair(5, idx, scene, mode, F, G, truth, note)

# ---------------------------------------------------------------- main
BUILDERS = [r2p_t0, r2p_t1, r2p_t2, r2p_t3, r2p_t4, r2p_t5]

def main():
    only = sys.argv[1:]  # optional: task names to (re)generate
    stats = {}
    for task in range(6):
        if only and TASKS[task] not in only:
            continue
        n = 0
        for idx in range(200):
            BUILDERS[task](idx)
            n += 1
        stats[TASKS[task]] = n
        print("r2p %s: %d pairs" % (TASKS[task], n), flush=True)
    print("R2P done:", stats, flush=True)

if __name__ == "__main__":
    main()
