#!/usr/bin/env python3
"""Extract byte-identical mode-35 mechanism functions from the REPAIRED probe.

Source: hpam3536_r35.zag (R-35 repair of hpam3536_probe.zag @ b20ae9edf87da4aa).
The repaired probe file is NEVER modified. Drivers @import the extracted
copies; verify_copies.sh re-runs this extraction and diffs, proving identity.
Same boundary-extraction pattern as RT-JKLM's extract_copies.py.
"""
import sys, hashlib, re

SRC = sys.argv[1]
OUT = sys.argv[2]

WANT = [
    ("struct", "LowVal"), ("struct", "HighVal"), ("struct", "LowVec"),
    ("struct", "HighVec"), ("struct", "LowKey"), ("struct", "HighKey"),
    ("fn", "fnv32"), ("fn", "put32i"), ("fn", "put32u"), ("fn", "put64i"),
    ("fn", "get32i"),
    ("fn", "tag_half"), ("fn", "verify_high"), ("fn", "declassify"),
    ("fn", "act_sink"), ("fn", "premise_sink"), ("fn", "oracle"),
    ("fn", "mean8"), ("fn", "cache_put"), ("fn", "cache_get"),
    ("fn", "emb"), ("fn", "vec_uplift"), ("fn", "vec_tag_half"),
    ("fn", "decide_high"), ("fn", "retrkey"), ("fn", "key_uplift"),
    ("fn", "premise_keyed"), ("fn", "summarize"),
    ("fn", "adv_low"), ("fn", "forge"),
]

def is_boundary(line):
    s = line.strip()
    if s.startswith("fn ") or s.startswith("struct ") or s.startswith("const "):
        return True
    if s.startswith("//") and ("===" in s or "---" in s):
        return True
    return False

def extract(lines, kind, name):
    start = None
    for i, ln in enumerate(lines):
        if ln.startswith(kind + " " + name) and (
            ln[len(kind)+1+len(name):len(kind)+2+len(name)] in (" ", "{", "(")):
            start = i
            break
    assert start is not None, f"not found: {kind} {name}"
    end = len(lines)
    for j in range(start + 1, len(lines)):
        if is_boundary(lines[j]):
            end = j
            break
    while end > start + 1 and lines[end-1].strip() == "":
        end -= 1
    return lines[start:end]

def main():
    with open(SRC) as f:
        lines = f.read().split("\n")
    out = []
    out.append("// VERIFIED COPY — extracted from the R-35 repaired probe hpam3536_r35.zag")
    out.append("// (repair of hpam3536_probe.zag @ b20ae9edf87da4aa: full-64-bit tag binding)")
    out.append("// DO NOT EDIT. Regenerated by extract_r35.py; verify_copies.sh checks identity.")
    out.append("")
    for kind, name in WANT:
        out.extend(extract(lines, kind, name))
        out.append("")
    text = "\n".join(out)
    stripped = "\n".join(ln.split("//")[0] for ln in text.split("\n"))
    defined = set(n for k, n in WANT)
    builtins = {"nio_alloc","nio_free","_zag_slice_ptr","_zag_raw_syscall",
                "_zag_i64_to_str","_zag_arg","_zag_strcmp","_zag_malloc","_zag_free"}
    called = set(re.findall(r'\b([a-z_][a-z0-9_]*)\s*\(', stripped))
    keywords = {"if","while","return","fn","struct","let"}
    missing = called - defined - builtins - keywords
    assert not missing, f"missing deps in copy35_r35: {missing}"
    with open(OUT, "w") as f:
        f.write(text)
    h = hashlib.sha256(text.encode()).hexdigest()
    print(f"copy35_r35.zag: {len(out)} lines, sha256={h}")

main()
