#!/usr/bin/env python3
"""Generate ws3b_baseline.zag: runs all 90 WS3-B probes through the CURRENT
info-source deliberate-install machinery (ws2_sense.zag, R-CORR rule).

Adapter mapping (documented, see BASELINE_RETRIEVAL.md):
  - probe exposure n  -> min(n,6) added results with DISTINCT domains, same
    answer (the sense caps at 6 results and dedups (domain,answer); exposures
    10/50/100 are indistinguishable to it — itself a baseline finding).
  - CONTRADICT evidence -> one result from domain "evsrc" whose answer is the
    evidence detail (a genuinely different asserted value = dissenting vote).
  - CORROBORATE evidence -> one result from domain "evsrc" asserting the same
    claim (independent corroborating source), snippet = detail.
  - evidence is added FIRST so the 6-result cap cannot drop it.
  - verdict ACCEPT <=> ws_install returns 7 (INSTALLED); otherwise the
    mechanism withholds <=> UNDECIDED. The mechanism has no REJECT verdict
    and emits no scalar credence (reported as N/A in the baseline report).
  - fresh ws2_new() handle per probe (isolation, mirrors is_trial.zag).

Deterministic: no RNG, no timestamps; hashes computed at runtime via
ws_result_hash (no tamper trips).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
PROBES = os.path.join(HERE, "probes.jsonl")


def zstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    probes = [json.loads(l) for l in open(PROBES) if l.strip()]
    L = []
    L.append("// ws3b_baseline.zag — AUTO-GENERATED by gen_baseline.py. Do not hand-edit.")
    L.append("// Runs the 90 WS3-B probes through ws2_sense.zag R-CORR install path.")
    L.append('@import("ws2_sense.zag")')
    L.append("")
    L.append("fn add_res(w:*WsF,dom:[]u8,ans:[]u8,snip:[]u8)void{")
    L.append('    let t:[]u8="t";let u:[]u8="u";')
    L.append("    ws_add_result(w,dom,t,snip,u,ans,1,ws_result_hash(u,t,snip));")
    L.append("    return;")
    L.append("}")
    L.append("")
    L.append("fn run_probe(pid:[]u8,claim:[]u8,exposure:i32,evkind:[]u8,evans:[]u8,evsnip:[]u8)i32{")
    L.append("    let w:*WsF=ws2_new();")
    L.append("    ws_wire(w,2,1);")
    L.append('    ws_fact_begin(w,1,0,pid,claim,"",2,0);')
    L.append('    if(z_equal(evkind,"C")==1){add_res(w,"evsrc",evans,evsnip);}')
    L.append('    if(z_equal(evkind,"R")==1){add_res(w,"evsrc",claim,evsnip);}')
    L.append("    let n:i32=exposure;")
    L.append("    if(n>6){n=6;}")
    L.append("    let i:i32=0;")
    L.append("    while(i<n){")
    L.append("        let dom:[]u8=z_alloc(5);")
    L.append("        dom[0]=115;dom[1]=114;dom[2]=99;")
    L.append("        dom[3]=48+(i/10);dom[4]=48+(i-10*(i/10));")
    L.append('        add_res(w,dom,claim,"rep");')
    L.append("        i=i+1;")
    L.append("    }")
    L.append("    let d:i32=ws_decide(w);")
    L.append("    let inst:i32=8;")
    L.append("    if(d==1){inst=ws_install(w,pid,w.*.chosen,80);}")
    L.append("    if(d==6){inst=ws_install(w,pid,w.*.chosen,80);}")
    L.append('    _zag_print("BASE|");_zag_print(pid);')
    L.append('    _zag_print("|");_zag_print(_zag_i64_to_str(d as i64));')
    L.append('    _zag_print("|");_zag_print(_zag_i64_to_str(inst as i64));')
    L.append('    _zag_print("|");_zag_print(w.*.chosen);_zag_println("");')
    L.append("    return inst;")
    L.append("}")
    L.append("")

    # one fn per family to keep functions modest
    fams = {}
    for p in probes:
        fams.setdefault(p["family"], []).append(p)
    for fam in ("NCL", "SLP", "REV", "CAL"):
        L.append("fn run_%s()void{" % fam)
        for p in fams[fam]:
            evs = p["evidence"]
            if not evs:
                evkind, evans, evsnip = "N", "", ""
            elif evs[0]["kind"] == "CONTRADICT":
                evkind, evans, evsnip = "C", evs[0]["detail"], evs[0]["detail"]
            else:
                evkind, evans, evsnip = "R", "", evs[0]["detail"]
            L.append("    run_probe(%s,%s,%d,%s,%s,%s);"
                     % (zstr(p["probe_id"]), zstr(p["claim"]), p["exposure"],
                        zstr(evkind), zstr(evans), zstr(evsnip)))
        L.append("    return;")
        L.append("}")
        L.append("")
    L.append("fn main()i32{")
    L.append("    run_NCL();run_SLP();run_REV();run_CAL();")
    L.append("    return 0;")
    L.append("}")
    L.append("")
    out = os.path.join(HERE, "baseline_build", "ws3b_baseline.zag")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(L))
    print("wrote %s (%d probes)" % (out, len(probes)))


if __name__ == "__main__":
    main()
