#!/usr/bin/env python3
"""Extract byte-identical mechanism functions from the committed H-PAM-35/36 probe.

Source: hpam3536_probe.zag @ 8d16d9f3 (SHA-256 pinned in PREREG_RT_JKLM.md).
The probe file is NEVER modified. Drivers @import the extracted copies;
verify_copies.sh re-runs this extraction and diffs, proving identity.
"""
import sys, hashlib

SRC = sys.argv[1]          # path to committed hpam3536_probe.zag
WHICH = sys.argv[2]        # "35" or "36"
OUT = sys.argv[3]

WANT_35 = [
    ("struct", "LowVal"), ("struct", "HighVal"), ("struct", "LowVec"),
    ("struct", "HighVec"), ("struct", "LowKey"), ("struct", "HighKey"),
    ("fn", "fnv32"), ("fn", "put32i"), ("fn", "put32u"), ("fn", "get32i"),
    ("fn", "tag_half"), ("fn", "verify_high"), ("fn", "declassify"),
    ("fn", "act_sink"), ("fn", "premise_sink"), ("fn", "oracle"),
    ("fn", "mean8"), ("fn", "cache_put"), ("fn", "cache_get"),
    ("fn", "emb"), ("fn", "vec_uplift"), ("fn", "vec_tag_half"),
    ("fn", "decide_high"), ("fn", "retrkey"), ("fn", "key_uplift"),
    ("fn", "premise_keyed"), ("fn", "summarize"),
    ("fn", "adv_low"), ("fn", "forge"),
]
WANT_36 = [
    ("fn", "fnv32"), ("fn", "put32i"), ("fn", "put32u"),
    ("fn", "wstep"), ("fn", "honest_wc"), ("fn", "honest_wm"),
    ("fn", "cstep"), ("fn", "admit36"),
    ("fn", "adv36_conf"), ("fn", "adv36_meas"),
]

def is_boundary(line):
    s = line.strip()
    if s.startswith("fn ") or s.startswith("struct ") or s.startswith("const "):
        return True
    if s.startswith("//") and ("===" in s or "---" in s):
        return True
    return False

def extract(lines, kind, name):
    start = None
    for i, ln in enumerate(lines):
        if ln.startswith(kind + " " + name) and (
            ln[len(kind)+1+len(name):len(kind)+2+len(name)] in (" ", "{", "(")):
            start = i
            break
    assert start is not None, f"not found: {kind} {name}"
    end = len(lines)
    for j in range(start + 1, len(lines)):
        if is_boundary(lines[j]):
            end = j
            break
    # trim trailing blank lines
    while end > start + 1 and lines[end-1].strip() == "":
        end -= 1
    return lines[start:end]

def main():
    with open(SRC) as f:
        lines = f.read().split("\n")
    want = WANT_35 if WHICH == "35" else WANT_36
    out = []
    out.append("// VERIFIED COPY — extracted from committed hpam3536_probe.zag @ 8d16d9f3")
    out.append("// DO NOT EDIT. Regenerated by extract_copies.py; verify_copies.sh checks identity.")
    out.append("")
    for kind, name in want:
        block = extract(lines, kind, name)
        out.extend(block)
        out.append("")
    # dependency closure self-check: every identifier called must be defined
    # in the copy or be a builtin/keyword
    text = "\n".join(out)
    # strip // comments before the dependency scan
    stripped = "\n".join(ln.split("//")[0] for ln in text.split("\n"))
    defined = set(n for k, n in want)
    builtins = {"nio_alloc","nio_free","_zag_slice_ptr","_zag_raw_syscall",
                "_zag_i64_to_str","_zag_arg","_zag_strcmp","_zag_malloc","_zag_free"}
    import re
    called = set(re.findall(r'\b([a-z_][a-z0-9_]*)\s*\(', stripped))
    keywords = {"if","while","return","fn","struct","let"}
    missing = called - defined - builtins - keywords
    assert not missing, f"missing deps in copy{WHICH}: {missing}"
    with open(OUT, "w") as f:
        f.write("\n".join(out))
    h = hashlib.sha256("\n".join(out).encode()).hexdigest()
    print(f"copy{WHICH}.zag: {len(out)} lines, sha256={h}")

main()
