#!/usr/bin/env python3
"""extract_b3536.py — build the B-3536 composition library by SCRIPT EXTRACTION.

Sources (committed, never retyped):
  H-35 repaired mechanisms: git show 1fa4ae58:docs/lab/senses/pam-rebuild/round2/r35/hpam3536_r35.zag
  H-36 repaired mechanisms: git show 6a30f5f9:docs/lab/senses/pam-rebuild/round2/r36_repair/r36_probe.zag

Output: b3536_lib.zag = imports + structs + all H-35 fns (minus main) +
        H-36-only fns (minus main). The 13 shared helpers are kept once and
        asserted byte-identical across the two sources before dedupe.
"""
import os
import re
import subprocess
import sys

D = os.path.dirname(os.path.abspath(__file__))
WORK = os.path.expanduser("~/workspace/b3536_scratch")
REPO = os.path.expanduser("~/workspace/selfpam_run/tnn-lab")
os.makedirs(WORK, exist_ok=True)

H35_COMMIT = "1fa4ae58"
H35_PATH = "docs/lab/senses/pam-rebuild/round2/r35/hpam3536_r35.zag"
H36_COMMIT = "6a30f5f9"
H36_PATH = "docs/lab/senses/pam-rebuild/round2/r36_repair/r36_probe.zag"


def gshow(commit, path):
    r = subprocess.run(["git", "show", f"{commit}:{path}"],
                       capture_output=True, text=True, cwd=REPO)
    assert r.returncode == 0, f"git show failed for {commit}:{path}"
    return r.stdout


def sha(b: bytes) -> str:
    import hashlib
    return hashlib.sha256(b).hexdigest()


def extract_fn(src: str, name: str):
    """Return (full_fn_text) for `fn name(` ... matching close brace, or None."""
    i = src.find(f"fn {name}(")
    if i < 0:
        return None
    j = src.find("{", i)
    assert j > i, f"no body for {name}"
    depth = 1
    j += 1
    while depth > 0:
        if src[j] == "{":
            depth += 1
        elif src[j] == "}":
            depth -= 1
        j += 1
    return src[i:j]


def fn_names(src: str):
    return re.findall(r"^fn ([A-Za-z0-9_]+)\(", src, re.M)


def strip_main_and_imports(src: str) -> str:
    m = extract_fn(src, "main")
    if m:
        src = src.replace(m, "", 1)
    src = re.sub(r'^@import\(".*"\)\n', "", src, flags=re.M)
    return src


def main():
    h35 = gshow(H35_COMMIT, H35_PATH)
    h36 = gshow(H36_COMMIT, H36_PATH)
    with open(os.path.join(WORK, "h35_r35.zag"), "w") as f:
        f.write(h35)
    with open(os.path.join(WORK, "h36_r36.zag"), "w") as f:
        f.write(h36)
    print(f"h35 sha={sha(h35.encode())}", flush=True)
    print(f"h36 sha={sha(h36.encode())}", flush=True)

    h35_names = set(fn_names(h35))
    h36_names = set(fn_names(h36))
    shared = sorted(h35_names & h36_names - {"main"})
    print(f"shared fns ({len(shared)}): {', '.join(shared)}", flush=True)
    # assert byte-identical before dedupe
    for n in shared:
        a, b = extract_fn(h35, n), extract_fn(h36, n)
        assert a is not None and b is not None, f"missing shared fn {n}"
        assert a == b, f"SHARED FN DIFFERS: {n}"
    print("all shared fns byte-identical -> dedupe safe", flush=True)

    h35_body = strip_main_and_imports(h35)
    h36_body = strip_main_and_imports(h36)
    # B-3536 composition hygiene: drop h35's `fn m36` (the PRE-REPAIR
    # hardcoded-seed mode-36 regression battery). It is dead code in the
    # composition — the 36-side is the repaired fresh-seed path (r36
    # mechanisms + this driver's comp36* batteries) — and it carries six
    # copies of the stale hardcoded seed (305419896/2596069104), which would
    # otherwise sit in the attacker's read set outside the marked
    # M36-ATTACKER-CLASS fixture. Nothing in the composition calls m36.
    m36 = extract_fn(h35_body, "m36")
    assert m36 is not None, "h35 m36 not found"
    assert "fn m36(" not in h36_body
    h35_body = h35_body.replace(m36, "", 1)
    print("dropped dead h35 m36 (stale hardcoded seed, uncalled)", flush=True)
    # drop shared fns from h36 body
    for n in shared:
        m = extract_fn(h36_body, n)
        assert m is not None, f"could not find {n} in h36 body"
        h36_body = h36_body.replace(m, "", 1)

    # sanity: h36 keeps its unique fns
    h36_unique = sorted(h36_names - h35_names - {"main"})
    for n in h36_unique:
        assert f"fn {n}(" in h36_body, f"lost unique fn {n}"

    header = (
        '// b3536_lib.zag — B-3536 composition library (generated by extract_b3536.py)\n'
        '// Mechanisms extracted by script from committed repaired sources (never retyped):\n'
        '//   H-35 (capability-typed sinks, full-64-bit tag repair): commit 1fa4ae58\n'
        f'//     source SHA-256 {sha(h35.encode())}\n'
        '//   H-36 (commit-then-sample, fresh-seed repair): commit 6a30f5f9\n'
        f'//     source SHA-256 {sha(h36.encode())}\n'
        '// 13 shared helpers (ob_puts/ob_puti/yn/fnv32/put32i/put32u/wstep/\n'
        '// honest_wc/honest_wm/cstep/admit36/adv36_conf/adv36_meas) asserted\n'
        '// byte-identical across both sources and kept once (from the H-35 copy).\n'
        '@import("R33_NATIVE_IO_V1.zag")\n'
        '@import("R33_NATIVE_SHA256_V2.zag")\n'
    )
    lib = header + h35_body + "\n// ---------- H-36-only mechanisms ----------\n" + h36_body
    # final duplicate-fn guard
    names = fn_names(lib)
    assert len(names) == len(set(names)), f"duplicate fn names: {sorted(set(n for n in names if names.count(n) > 1))}"
    assert "fn main(" not in lib, "main leaked into lib"

    out = os.path.join(WORK, "b3536_lib.zag")
    with open(out, "w") as f:
        f.write(lib)
    print(f"wrote {out} sha={sha(lib.encode())} fns={len(names)}", flush=True)


if __name__ == "__main__":
    main()
