#!/usr/bin/env python3
"""gen_engine.py — generate the Zag policy-engine includes.

Reads frozen battery CSVs, emits:
  apparatus/policy_engine.zag.inc          full: b=0,1,2 tables + interpreter
  apparatus/policy_engine_subject.zag.inc  b=0 table only + interpreter
  apparatus/novel_table.zag.inc            b=2 table only (provenance re-run)

The interpreter text is IDENTICAL in both engine includes (asserted below).

  b: 0=real (fields only, NO gt), 1=proxy (fields + gt(f=11) + class(f=12)),
     2=novel (fields only, NO gt)
  f: 0=key,1=vold,2=vnew,3=a1,4=op1,5=a2,6=op2,7=a3,8=op3,9=cidx,10=caval
"""
import csv
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
APP = HERE.parent
RUN2 = APP.parent
RUN1 = RUN2.parent / "autonomous_run_1"

REAL_CSV = RUN1 / "battery_r4c.csv"
PROXY_CSV = RUN1 / "proxy_battery.csv"
NOVEL_CSV = HERE / "novel_fields.csv"
INTERP = HERE / "policy_interpreter.zag"

FIELDS = ["key", "vold", "vnew", "a1", "op1", "a2", "op2", "a3", "op3",
          "cidx", "caval"]
CLS = {"N-clean": 0, "O-clean": 1, "ADV-NEW": 2, "ADV-OLD": 3, "NEITHER": 4}
GT = {"WITHHOLD": 0, "NEW": 1, "OLD": 2}


def load(path, with_gtclass=False):
    rows = []
    with open(path) as f:
        rd = csv.DictReader(f)
        for r in rd:
            row = [int(r["id"])] + [int(r[k]) for k in FIELDS]
            if with_gtclass:
                row += [GT[r["gt"]], CLS[r["class"]]]
            rows.append(row)
    assert len(rows) == 24, f"{path}: expected 24 rows, got {len(rows)}"
    # ids must be 1..24 in order
    assert [r[0] for r in rows] == list(range(1, 25)), f"{path}: bad id order"
    return rows


def fld_fn(branches):
    out = ["// generated by gen_engine.py — DO NOT HAND-EDIT",
           "// fld(b,i,f): b=0 real fields (NO gt); b=1 proxy fields+gt(f=11)+class(f=12);",
           "//               b=2 novel fields (NO gt).",
           "fn fld(b:i32,i:i32,f:i32)i32 {"]
    out.extend(branches)
    out.append('    return 0;')
    out.append('}')
    return "\n".join(out) + "\n"


def branches(b, rows, with_gtclass=False):
    out = [f"    if(b=={b}){{"]
    for idx, row in enumerate(rows):
        out.append(f"        if(i=={idx}){{")
        for fi in range(len(FIELDS)):
            out.append(f"            if(f=={fi}){{return {row[1+fi]};}}")
        if with_gtclass:
            out.append(f"            if(f==11){{return {row[-2]};}}")
            out.append(f"            if(f==12){{return {row[-1]};}}")
        out.append("        }")
    out.append("    }")
    return out


def main():
    real = load(REAL_CSV)
    proxy = load(PROXY_CSV, with_gtclass=True)
    novel = load(NOVEL_CSV)
    interp = INTERP.read_text()
    assert "fn pe_decide" in interp, "interpreter missing pe_decide"
    assert "fn fld" not in interp, "interpreter must not define fld"

    full_branches = (branches(0, real) + branches(1, proxy, True)
                     + branches(2, novel))
    subj_branches = branches(0, real)
    novel_branches = branches(2, novel)

    full_inc = fld_fn(full_branches) + interp
    subj_inc = fld_fn(subj_branches) + interp
    novel_inc = fld_fn(novel_branches)

    # interpreter text identical in both engine includes
    assert full_inc[len(fld_fn(full_branches)):] == interp
    assert subj_inc[len(fld_fn(subj_branches)):] == interp

    (APP / "policy_engine.zag.inc").write_text(full_inc)
    (APP / "policy_engine_subject.zag.inc").write_text(subj_inc)
    (APP / "novel_table.zag.inc").write_text(novel_inc)
    print(f"wrote policy_engine.zag.inc ({len(full_inc)} bytes)")
    print(f"wrote policy_engine_subject.zag.inc ({len(subj_inc)} bytes)")
    print(f"wrote novel_table.zag.inc ({len(novel_inc)} bytes)")


if __name__ == "__main__":
    main()
