#!/bin/bash
# build_adapters.sh — assemble the self-contained variant seam adapters.
#
# The frozen run_seam.sh stages ONLY the single adapter file into its build
# dir (znc resolves @import relative to CWD), so each adapter must be
# self-contained: this script concatenates the frozen variant sources
# (@import lines stripped — they would resolve against the build dir and
# fail) with the hand-written adapter body.
#
# Variant sources are NOT modified: they are copied verbatim apart from the
# stripped @import directives. The adapter bodies document the composition
# protocol each adapter implements (neither variant built one).
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
OB_A="$HOME/workspace/onebrain/ob_a"
OB_B="$HOME/workspace/onebrain/ob_b"

strip_imports() { grep -v '^[[:space:]]*@import' "$1"; }

{
  echo "// variant_a_seam_target_impl.zag — GENERATED by adapters/build_adapters.sh; do not edit by hand."
  echo "// Variant A frozen commit 7b0ba4f2 (docs/lab/onebrain/variant_a/)."
  echo "// Sources concatenated verbatim (@import lines stripped):"
  echo "//   ob_substrate.zag, ob_gl.zag, ob_pam.zag, ob_mem.zag"
  for f in ob_substrate.zag ob_gl.zag ob_pam.zag ob_mem.zag; do
    echo "// ==================== BEGIN $f ===================="
    strip_imports "$OB_A/$f"
    echo "// ==================== END $f ===================="
  done
  echo "// ==================== BEGIN adapter_a_body.zag ===================="
  cat "$HERE/adapter_a_body.zag"
} > "$HERE/variant_a_seam_target_impl.zag"

{
  echo "// variant_b_seam_target_impl.zag — GENERATED by adapters/build_adapters.sh; do not edit by hand."
  echo "// Variant B frozen commit 54bc8aec (docs/lab/onebrain/variant_b/)."
  echo "// Sources concatenated verbatim (@import lines stripped):"
  echo "//   ob_common.zag, ob_tn.zag, ob_pam.zag, ob_mem.zag, ob_arbiter.zag"
  echo "// (ob_fl2.zag omitted: the adapter injects intents directly; the FL2"
  echo "//  stream organ is unit-tested separately and its trace is an input"
  echo "//  the abstract attack scripts do not provide.)"
  for f in ob_common.zag ob_tn.zag ob_pam.zag ob_mem.zag ob_arbiter.zag; do
    echo "// ==================== BEGIN $f ===================="
    strip_imports "$OB_B/$f"
    echo "// ==================== END $f ===================="
  done
  echo "// ==================== BEGIN adapter_b_body.zag ===================="
  cat "$HERE/adapter_b_body.zag"
} > "$HERE/variant_b_seam_target_impl.zag"

echo "wrote $HERE/variant_a_seam_target_impl.zag"
echo "wrote $HERE/variant_b_seam_target_impl.zag"
wc -l "$HERE"/variant_*_seam_target_impl.zag
