#!/usr/bin/env python3
# test_boundary.py — characterization tests for the frozen confirmatory analyzer
# (c2/bin/uanalyze). All fixtures are analytical (zero RNG), generated by
# documented formulas below. These tests LOCK IN the analyzer's honest
# boundaries; they document behavior, not pass/fail gates.
#
# Run: python3 test_boundary.py
# Requires: ../bin/uanalyze (frozen c2 binary)

import math, os, struct, subprocess, sys

BIN = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'bin', 'uanalyze')
FIX = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'fixtures')
os.makedirs(FIX, exist_ok=True)
SR = 16000

def rint(x):
    return int(math.floor(x + 0.5)) if x >= 0 else int(math.ceil(x - 0.5))

def write_wav(path, samples, extra_chunks=b''):
    pcm = struct.pack('<%dh' % len(samples), *[max(-32768, min(32767, s)) for s in samples])
    fmt = struct.pack('<4sIHHIIHH', b'fmt ', 16, 1, 1, SR, SR*2, 2, 16)
    data = struct.pack('<4sI', b'data', len(pcm)) + pcm
    riff_len = 4 + len(fmt) + len(extra_chunks) + len(data)
    hdr = struct.pack('<4sI4s', b'RIFF', riff_len, b'WAVE')
    with open(path, 'wb') as f:
        f.write(hdr + fmt + extra_chunks + data)

def write_ppm(path, w, h, px):
    # px: list of (r,g,b) length w*h
    hdr = ('P6\n%d %d\n255\n' % (w, h)).encode()
    body = b''.join(struct.pack('BBB', r, g, b) for (r, g, b) in px)
    with open(path, 'wb') as f:
        f.write(hdr + body)

def run(*args):
    r = subprocess.run([BIN] + list(args), capture_output=True, text=True)
    return r.stdout

def get(stdout, key):
    for line in stdout.splitlines():
        if line.startswith(key + ' '):
            return line.split(' ', 1)[1]
    return None

print("=" * 70)
print("BOUNDARY CHARACTERIZATION — frozen c2 analyzer")
print("=" * 70)

# --- Test 1: RIFF chunk scanning ---
# 444.444 Hz tone, 2 s, with a 64-byte LIST chunk inserted before 'data'.
# The parser must scan for 'data', not assume offset 44.
N = 32000
tone = [rint(12000 * math.sin(2*math.pi*(4000/9)*i/SR)) for i in range(N)]
list_chunk = struct.pack('<4sI', b'LIST', 56) + b'X' * 56
write_wav(FIX + '/t1_list.wav', tone, extra_chunks=list_chunk)
out = run('a', FIX + '/t1_list.wav')
f0 = get(out, 'f0_med_dhz'); dur = get(out, 'dur_ms')
print(f"\n[1] RIFF chunk scanning (LIST before data):")
print(f"    f0_med_dhz={f0} (expect 4444), dur_ms={dur} (expect 2000)")
print(f"    -> {'OK: data chunk found by scan' if f0=='4444' and dur=='2000' else 'FAIL'}")

# --- Test 2: Percentile/sort correctness ---
# 1.5 s at 444.444 Hz then 1.5 s at 888.888 Hz. f0_p10 ~4444, f0_p90 ~8888.
# A broken sort (isort_copy bug) would corrupt these percentiles.
N = 48000
two = []
for i in range(N):
    f = (4000/9) if i < 24000 else (8000/9)
    two.append(rint(12000 * math.sin(2*math.pi*f*i/SR)))
write_wav(FIX + '/t2_twotone.wav', two)
out = run('a', FIX + '/t2_twotone.wav')
p10 = get(out, 'f0_p10_dhz'); p90 = get(out, 'f0_p90_dhz')
print(f"\n[2] Percentile/sort (444Hz + 888Hz halves):")
print(f"    f0_p10_dhz={p10} (expect ~4444), f0_p90_dhz={p90} (expect ~8888)")
ok = p10 and p90 and abs(int(p10)-4444) < 200 and abs(int(p90)-8888) < 400
print(f"    -> {'OK: percentiles track the two tones' if ok else 'CHECK'}")

# --- Test 3: Leading-silence dynamic range ---
# 1 s digital silence, 1 s quiet tone (amp 2000), 1 s loud tone (amp 16000).
# min_es must ignore the silent windows; dyn_ratio ~ (16000/2000)^2 = 64.
N = 48000
sig = [0]*16000
sig += [rint(2000 * math.sin(2*math.pi*(4000/9)*i/SR)) for i in range(16000)]
sig += [rint(16000 * math.sin(2*math.pi*(4000/9)*i/SR)) for i in range(16000)]
write_wav(FIX + '/t3_silence.wav', sig)
out = run('a', FIX + '/t3_silence.wav')
dr = get(out, 'dyn_ratio_milli')
print(f"\n[3] Leading-silence dynamic range (silence+quiet+loud):")
print(f"    dyn_ratio_milli={dr} (expect ~64.0 for 64x; 1.000 means silence-poisoned)")
ok = dr and float(dr) > 20.0
print(f"    -> {'OK: silence excluded from min' if ok else 'FAIL: min poisoned by silence'}")

# --- Test 4: High-frequency pitch ceiling ---
# 6 kHz tone (above the 4 kHz autocorr ceiling). Documents subharmonic aliasing.
N = 48000
hi = [rint(12000 * math.sin(2*math.pi*6000*i/SR)) for i in range(N)]
write_wav(FIX + '/t4_6khz.wav', hi)
out = run('a', FIX + '/t4_6khz.wav')
f0 = get(out, 'f0_med_dhz')
print(f"\n[4] High-frequency pitch ceiling (6 kHz tone, ceiling 4 kHz):")
print(f"    f0_med_dhz={f0} (true 60000; expect aliased subharmonic, NOT 60000)")
print(f"    -> {'OK: honest boundary (reports subharmonic, not 6kHz)' if f0 and f0!='60000' else 'CHECK'}")

# --- Test 5: Long-period rhythm withholding ---
# 6 s tone with 0.2 Hz AM (5 s period). Rhythm window is 0.1-0.5 s: must withhold.
N = 96000
am = []
for i in range(N):
    env = 0.5 + 0.5 * math.sin(2*math.pi*0.2*i/SR)
    am.append(rint(12000 * env * math.sin(2*math.pi*(4000/9)*i/SR)))
write_wav(FIX + '/t5_longam.wav', am)
out = run('a', FIX + '/t5_longam.wav')
ep = get(out, 'env_period_ms')
print(f"\n[5] Long-period rhythm (5 s AM period; detector window 0.1-0.5 s):")
print(f"    env_period_ms={ep} (expect 0 = withheld; nonzero = fabricated, cf. H1/H2)")
print(f"    -> {'OK: withheld' if ep=='0' else 'DOCUMENTED: fabricates (known H1/H2 mechanism)'}")

# --- Test 6: Fine-detail texture scale ---
# 480x320: (a) 2px checkerboard, (b) smooth gray. At 80x45 both read smooth.
w, h = 480, 320
chk = [((255,255,255) if ((x//2)+(y//2))%2==0 else (0,0,0)) for y in range(h) for x in range(w)]
write_ppm(FIX + '/t6_checker.ppm', w, h, chk)
sm = [(128,128,128)] * (w*h)
write_ppm(FIX + '/t6_smooth.ppm', w, h, sm)
o1 = run('i', FIX + '/t6_checker.ppm'); o2 = run('i', FIX + '/t6_smooth.ppm')
t1 = [l for l in o1.splitlines() if 'TEXTURE' in l]
t2 = [l for l in o2.splitlines() if 'TEXTURE' in l]
print(f"\n[6] Fine-detail texture scale (2px checkerboard vs smooth, analyzed at 80x45):")
print(f"    checker: {t1[0] if t1 else '?'}")
print(f"    smooth:  {t2[0] if t2 else '?'}")
print(f"    -> DOCUMENTED: fine detail invisible at analysis scale (cf. H4/H5)")

# --- Test 7: Deforming/churning motion ---
# 6 frames, 160x90, deterministic churning: sum of moving sine interference.
# Block matcher should find no consistent vectors (chaotic).
w, h = 160, 90
for f in range(6):
    px = []
    for y in range(h):
        for x in range(w):
            v = math.sin(0.3*x + 0.9*f) + math.sin(0.4*y - 1.3*f) + math.sin(0.2*(x+y) + 0.5*f)
            g = int(128 + 100 * v / 3)
            g = max(0, min(255, g))
            px.append((g, g, g))
    write_ppm(f'{FIX}/t7_c{f+1:03d}.ppm', w, h, px)
# rename to f_001..f_006 for the video prefix convention
import glob
for f in range(6):
    os.rename(f'{FIX}/t7_c{f+1:03d}.ppm', f'{FIX}/t7_f_{f+1:03d}.ppm')
out = run('v', FIX + '/t7_', '6')
vf = get(out, 'valid_frac_milli'); sp = get(out, 'speed_pxs_milli')
desc = [l for l in out.splitlines() if 'MOTION' in l or 'motion' in l.lower()]
print(f"\n[7] Deforming/churning motion (deterministic sine-interference churn):")
print(f"    valid_frac_milli={vf}, speed_pxs_milli={sp}")
for d in desc[:3]: print(f"    {d.strip()}")
print(f"    -> DOCUMENTED: block matcher on chaotic texture (cf. V1 boundary)")

print("\n" + "=" * 70)
print("CHARACTERIZATION COMPLETE")
print("=" * 70)
