#!/usr/bin/env python3
"""analyze_geometry.py — parse frozen D1 trial tables + enumerate proposals.

Step 1: parse frozen_stack_records.zag (generated by frozen gen_d1.py) into
per-stream trial tables. Step 2: reimplement the frozen gate mirror VERBATIM
(copied from gen_d1.py) and enumerate every install proposal with full pair
geometry (mrgF, seq, spans, truth). Step 3: verify leg3 tables against the
frozen gen_guard.py rows. All from frozen sources; zero RNG.
"""
import re, json, hashlib, sys

HERE = "/home/hatch/workspace/pam_round3/mg6_temporal"
V2 = "/home/hatch/workspace/tnn-lab/senses/pam-rebuild/v2"
KEY = b"PAMV2-REG-CHANNEL-2026-09-23"

TOLS = {0: 8, 1: 40, 2: 60, 3: 4000, 4: 120, 5: 0}
D_PERM, D_PROV, D_CORR, D_CONF, D_CHAL, D_REV, D_ACC, D_WITH = 0, 1, 2, 3, 4, 5, 6, 7

# ---------- 1. parse frozen stack_records.zag ----------
def parse_records(path):
    txt = open(path).read()
    streams = {}
    # find each stream's init function blocks
    for m in re.finditer(r"fn d1_(\w+)_init_trials\(tr:\[\]u8\) void \{(.*?)\n\}", txt, re.S):
        sname, body = m.group(1), m.group(2)
        words = {}
        for pm in re.finditer(r"t_put64\(tr,(\d+),(-?\d+)\);", body):
            off, w = int(pm.group(1)), int(pm.group(2))
            words[off] = w
        n = max(words) // 112 + 1 if words else 0
        trials = []
        for ti in range(n):
            base = ti * 112
            w = [words[base + f * 8] for f in range(14)]
            trials.append({
                "seq": w[0], "tcode": w[1], "prog": w[2], "jcode": w[3],
                "conf": w[4], "pred": w[5], "meas": w[6], "mrgF": w[7],
                "jG": w[8], "confG": w[9], "span_a": w[10], "span_b": w[11],
                "fx_off": w[12], "fx_len": w[13],
            })
        streams[sname] = trials
    # fixture strings
    for m in re.finditer(r"fn d1_(\w+)_init_fx\(fx:\[\]u8\) void \{(.*?)\n\}", txt, re.S):
        sname, body = m.group(1), m.group(2)
        blist = {}
        for pm in re.finditer(r"fx\[(\d+)\]=(\d+);", body):
            blist[int(pm.group(1))] = int(pm.group(2))
        raw = bytes(blist[i] for i in range(max(blist) + 1)) if blist else b""
        for t in streams[sname]:
            t["fixture"] = raw[t["fx_off"]:t["fx_off"] + t["fx_len"]].decode()
    return streams

streams = parse_records(HERE + "/frozen_stack_records.zag")
print("parsed streams:", {k: len(v) for k, v in streams.items()})

# ---------- 2. verify leg3 tables vs frozen gen_guard.py ----------
# (D1 prereg §2: leg3 uses the EXACT trial rows from round2/cc1_guard/gen_guard.py)
sys.path.insert(0, HERE)
import frozen_gen_guard as G
ok = True
for (cn, rows, cfj, pre, nh, sc) in G.CELLS:
    if cn in ("CC1-V1","CC1-V2","CC1-V3","CC1-V4","CC1-V5","CC1-V6","CC1-V7","CC1-V8","CC1-V9",
              "CC2-W1","CC2-W2","C1-W3"):
        continue  # not in the D1 leg3 set
    sname = "leg3_" + cn
    st = streams[sname]
    assert len(st) == len(rows), (sname, len(st), len(rows))
    for ri, row in enumerate(rows):
        (tcode, prog, jcode, conf, pred, meas, mrgF, truth,
         jG, confG, seq, sa, sb) = row
        t = st[ri]
        checks = [
            t["tcode"] == tcode, t["prog"] == prog, t["jcode"] == jcode,
            t["conf"] == conf, t["pred"] == pred, t["meas"] == meas,
            t["mrgF"] == mrgF, t["jG"] == jG, t["confG"] == confG,
            t["seq"] == seq, t["span_a"] == sa, t["span_b"] == sb,
        ]
        if not all(checks):
            ok = False
            print("MISMATCH", sname, ri, row, t)
print("leg3 tables match frozen gen_guard.py rows:", "PASS" if ok else "FAIL")

# ---------- 3. gatt sidecars ----------
def load_gatt(path):
    g = {}
    for line in open(path):
        line = line.strip()
        if not line:
            continue
        s, tag = line.split("|")
        g[int(s)] = tag
    return g

def recompute_tag(t):
    ib = KEY + b"|" + str(t["seq"]).encode() + b"|" + t["fixture"].encode() + \
        b"|" + str(t["jG"]).encode() + b"|" + str(t["confG"]).encode()
    return hashlib.sha256(ib).hexdigest()

gatt_files = {
    "leg1": V2 + "/hardening/gatt/withhold.gatt",
    "leg2": V2 + "/hardening/gatt/install.gatt",
    "leg4_clean": V2 + "/hardening/gatt/clean.gatt",
    "leg4_withhold": V2 + "/hardening/gatt/withhold.gatt",
    "leg4_install": V2 + "/hardening/gatt/install.gatt",
    "leg4_decoy": V2 + "/hardening/gatt/decoy.gatt",
}
# map trial_idx -> tag via seq
gtags = {}
for sname, trials in streams.items():
    if sname.startswith("leg3_"):
        cn = sname[5:]
        # gatt_leg3 files live in the frozen d1_stack dir
        g = load_gatt("/home/hatch/workspace/tnn-lab/docs/lab/senses/pam-rebuild/round2/d1_stack/gatt_leg3_%s.txt" % cn)
        gtags[sname] = {ti: g[ti] for ti in range(len(trials))}
    else:
        g = load_gatt(gatt_files[sname])
        gtags[sname] = {ti: g[t["seq"]] for ti, t in enumerate(trials)}

# verify recomputation on genuine tags (all except spoofed decoys)
n_match = n_total = n_spoof = 0
for sname, trials in streams.items():
    for ti, t in enumerate(trials):
        n_total += 1
        if recompute_tag(t) == gtags[sname][ti]:
            n_match += 1
        else:
            if sname == "leg4_decoy":
                n_spoof += 1
            else:
                print("TAG MISMATCH", sname, ti, t["seq"], t["fixture"])
print("gatt recompute: %d/%d match, %d spoofed decoys" % (n_match, n_total, n_spoof))

# ---------- 4. frozen gate mirror (verbatim from gen_d1.py) ----------
def gate_step(st, t, tag):
    tol = TOLS[t["tcode"]]
    prog, jc, conf, pred, meas = t["prog"], t["jcode"], t["conf"], t["pred"], t["meas"]
    if prog != 0 or pred != 1:
        return D_WITH, "gate-prog-pred", None
    prov, perm, chal = st["prov"], st["perm"], st["chal"]
    if perm and jc == perm["t"]["jcode"] and abs(meas - perm["t"]["meas"]) <= tol:
        return D_CORR, "gate-corr", None
    if prov and not perm and jc == prov["t"]["jcode"] \
            and abs(meas - prov["t"]["meas"]) <= tol:
        if conf >= 700:
            return "PROPOSE_PERM", "gate-propose-perm", (prov, {"t": t, "tag": tag})
        return D_PROV, "gate-prov-lowconf", None
    if perm or prov:
        ij = perm["t"]["jcode"] if perm else prov["t"]["jcode"]
        if jc != ij:
            if conf >= 700:
                if chal and chal["t"]["jcode"] == jc \
                        and abs(meas - chal["t"]["meas"]) <= tol:
                    return "PROPOSE_REV", "gate-propose-rev", (chal, {"t": t, "tag": tag})
                st["chal"] = {"t": t, "tag": tag}
                return D_CHAL, "gate-chal", None
            return D_CONF, "gate-conf-lowconf", None
        st["prov"] = {"t": t, "tag": tag}
        return D_PROV, "gate-reanchor", None
    st["prov"] = {"t": t, "tag": tag}
    return D_PROV, "gate-first-prov", None

def guard_arms(pair):
    """frozen MG6 arm attribution; returns list of fired arms."""
    s, tt = pair[0]["t"], pair[1]["t"]
    arms = []
    if min(s["mrgF"], tt["mrgF"]) < 400:
        arms.append("margin")
    if s["span_a"] < tt["span_b"] and tt["span_a"] < s["span_b"]:
        arms.append("span")
    if abs(s["seq"] - tt["seq"]) < 20:
        arms.append("temporal")
    return arms

def att_ok(tr, tag):
    t = tr["t"]
    ib = KEY + b"|" + str(t["seq"]).encode() + b"|" + t["fixture"].encode() + \
        b"|" + str(t["jG"]).encode() + b"|" + str(t["confG"]).encode()
    return hashlib.sha256(ib).hexdigest() == tag

def harden(pair, is_rev, hist, perm, tcode):
    for tr in pair:
        t = tr["t"]
        if t["prog"] != 0:
            return False, "harden-r1"
        if not att_ok(tr, tr["tag"]):
            return False, "harden-r2"
        if not (t["conf"] >= 700 and t["jG"] == t["jcode"] and t["confG"] >= 700):
            return False, "harden-r3"
    if is_rev and perm is not None:
        tol = TOLS[tcode]
        tj = pair[1]["t"]["jcode"]
        tm = pair[1]["t"]["meas"]
        corr = any(h[0] == tcode and h[1] == tj and h[2] == 0
                   and abs(h[3] - tm) <= tol for h in hist)
        if not corr or (pair[1]["t"]["conf"] - perm["t"]["conf"]) < 100:
            return False, "harden-r4"
    return True, "harden-ok"

def run_stream(trials, gtags, guard_fn, collect=None):
    """guard_fn(pair) -> list of fired arms (empty = allow)."""
    states = {}
    hist = []
    out = []
    for ti, t in enumerate(trials):
        tc = t["tcode"]
        st = states.setdefault(tc, {"prov": None, "perm": None, "chal": None})
        tag = gtags[ti]
        disp, detail, pair = gate_step(st, t, tag)
        install = 0
        if disp == "PROPOSE_PERM" or disp == "PROPOSE_REV":
            is_rev = (disp == "PROPOSE_REV")
            arms = guard_fn(pair)
            if collect is not None:
                collect.append((ti, t, pair, arms, is_rev))
            if arms:
                disp = D_CHAL if is_rev else D_PROV
                detail = "guard-veto:" + "+".join(arms)
            else:
                ok, hdetail = harden(pair, is_rev, hist, st["perm"], tc)
                if ok:
                    st["perm"] = {"t": pair[1]["t"], "tag": pair[1]["tag"]}
                    st["prov"] = None
                    st["chal"] = None
                    disp = D_REV if is_rev else D_PERM
                    detail = hdetail
                    install = 1
                else:
                    disp = D_WITH
                    detail = hdetail
        out.append((ti, disp, detail, install))
        hist.append((tc, t["jcode"], t["prog"], t["meas"]))
    return out

# ---------- 5. enumerate proposals with frozen MG6 ----------
print("\n=== leg1 proposals under frozen MG6 ===")
proposals = []
out = run_stream(streams["leg1"], gtags["leg1"], guard_arms, collect=proposals)
for (ti, t, pair, arms, is_rev) in proposals:
    s, inc = pair[0]["t"], pair[1]["t"]
    dseq = abs(s["seq"] - inc["seq"])
    print("idx %2d seq %3d kind=%s arms=%s dseq=%d mrg=(%d,%d) spans=(%d,%d)x(%d,%d) true_pair=%s incoming_true=%s" % (
        ti, t["seq"], "REV" if is_rev else "PERM", "+".join(arms) or "ALLOW",
        dseq, s["mrgF"], inc["mrgF"],
        s["span_a"], s["span_b"], inc["span_a"], inc["span_b"],
        (s.get("truth", "?"), inc.get("truth", "?")),
        "?"))

# truth: not in trial tables; recover from withhold records via fixture
rec_truth = {}
for line in open(V2 + "/redteam/evidence/rec_withhold.records"):
    f = line.rstrip("\n").split("|")
    rec_truth[f[2]] = (f[5], f[10])  # fixture -> (judgment, truth)
print("\n=== leg1 proposals with truth ===")
for (ti, t, pair, arms, is_rev) in proposals:
    s, inc = pair[0]["t"], pair[1]["t"]
    sj, st_ = rec_truth[s["fixture"]]
    ij, it_ = rec_truth[inc["fixture"]]
    dseq = abs(s["seq"] - inc["seq"])
    print("idx %2d seq %3d kind=%-4s arms=%-16s dseq=%2d mrg=(%5d,%5d) spans=(%5d,%5d)x(%5d,%5d) stored(j=%s,tru=%s) incoming(j=%s,tru=%s)" % (
        ti, t["seq"], "REV" if is_rev else "PERM", "+".join(arms) or "ALLOW",
        dseq, s["mrgF"], inc["mrgF"],
        s["span_a"], s["span_b"], inc["span_a"], inc["span_b"],
        sj, st_, ij, it_))
