#!/usr/bin/env python3
# gen_r3.py — deterministic EXPECT generator for the MG6 temporal-arm recalibration.
# Reads ONLY frozen inputs (by script, never memory), runs the validated mirror
# for all six preregistered candidates, emits EXPECT_R3*.tsv, copies the frozen
# stack_records.zag byte-verbatim, and regenerates guard_records.zag via the
# frozen CC1 generator, asserting byte-identity with the frozen committed copy.
# Pure Python, zero RNG, deterministic output (insertion-ordered streams).
import sys, os, io, hashlib, contextlib, shutil, subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
# silence analysis-script main output
with contextlib.redirect_stdout(io.StringIO()):
    from analyze_geometry import streams, gtags
    from sweep_guards import run_with_hist, mk_guard, CANDS, truth_for
    import sweep_cc1 as C1

LAB = os.path.expanduser("~/workspace/tnn-lab")
D1DIR = os.path.join(LAB, "docs/lab/senses/pam-rebuild/round2/d1_stack")
CC1DIR = os.path.join(LAB, "docs/lab/senses/pam-rebuild/round2/cc1_guard")

def sha(b): return hashlib.sha256(b).hexdigest()

# ---- 1. copy frozen stack_records.zag byte-verbatim -------------------------
src = os.path.join(D1DIR, "stack_records.zag")
dst = os.path.join(HERE, "r3_stack_records.zag")
data = open(src, "rb").read()
open(dst, "wb").write(data)
print("stack_records.zag copied byte-verbatim, sha256=%s" % sha(data)[:16])

# ---- 2. regenerate guard_records.zag via frozen generator, assert identity --
gen = os.path.join(HERE, "frozen_gen_guard.py")
gen_src = open(gen).read()
assert 'CELLS = [' in gen_src, "frozen generator table missing"
# run the frozen generator's emit path in a temp dir (it writes guard_records.zag)
tmpd = os.path.join(HERE, "_gen_tmp")
os.makedirs(tmpd, exist_ok=True)
shutil.copy(gen, os.path.join(tmpd, "gen_guard.py"))
r = subprocess.run([sys.executable, "gen_guard.py"], cwd=tmpd,
                   capture_output=True, text=True)
assert r.returncode == 0, r.stderr[-2000:]
regen = open(os.path.join(tmpd, "guard_records.zag"), "rb").read()
# frozen guard_records.zag: local pam_round2 copy + git-committed copy
gr_local = "/home/hatch/workspace/pam_round2/cc1_guard/src/guard_records.zag"
frozen_gr = open(gr_local, "rb").read()
gr_git = subprocess.run(
    ["git", "-C", "/home/hatch/workspace/selfpam_run/tnn-lab", "show",
     "dfe3d49f6d6be7ea99c3740320e475e667ec77b0:docs/lab/senses/pam-rebuild/round2/cc1_guard/src/guard_records.zag"],
    capture_output=True)
assert gr_git.returncode == 0, "git show guard_records.zag failed"
assert sha(gr_git.stdout) == sha(frozen_gr), "local vs git guard_records.zag differ"
assert sha(regen) == sha(frozen_gr), "regenerated guard_records.zag DIFFERS from frozen"
shutil.copy(os.path.join(tmpd, "guard_records.zag"),
            os.path.join(HERE, "r3_guard_records.zag"))
shutil.rmtree(tmpd)
print("guard_records.zag regenerated byte-identical to frozen, sha256=%s" % sha(regen)[:16])

# ---- 3. D1 battery EXPECT ----------------------------------------------------
DN = {0:"PERM",1:"PROV",2:"CORR",3:"CONF",4:"CHAL",5:"REV",6:"ACC",7:"WITH",
      -1:"PROPOSE",-2:"ALLOW"}
C1DN = {0:"PERM",1:"PROV",2:"CORR",3:"CONF",4:"CHAL",5:"REV",6:"ACC",7:"WITH"}
with open(os.path.join(HERE, "EXPECT_R3.tsv"), "w") as f:
    f.write("cand\tleg\ttrial_idx\tseq\tdisp\tinstall\tdetail\n")
    for cand in CANDS:
        gf = mk_guard(cand)
        for sname, trials in streams.items():
            out = run_with_hist(trials, gtags[sname], gf)
            for (ti, disp, detail, inst) in out:
                sdisp = DN[disp] if isinstance(disp, int) else disp
                f.write("%s\t%s\t%d\t%d\t%s\t%d\t%s\n" % (
                    cand, sname, ti, trials[ti]["seq"], sdisp, inst, detail))
print("EXPECT_R3.tsv written")

# ---- 4. D1 battery per-cell summary -----------------------------------------
with open(os.path.join(HERE, "EXPECT_R3_CELL.tsv"), "w") as f:
    f.write("cand\tleg\ttrials\tinstalls\tfalse_installs\ttrue_leg1_retained\n")
    for cand in CANDS:
        gf = mk_guard(cand)
        for sname, trials in streams.items():
            out = run_with_hist(trials, gtags[sname], gf)
            ninst = sum(1 for x in out if x[3] == 1)
            nfalse = 0
            ntrue = 0
            for (ti, disp, detail, inst) in out:
                if inst and sname == "leg1":
                    j, tru = truth_for(sname, trials[ti])
                    if j == tru: ntrue += 1
                    else: nfalse += 1
            f.write("%s\t%s\t%d\t%d\t%d\t%d\n" % (
                cand, sname, len(trials), ninst, nfalse, ntrue))
print("EXPECT_R3_CELL.tsv written")

# ---- 5. CC1 battery EXPECT ---------------------------------------------------
with open(os.path.join(HERE, "EXPECT_R3_CC1.tsv"), "w") as f:
    f.write("cand\tcell\ttrial_idx\tdisp\n")
    for cand in CANDS:
        gf = C1.mk_guard(cand)
        for (name, trials, cfj, pre, no_hist, scored) in C1.G.CELLS:
            out, pj = C1.g1_cell(trials, pre, no_hist, gf)
            for (ti, disp, prop) in out:
                sdisp = C1DN[disp] if isinstance(disp, int) else disp
                f.write("%s\t%s\t%d\t%s\n" % (cand, name, ti, sdisp))
print("EXPECT_R3_CC1.tsv written")
print("done")
