#!/usr/bin/env python3
# gen_compact2.py — extracts ALL frozen record bytes and emits compact Zag.
import re

src = open("src/r3_stack_records.zag").read()

def get_fn_body(name):
    m = re.search(r'fn %s\(\w+:\[\]u8\) void \{(.*?)\n\}' % name, src, re.S)
    return m.group(1) if m else None

def extract_bytes(body):
    # Handles t_put64(arr,off,val) and arr[i]=val
    buf = {}
    for o, v in re.findall(r't_put64\(\w+,(\d+),(-?\d+)\);', body):
        o = int(o); v = int(v) & 0xFFFFFFFFFFFFFFFF
        for i in range(8):
            buf[o+i] = (v >> (i*8)) & 0xFF
    for i, v in re.findall(r'\w+\[(\d+)\]=(\d+);', body):
        buf[int(i)] = int(v) & 0xFF
    if not buf: return None
    n = max(buf.keys()) + 1
    return bytes(buf.get(i, 0) for i in range(n))

streams = re.findall(r'fn d1_(\w+)_init_trials', src)
out = ["// r3_records_compact.zag — frozen D1 records, compact encoding.",
       "// Data byte-identical to r3_stack_records.zag; generated by gen_compact2.py.",
       "// Build note: the 1.3MB t_put64 init file does not compile without zagd.",
       ""]
for s in streams:
    S = s.upper()
    for kind in ["trials", "fx", "gatt"]:
        fn = "d1_%s_init_%s" % (s, kind)
        body = get_fn_body(fn)
        data = extract_bytes(body) if body else None
        if data is None:
            print("SKIP", fn); continue
        # Emit as \xNN, single string literal (Zag handles large literals fine)
        hexstr = ''.join('\\x%02x' % b for b in data)
        out.append('const D1_%s_%s_DATA:[]u8 = "%s";' % (S, kind.upper(), hexstr))
        out.append('const D1_%s_%s_LEN:i64 = %d;' % (S, kind.upper(), len(data)))
        out.append("")
    print("ok", s, "trials/fx/gatt")

open("src/r3_records_compact.zag", "w").write("\n".join(out))
print("written")
