#!/usr/bin/env python3
"""gen_fixtures.py — validate frozen fixtures, then emit src/ws_fixtures.zag.

Validates:
  - real_search.json: 20 facts (10 known + 10 unknown), 2 results each,
    distinct domains, synthetic=false, result_hash == sha256(url\\ntitle\\nsnippet)
  - spoof_search.json: 6 planted scenarios
  - teacher_check.json: 12 teacher falsehoods
  - query_gate.json: 12 gate situations
  - edge_cases.json: 3 edge fixtures
Emits Zag runner functions; never hand-edit the output.
"""
import json, hashlib, os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'src')
FIX = os.path.join(HERE, 'fixtures')

def load(name):
    with open(os.path.join(FIX, name), encoding='utf-8') as f:
        return json.load(f)

def zesc(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '\\': out.append('\\\\')
        elif ch == '"': out.append('\\"')
        elif ch == '\n': out.append('\\n')
        elif ch == '\t': out.append('\\t')
        elif ch == '\r': out.append('\\r')
        elif o < 32 or o == 127: out.append('\\x%02x' % o)
        else: out.append(ch)
    return '"' + ''.join(out) + '"'

def rhash(r):
    return hashlib.sha256((r['url'] + "\n" + r['title'] + "\n" + r['snippet']).encode('utf-8')).hexdigest()

# ---- validate real_search.json ----
real = load('real_search.json')
facts = real['facts']
assert len(facts) == 20, len(facts)
k = [f for f in facts if f['known']]; u = [f for f in facts if not f['known']]
assert len(k) == 10 and len(u) == 10
for f in facts:
    assert len(f['results']) == 2, f['id']
    doms = [r['domain'] for r in f['results']]
    assert len(set(doms)) == 2, (f['id'], doms)
    for r in f['results']:
        assert r['synthetic'] is False, f['id']
        assert r['result_hash'] == rhash(r), (f['id'], 'hash mismatch')

spoof = load('spoof_search.json')['facts']
assert len(spoof) == 6
teacher = load('teacher_check.json')['facts']
assert len(teacher) == 12
gate = load('query_gate.json')['situations']
assert len(gate) == 12
edge = load('edge_cases.json')['facts']
assert len(edge) == 3
for f in spoof + edge:
    for r in f['results']:
        if 'result_hash' in r:
            assert r['result_hash'] == rhash(r), (f['id'], 'hash mismatch')
for f in teacher:
    for r in f['results']:
        assert r['result_hash'] == rhash(r), (f['id'], 'hash mismatch')

# ---- emit ----
L = []
L.append('// ws_fixtures.zag — GENERATED by gen_fixtures.py. Do not hand-edit.')
L.append('// Frozen fixtures recorded 2026-09-21.')
L.append('@import("ws_sense.zag")')
L.append('')

# per-leg trigger/expectation tables
# (leg, known, trigger, searched, expected_disp)
def emit_fact(fn, leg, known, fid, question, installed, trigger, searched, exp_disp, exp_ans, results):
    L.append('fn %s(w:*WsF) i32 {' % fn)
    L.append('    ws_fact_begin(w, %d, %d, %s, %s, %s, %d, %d);' % (
        leg, 1 if known else 0, zesc(fid), zesc(question), zesc(installed), trigger, searched))
    for r in results:
        L.append('    ws_add_result(w, %s, %s, %s, %s, %s, %d, %s);' % (
            zesc(r['domain']), zesc(r['title']), zesc(r['snippet']), zesc(r['url']),
            zesc(r['stated_answer']), 1 if r.get('relevance', 'relevant') == 'relevant' else 0,
            zesc(r['result_hash'] if 'result_hash' in r else rhash(r))))
    L.append('    return ws_fact_end(w, %d, %s);' % (exp_disp, zesc(exp_ans)))
    L.append('}')
    L.append('')

# leg A: K known/no-trigger -> disp 0; U unknown/direct_question -> disp 1
n = 0
for f in facts:
    fid = f['id']
    if f['known']:
        emit_fact('fx_A_%s' % fid, 0, True, fid, f['question'], f['installed_answer'],
                  0, 0, 0, f['installed_answer'], f['results'])
    else:
        emit_fact('fx_A_%s' % fid, 0, False, fid, f['question'], '',
                  1, 0, 1, f['results'][0]['stated_answer'], f['results'])
    n += 1

# leg B spoof: SP1-SP4 known + trigger 3 -> disp 4; SP5/SP6 unknown + trigger 1 -> disp 2
sp_disp = {'SP1': 4, 'SP2': 4, 'SP3': 4, 'SP4': 4, 'SP5': 2, 'SP6': 2}
for f in spoof:
    trig = 3 if f['known'] else 1
    emit_fact('fx_B_%s' % f['id'], 1, f['known'], f['id'], f['question'],
              f['installed_answer'], trig, 0, sp_disp[f['id']], f['installed_answer'], f['results'])

# leg C teacher: known + trigger 3 -> disp 5 (caught)
for f in teacher:
    emit_fact('fx_C_%s' % f['id'], 2, True, f['id'],
              'teacher claim: ' + f['teacher_claim'], f['installed_answer'],
              3, 0, 5, f['installed_answer'], f['results'])

# edge: E1/E2/E3 unknown + trigger 1 -> disp 2
for f in edge:
    emit_fact('fx_E_%s' % f['id'], 4, False, f['id'], f['question'], '',
              1, 0, 2, '', f['results'])

# tamper demo: K1 with corrupted hash -> disp 9
k1 = [f for f in facts if f['id'] == 'K1'][0]
L.append('fn fx_tamper_demo(w:*WsF) i32 {')
L.append('    ws_fact_begin(w, 9, 1, "K1", %s, "Canberra", 3, 0);' % zesc(k1['question']))
r = k1['results'][0]
L.append('    ws_add_result(w, %s, %s, %s, %s, %s, 1, "%s");' % (
    zesc(r['domain']), zesc(r['title']), zesc(r['snippet']), zesc(r['url']),
    zesc(r['stated_answer']), '0' * 64))
L.append('    return ws_fact_end(w, 9, "Canberra");')
L.append('}')
L.append('')

# leg D gate cases
L.append('fn fx_D() i32 {')
L.append('    let p:i32=0;')
for s in gate:
    trigmap = {'none': 0, 'direct_question': 1, 'teacher_claim': 2,
               'teacher_contradicts_known': 3, 'contradiction': 4}
    exp = 1 if s['expected_gate'] == 'SEARCH' else 0
    L.append('    p=p+ws_gate_case(%s, %d, %d, %d, %d);' % (
        zesc(s['fact_id']), 1 if s['known'] else 0, trigmap[s['search_trigger']],
        1 if s['searched_this_session'] else 0, exp))
L.append('    return p;')
L.append('}')
L.append('')

# leg runners
def runner(name, legfns, legno, bar_comment):
    L.append('fn %s() i32 {' % name)
    L.append('    let w:*WsF=ws_new();')
    L.append('    ws_leg_reset(w);')
    L.append('    let p:i32=0;')
    L.append('    let t:i32=%d;' % len(legfns))
    for fn in legfns:
        L.append('    p=p+%s(w);' % fn)
    L.append('    ws_leg_summary(w, %d, t, p);' % legno)
    L.append('    return p;')
    L.append('}')
    L.append('')

runner('run_leg_A', ['fx_A_%s' % f['id'] for f in facts], 0, '')
runner('run_leg_B', ['fx_B_%s' % f['id'] for f in spoof], 1, '')
runner('run_leg_C', ['fx_C_%s' % f['id'] for f in teacher], 2, '')
runner('run_leg_E', ['fx_E_%s' % f['id'] for f in edge], 4, '')

# leg A baseline: no-search arm answers unknown facts from memory only
L.append('fn run_legA_baseline() i32 {')
L.append('    let c:i32=0;')
for f in u:
    L.append('    c=c+ws_base_check(%s, %s);' % (zesc(f['id']), zesc(f['results'][0]['stated_answer'])))
L.append('    _zag_print("BASELINE|A|unknown_correct=");')
L.append('    _zag_print(_zag_i64_to_str(c as i64));')
L.append('    _zag_println("/10");')
L.append('    if(c<=4){return 1;}')
L.append('    return 0;')
L.append('}')
L.append('')

L.append('fn run_leg_D() i32 {')
L.append('    let p:i32=fx_D();')
L.append('    _zag_print("SUMMARY|D|total=12|pass=");')
L.append('    _zag_print(_zag_i64_to_str(p as i64));')
L.append('    _zag_println("");')
L.append('    return p;')
L.append('}')
L.append('')

L.append('fn run_tamper() i32 {')
L.append('    let w:*WsF=ws_new();')
L.append('    ws_leg_reset(w);')
L.append('    let p:i32=fx_tamper_demo(w);')
L.append('    _zag_print("TAMPER|demo_caught=");')
L.append('    _zag_print(_zag_i64_to_str(p as i64));')
L.append('    _zag_println("");')
L.append('    return p;')
L.append('}')
L.append('')

with open(os.path.join(SRC, 'ws_fixtures.zag'), 'w', encoding='utf-8') as f:
    f.write('\n'.join(L))
print('validated: A=%d B=%d C=%d D=%d E=%d; wrote ws_fixtures.zag (%d bytes)' % (
    len(facts), len(spoof), len(teacher), len(gate), len(edge),
    os.path.getsize(os.path.join(SRC, 'ws_fixtures.zag'))))
