#!/usr/bin/env python3
"""Generate Zag corpus fixtures for the joke/lie/satire trial.

Usage:
  gen_corpus.py corpus fixtures/corpus.json src/j_corpus.zag j_
  gen_corpus.py helper fixtures/helper.json src/j_helper.zag j_
  gen_corpus.py calib  calibration/dev.json src/c_calib.zag c_

Folding (frozen, documented in PREREG §2): lowercase; keep bytes 32-126;
every other char -> space; collapse whitespace runs to one space; strip.
Deterministic. The manifest keeps original UTF-8; the classifier reads folded.
"""
import json
import re
import sys

INTENT_CODE = {"SINCERE": 1, "JOKING": 2, "SATIRE": 3, "DECEPTIVE": 4, "UNCERTAIN": 5}


def fold(s):
    s = s.lower()
    out = []
    for ch in s:
        o = ord(ch)
        out.append(ch if 32 <= o <= 126 else " ")
    s = "".join(out)
    return re.sub(r"\s+", " ", s).strip()


def zag_esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit_str_fn(lines, prefix, name, items, key):
    lines.append(f"fn {prefix}{name}(i:i32)[]u8 {{")
    for idx, it in enumerate(items):
        v = zag_esc(it[key])
        lines.append(f'    if(i=={idx}){{return "{v}";}}')
    lines.append('    return "";')
    lines.append("}")
    lines.append("")


def emit_int_fn(lines, prefix, name, items, key):
    lines.append(f"fn {prefix}{name}(i:i32)i32 {{")
    for idx, it in enumerate(items):
        lines.append(f"    if(i=={idx}){{return {it[key]};}}")
    lines.append("    return 0;")
    lines.append("}")


def main():
    kind, inp, outp, prefix = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
    with open(inp, encoding="utf-8") as f:
        data = json.load(f)
    items = data["items"] if isinstance(data, dict) and "items" in data else \
            data["judgments"] if isinstance(data, dict) and "judgments" in data else data

    lines = [f"// GENERATED by gen_corpus.py from {inp} — do not hand-edit.", ""]
    if kind == "corpus":
        for it in items:
            combo = (it.get("title", "") + " " + it["body"]).strip()
            it["_text"] = fold(combo)
            it["_url"] = fold(it["url"])
        lines.append(f"fn {prefix}nitems()i32 {{ return {len(items)}; }}")
        lines.append("")
        emit_str_fn(lines, prefix, "id", items, "id")
        emit_str_fn(lines, prefix, "cat", items, "category")
        emit_str_fn(lines, prefix, "text", items, "_text")
        emit_str_fn(lines, prefix, "url", items, "_url")
        emit_str_fn(lines, prefix, "title", items, "title")
    elif kind == "helper":
        for it in items:
            it["_intent"] = INTENT_CODE[it["intent"]]
            it["_marker"] = fold(it["marker"])
        lines.append(f"fn {prefix}h_n()i32 {{ return {len(items)}; }}")
        lines.append("")
        emit_int_fn(lines, prefix, "h_intent", items, "_intent")
        emit_str_fn(lines, prefix, "h_marker", items, "_marker")
    elif kind == "calib":
        for it in items:
            combo = (it.get("title", "") + " " + it["body"]).strip()
            it["_text"] = fold(combo)
            it["_url"] = fold(it.get("url", ""))
        lines.append(f"fn {prefix}nitems()i32 {{ return {len(items)}; }}")
        lines.append("")
        emit_str_fn(lines, prefix, "id", items, "id")
        emit_str_fn(lines, prefix, "text", items, "_text")
        emit_str_fn(lines, prefix, "url", items, "_url")
    else:
        raise SystemExit(f"unknown kind {kind}")

    with open(outp, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {outp} ({len(items)} items)")


if __name__ == "__main__":
    main()
