#!/usr/bin/env python3
"""WS3-C MW sibling port generator (PREREG_WS3C.md §7, frozen 2026-09-24).

Builds src/mw_after.zag from the frozen tnn-lab/mixed-web/src/mw_sense.zag
by exactly two surgical edits (each asserted to hit exactly once):
  1. MAJORITY block: settle -> WITHHOLD with rule tag MAJORITY_RETIRED.
  2. CORROB block: settle -> WITHHOLD with rule tag CORROB_HELD.
RECENCY / TIE / INSUFFICIENT untouched.

Also emits build_c/drv_mw_frozen.zag (@import mw_sense.zag) and
build_c/drv_mw_port.zag (@import mw_after.zag): the same 8-case deliberation
driver against both modules. Report only; no kill bars.

No RNG, no timestamps anywhere.
"""
import os

WS3 = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(WS3, "src")
BUILD = os.path.join(WS3, "build_c")
FROZEN = os.path.expanduser("~/workspace/tnn-lab/mixed-web/src/mw_sense.zag")

HEADER = """// mw_after.zag — WS3-C port of the frozen mixed-web deliberation sense.
// GENERATED by src/gen_mw_port.py — do not hand-edit.
// Source: tnn-lab/mixed-web/src/mw_sense.zag (frozen).
// Port (PREREG_WS3C.md §7, report only): the WS3-A retune principle
// ("popularity never settles") applied to the sibling:
//   1. MAJORITY rule retired: a would-be majority now WITHHOLDS with rule
//      tag MAJORITY_RETIRED instead of CONVERGEing.
//   2. CORROB rule held: near-unanimity is still popularity; mw has no
//      PROVISIONAL verdict, so the principled port WITHHOLDS with rule tag
//      CORROB_HELD (this is the port's cost, flagged for Micah).
// RECENCY / TIE / INSUFFICIENT are untouched.

"""

OLD_MAJORITY = 'rule="MAJORITY";chosen=mw_c_ans(w,best);conv=1;'
NEW_MAJORITY = 'rule="MAJORITY_RETIRED";chosen=mw_empty();conv=0;'
OLD_CORROB = 'rule="CORROB";chosen=mw_c_ans(w,best);conv=1;'
NEW_CORROB = 'rule="CORROB_HELD";chosen=mw_empty();conv=0;'

# (case id, temporal, [(domain, answer, recency)])
CASES = [
    ("MW1", 0, [("d1.ex", "Alpha", 0), ("d2.ex", "Alpha", 0),
                ("d3.ex", "Alpha", 0), ("d4.ex", "Alpha", 0),
                ("d5.ex", "Beta", 0)]),
    ("MW2", 0, [("d1.ex", "Alpha", 0), ("d2.ex", "Alpha", 0),
                ("d3.ex", "Alpha", 0), ("d4.ex", "Alpha", 0),
                ("d5.ex", "Alpha", 0), ("d6.ex", "Alpha", 0),
                ("d7.ex", "Beta", 0)]),
    ("MW3", 0, [("d1.ex", "Alpha", 0), ("d2.ex", "Alpha", 0),
                ("d3.ex", "Alpha", 0)]),
    ("MW4", 0, [("d1.ex", "Alpha", 0), ("d2.ex", "Alpha", 0)]),
    ("MW5", 0, [("d1.ex", "Alpha", 0), ("d2.ex", "Alpha", 0),
                ("d3.ex", "Beta", 0), ("d4.ex", "Beta", 0)]),
    ("MW6", 0, [("d1.ex", "Alpha", 0)]),
    ("MW7", 1, [("g1.ex", "Gamma", 2027), ("g2.ex", "Gamma", 2027),
                ("d1.ex", "Delta", 2024), ("e1.ex", "Epsilon", 2020)]),
    ("MW8", 0, [("a1.ex", "Alpha", 0), ("a2.ex", "Alpha", 0),
                ("a3.ex", "Alpha", 0), ("b1.ex", "Beta", 0),
                ("b2.ex", "Beta", 0)]),
]


def zag_str(s):
    assert '"' not in s and '\\' not in s and '|' not in s, s
    return '"%s"' % s


def build_port():
    with open(FROZEN) as f:
        src = f.read()
    for old, new in ((OLD_MAJORITY, NEW_MAJORITY), (OLD_CORROB, NEW_CORROB)):
        n = src.count(old)
        assert n == 1, "expected exactly 1 hit for %r, got %d" % (old[:40], n)
        src = src.replace(old, new)
    out = os.path.join(SRC, "mw_after.zag")
    with open(out, "w") as f:
        f.write(HEADER + src)
    print("wrote", out)


def gen_driver(modname):
    lines = []
    lines.append("// GENERATED by gen_mw_port.py — do not hand-edit.")
    lines.append('@import("%s")' % modname)
    lines.append("")
    for cid, temporal, results in CASES:
        lines.append("fn mc_%s()void {" % cid)
        lines.append("    let w:*MwF=mw_new();")
        lines.append('    mw_fact_begin(w,%s,"q-%s",%d);'
                     % (zag_str(cid), cid, temporal))
        for dom, ans, rec in results:
            lines.append("    mw_add_result(w,%s,%s,%d);"
                         % (zag_str(dom), zag_str(ans), rec))
        lines.append("    let v:i32=mw_deliberate(w);")
        lines.append("    mw_fact_end(w);")
        lines.append('    _zag_print("MW|%s|");' % cid)
        lines.append('    if(v==1){_zag_print("1|");}else{_zag_print("0|");}')
        lines.append("    _zag_print(w.*.chosen);")
        lines.append('    _zag_print("|");')
        lines.append("    _zag_print(w.*.rule);")
        lines.append('    _zag_println("");')
        lines.append("    return;")
        lines.append("}")
        lines.append("")
    lines.append("fn main()i32 {")
    for cid, _, _ in CASES:
        lines.append("    mc_%s();" % cid)
    lines.append('    _zag_println("MWDONE");')
    lines.append("    return 0;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    build_port()
    os.makedirs(BUILD, exist_ok=True)
    for name, mod in (("frozen", "mw_sense.zag"), ("port", "mw_after.zag")):
        p = os.path.join(BUILD, "drv_mw_%s.zag" % name)
        with open(p, "w") as f:
            f.write(gen_driver(mod))
        print("wrote", p)


if __name__ == "__main__":
    main()
