#!/usr/bin/env python3
"""Resumable fixture generation for the senses rematch.

The frozen generator is per-index deterministic:
rng = Rng(stream_seed(MASTER_SEED, stream, idx)), so a missing fixture
pNNNN can be regenerated byte-identically at any time. This driver only
generates (fixture, .truth) pairs that are absent (or empty), making it
safe to re-run after a reboot.

Usage: resume_gen.py <name> <seed> <mult> [task_csv]
  task_csv: e.g. "2,3" to only do t3/t4 (0-based task indices); default all.
Writes MANIFEST.sha256 + counts.json when every task dir is complete.
"""
import os, sys, hashlib, json, time

sys.path.insert(0, "/home/hatch/workspace/senses-rebuild/harness")
import gen

CACHE = "/home/hatch/workspace/senses-rebuild/harness/fixtures/_photos"
WORK = "/home/hatch/workspace/senses-rematch/data"
BASE = [60, 40, 90, 60, 60, 60]
GEXT = {0: ".img", 1: ".img", 2: ".img", 3: ".pcm", 4: ".pcm", 5: ".vid"}
PHOTO_TASKS = {1, 2, 5}
GENS = [gen.gen_t1, gen.gen_t2, gen.gen_t3, gen.gen_t4, gen.gen_t5, gen.gen_t6]

def sha256_file(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for ch in iter(lambda: f.read(1 << 20), b""):
            h.update(ch)
    return h.hexdigest()

def present(path):
    return os.path.exists(path) and os.path.getsize(path) > 0

def main():
    name, seed, mult = sys.argv[1], int(sys.argv[2]), int(sys.argv[3])
    only = ([int(x) for x in sys.argv[4].split(",")] if len(sys.argv) > 4
            else list(range(6)))
    assert len(os.listdir(CACHE)) >= 170, "photo cache incomplete"
    gen.MASTER_SEED = seed
    gen.PHOTOS = CACHE
    outdir = os.path.join(WORK, name)
    gen.FIX = outdir
    os.makedirs(outdir, exist_ok=True)
    for ti in only:
        tdir = gen.DIRS_T[ti]
        n = BASE[ti] * mult
        d = os.path.join(outdir, tdir, "primary")
        os.makedirs(d, exist_ok=True)
        ext = GEXT[ti]
        missing = [idx for idx in range(n)
                   if not (present(os.path.join(d, "p%03d%s" % (idx, ext))) and
                           present(os.path.join(d, "p%03d%s.truth" % (idx, ext))))]
        print("%s %s: %d/%d missing" % (name, tdir, len(missing), n), flush=True)
        t0 = time.time()
        for k, idx in enumerate(missing):
            if ti in PHOTO_TASKS:
                GENS[ti](ti, "primary", idx, 170)
            else:
                GENS[ti](ti, "primary", idx)
            if (k + 1) % 500 == 0:
                print("  %s: %d/%d (%.0fs)" % (tdir, k + 1, len(missing),
                                               time.time() - t0), flush=True)
        print("%s %s: complete in %.1fs" % (name, tdir, time.time() - t0),
              flush=True)
    # manifest when all six task dirs are complete
    complete = True
    manifest = []
    counts = {}
    for ti, tdir in enumerate(gen.DIRS_T):
        n = BASE[ti] * mult
        d = os.path.join(outdir, tdir, "primary")
        ext = GEXT[ti]
        files = [f for f in os.listdir(d) if f.endswith(ext)]
        if len(files) != n:
            complete = False
            break
        for f in sorted(files):
            manifest.append((os.path.join(tdir, "primary", f),
                             sha256_file(os.path.join(d, f))))
        truths = {}
        for f in sorted(files):
            tv = open(os.path.join(d, f + ".truth")).read().strip().split("=")[1]
            truths[tv] = truths.get(tv, 0) + 1
        counts[tdir] = {"n": n, "truths": truths}
    if complete:
        with open(os.path.join(outdir, "MANIFEST.sha256"), "w") as f:
            for rel, h in manifest:
                f.write("%s  %s\n" % (h, rel))
        with open(os.path.join(outdir, "counts.json"), "w") as f:
            json.dump({"name": name, "seed": seed, "mult": mult,
                       "tasks": counts}, f, indent=1)
        print("%s: MANIFEST written (%d fixtures)" % (name, len(manifest)),
              flush=True)
    else:
        print("%s: not all tasks complete, manifest deferred" % name, flush=True)

main()
